import Mathlib
import ToyApollo.Output.def_13_1

/-
TASK ID: def_13_2
TYPE: Definition
SOURCE PLAN: chapter13-finite-partition
TASK CONTENT:
\begin{defbox}{13.2}
\end{defbox}

Consider a finite partition. A1,A2,...,A k of the sample space. \Omega Let. \mathcal{G}be the\sigma-

algebra generated by A1,A2,...,A k For any \mathcal{G}-measurable function in L1(P) ,

define the conditional expectation given \mathcal{G}by

E[X\vert\mathcal{G}] \coloneqq

k\sum

i=1

E[X\vertAi]1Ai .

A few important notes are in order:

The conditional expectation given \mathcal{G}is a random variable. We can write it as

E[X\vert\mathcal{G}]() to emphasize that the input of the function is . .

E[X\vert\mathcal{G}] is a simple function that is \mathcal{G}-measurable and constant on each Ai The

value ofE[X\vert\mathcal{G}]() for. \in Ai isE[X\vertAi].

If Ai =\emptyset or P(Ai) = 0, the conditional expectation E[X\vertAi] given Ai is not

defined, butE[X\vert\mathcal{G}] is still well-defined.

Since E[X\vert\mathcal{G}] is a random variable, a natural question is how to compute the

expectation.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open scoped BigOperators

noncomputable section

/-- A finite family of sets is a partition of `Ω` when it covers every point and
distinct atoms are disjoint. -/
def def_13_2_isFinitePartition {Ω ι : Type*} (A : ι → Set Ω) : Prop :=
  (∀ ω : Ω, ∃ i : ι, ω ∈ A i) ∧
    ∀ i j : ι, i ≠ j → Disjoint (A i) (A j)

/-- The sigma-field `𝓖` is generated by the atoms `A i`: it contains every
atom, and it is the smallest sigma-field with that property. -/
def def_13_2_generatesSigmaField {Ω ι : Type*}
    (𝓖 : MeasurableSpace Ω) (A : ι → Set Ω) : Prop :=
  (∀ i : ι, @MeasurableSet Ω 𝓖 (A i)) ∧
    ∀ 𝓗 : MeasurableSpace Ω,
      (∀ i : ι, @MeasurableSet Ω 𝓗 (A i)) →
        ∀ ⦃B : Set Ω⦄, @MeasurableSet Ω 𝓖 B → @MeasurableSet Ω 𝓗 B

/-- Source-domain contract for Definition 13.2.  The partition is finite, the
listed atoms generate `𝓖`, and the input random variable is `𝓖`-measurable and
in `L¹(P)`. -/
def def_13_2_sourceDomain {Ω ι : Type*} [𝓕 : MeasurableSpace Ω] [Fintype ι]
    (P : Measure Ω) (𝓖 : MeasurableSpace Ω) (A : ι → Set Ω) (X : Ω → ℝ) : Prop :=
  IsProbabilityMeasure P ∧
    def_13_2_isFinitePartition A ∧
      (∀ i : ι, MeasurableSet (A i)) ∧
        (∀ i : ι, P (A i) ≠ ⊤) ∧
          def_13_2_generatesSigmaField 𝓖 A ∧
            (∀ ⦃B : Set Ω⦄, @MeasurableSet Ω 𝓖 B → @MeasurableSet Ω 𝓕 B) ∧
              Measurable[𝓖] X ∧
                Integrable X P

/-- The guarded event-conditional scalar used on one atom.  It calls
Definition 13.1 only when the atom has positive probability; zero-probability
atoms receive the harmless representative value `0`. -/
def def_13_2_atomConditionalExpectation {Ω ι : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ) (i : ι)
    (hA : MeasurableSet (A i)) (hA_top : P (A i) ≠ ⊤) : ℝ := by
  classical
  exact
    if hA0 : P (A i) = 0 then
      0
    else
      def_13_1 P (A i) hA hA0 hA_top X

/-- The `i`-th summand `E[X|A_i] 1_{A_i}` in Definition 13.2. -/
def def_13_2_atomTerm {Ω ι : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) (i : ι) : Ω → ℝ :=
  (A i).indicator
    (fun _ => def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i))

/-- Conditional expectation with respect to the finite partition
`A_1,...,A_k`, as the finite sum `∑ i, E[X|A_i] 1_{A_i}`. -/
def def_13_2_finitePartitionConditionalExpectation {Ω ι : Type*}
    [MeasurableSpace Ω] [Fintype ι]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) : Ω → ℝ := by
  classical
  exact fun ω => ∑ i, def_13_2_atomTerm P A X hA hA_top i ω

theorem def_13_2_atomTerm_of_mem {Ω ι : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) (i : ι) {ω : Ω}
    (hω : ω ∈ A i) :
    def_13_2_atomTerm P A X hA hA_top i ω =
      def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i) := by
  simp [def_13_2_atomTerm, hω]

theorem def_13_2_atomConditionalExpectation_of_wellDefined {Ω ι : Type*}
    [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ) (i : ι)
    (hA : MeasurableSet (A i)) (hA0 : P (A i) ≠ 0)
    (hA_top : P (A i) ≠ ⊤) :
    def_13_2_atomConditionalExpectation P A X i hA hA_top =
      def_13_1 P (A i) hA hA0 hA_top X := by
  rw [def_13_2_atomConditionalExpectation]
  simp [hA0]

theorem def_13_2_atomConditionalExpectation_of_null {Ω ι : Type*}
    [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ) (i : ι)
    (hA : MeasurableSet (A i)) (hA_top : P (A i) ≠ ⊤)
    (hA0 : P (A i) = 0) :
    def_13_2_atomConditionalExpectation P A X i hA hA_top = 0 := by
  rw [def_13_2_atomConditionalExpectation]
  simp [hA0]

theorem def_13_2_atomTerm_of_mem_wellDefined {Ω ι : Type*}
    [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top_all : ∀ i : ι, P (A i) ≠ ⊤) (i : ι) {ω : Ω}
    (hω : ω ∈ A i)
    (hA0 : P (A i) ≠ 0) (hA_top_i : P (A i) ≠ ⊤) :
    def_13_2_atomTerm P A X hA hA_top_all i ω =
      def_13_1 P (A i) (hA i) hA0 hA_top_i X := by
  rw [def_13_2_atomTerm_of_mem P A X hA hA_top_all i hω]
  exact def_13_2_atomConditionalExpectation_of_wellDefined
    P A X i (hA i) hA0 hA_top_i

theorem def_13_2_atomTerm_of_not_mem {Ω ι : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) (i : ι) {ω : Ω}
    (hω : ω ∉ A i) :
    def_13_2_atomTerm P A X hA hA_top i ω = 0 := by
  simp [def_13_2_atomTerm, hω]

theorem def_13_2_apply {Ω ι : Type*} [MeasurableSpace Ω] [Fintype ι]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) (ω : Ω) :
    def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω =
      ∑ i, def_13_2_atomTerm P A X hA hA_top i ω := by
  classical
  rfl

/-- Exported Definition 13.2: `Y` is the finite-partition conditional
expectation of `X` with respect to the sigma-field `𝓖` generated by the
partition atoms. -/
def def_13_2 {Ω ι : Type*} [𝓕 : MeasurableSpace Ω] [Fintype ι]
    (P : Measure Ω) (𝓖 : MeasurableSpace Ω) (A : ι → Set Ω)
    (X Y : Ω → ℝ) : Prop :=
  @def_13_2_sourceDomain Ω ι 𝓕 _ P 𝓖 A X ∧
    ∃ hA : ∀ i : ι, @MeasurableSet Ω 𝓕 (A i),
      ∃ hA_top : ∀ i : ι, P (A i) ≠ ⊤,
        Y = @def_13_2_finitePartitionConditionalExpectation Ω ι 𝓕 _
          P A X hA hA_top

theorem def_13_2_formula {Ω ι : Type*} [𝓕 : MeasurableSpace Ω] [Fintype ι]
    {P : Measure Ω} {𝓖 : MeasurableSpace Ω} {A : ι → Set Ω}
    {X Y : Ω → ℝ} (h : @def_13_2 Ω ι 𝓕 _ P 𝓖 A X Y) :
    ∃ hA : ∀ i : ι, @MeasurableSet Ω 𝓕 (A i),
      ∃ hA_top : ∀ i : ι, P (A i) ≠ ⊤,
        Y = @def_13_2_finitePartitionConditionalExpectation Ω ι 𝓕 _
          P A X hA hA_top :=
  h.2
