import Mathlib
import ToyApollo.Output.thm_2_6

/-
TASK ID: def_2_7
TYPE: Definition
SOURCE PLAN: 43_chap2_borel_sets
TASK CONTENT:
\begin{defbox}{2.7}
The $\sigma$-field $\mathcal{F}$ in Theorem 2.6 is called the $\sigma$-\textit{field generated by} $\mathcal{C}$ and is denoted by $\sigma(\mathcal{C})$. If $(B_i)_{i\ge 1}$ is a sequence of sets in $\Omega$, then the $\sigma$-field generated by this sequence of sets is denoted by $\sigma((B_i)_{i\ge 1})$.
\end{defbox}
-/

-- WRITE FINAL LEAN CODE BELOW

open Set MeasureTheory

/-- The sigma-field generated by a collection of subsets. -/
@[reducible]
def generatedSigmaField {Ω : Type*} (C : Set (Set Ω)) : MeasurableSpace Ω :=
  MeasurableSpace.generateFrom C

/-- The sigma-field generated by a sequence of subsets. -/
@[reducible]
def generatedSigmaFieldSeq {Ω : Type*} (B : ℕ → Set Ω) : MeasurableSpace Ω :=
  generatedSigmaField (Set.range B)

theorem generatedSigmaField_contains {Ω : Type*} (C : Set (Set Ω)) :
    ∀ s ∈ C, @MeasurableSet Ω (generatedSigmaField C) s :=
  (thm_2_6 C).1

theorem generatedSigmaFieldSeq_contains {Ω : Type*} (B : ℕ → Set Ω) (n : ℕ) :
    @MeasurableSet Ω (generatedSigmaFieldSeq B) (B n) := by
  exact generatedSigmaField_contains (Set.range B) (B n) ⟨n, rfl⟩

/-- Definition 2.7: the generated sigma-field notation `σ(C)`. -/
def def_2_7 {Ω : Type*} (C : Set (Set Ω)) : MeasurableSpace Ω :=
  generatedSigmaField C
