import Mathlib
import ToyApollo.Output.def_13_3

/-
TASK ID: def_13_4
TYPE: Definition
SOURCE PLAN: chapter13-sub-sigma-algebra
TASK CONTENT:
\begin{defbox}{13.4}
\end{defbox}

The conditional expectation of a random variable X given random variable Y is

defined as

E[X\vertY] \coloneqqE[X\vert\sigma(Y)].

For a family of random variables .{Yi}i\inI , the conditional expectation of X given

{Yi}i\inI is defined as

E[X\vert{Yi}i\inI ] \coloneqqE[X\vert\sigma({Yi}i\inI )].

In particular, the conditional expectation of X given random variables Y and Z

is defined as

E[X\vertY,Z ] \coloneqqE[X\vert\sigma(Y,Z) ].

Conditional probability is defined in terms of conditional expectation.

In the above definition, \sigma(Y,Z) means the smallest \sigma-algebra under which both

Y and Z are measurable, and \sigma({Yi}i\inI ) denotes the smallest \sigma-algebra such that

all random variables. Yi 's are measurable.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open ProbabilityTheory

noncomputable section

/- The sigma-field generated by one observed random variable. In Lean this is
the comap of the Borel/measurable-space structure on the observation space. -/
@[reducible]
def def_13_4_sigma {Ω S : Type*} [MeasurableSpace S] (Y : Ω → S) :
    SigmaField Ω :=
  (inferInstance : MeasurableSpace S).comap Y

/-- If the observed random variable is ambient-measurable, then its generated
sigma-field is a sub-sigma-field of the ambient sigma-field. -/
theorem def_13_4_sigma_subSigma_of_measurable {Ω S : Type*}
    [𝓕 : MeasurableSpace Ω] [MeasurableSpace S] {Y : Ω → S}
    (hY : Measurable Y) :
    IsSubSigmaField (def_13_4_sigma Y) 𝓕 := by
  intro A hA
  exact hY.comap_le A hA

/-- Definition 13.4: `CE` is a version of `E[X | Y]` when it is a conditional
expectation of `X` with respect to `sigma(Y)`. -/
def def_13_4 {Ω S : Type*} [𝓕 : MeasurableSpace Ω] [MeasurableSpace S]
    (P : Measure Ω) (Y : Ω → S)
    (hσY : IsSubSigmaField (def_13_4_sigma Y) 𝓕)
    (X CE : Ω → ℝ) : Prop :=
  @def_13_3 Ω 𝓕 P (def_13_4_sigma Y) hσY X CE

/- The sigma-field generated by a pair of observed random variables. -/
@[reducible]
def def_13_4_pairSigma {Ω S T : Type*}
    [MeasurableSpace S] [MeasurableSpace T] (Y : Ω → S) (Z : Ω → T) :
    SigmaField Ω :=
  (inferInstance : MeasurableSpace (S × T)).comap (fun ω => (Y ω, Z ω))

/-- Measurable observations generate a sub-sigma-field of the ambient
sigma-field. -/
theorem def_13_4_pairSigma_subSigma_of_measurable {Ω S T : Type*}
    [𝓕 : MeasurableSpace Ω] [MeasurableSpace S] [MeasurableSpace T]
    {Y : Ω → S} {Z : Ω → T} (hY : Measurable Y) (hZ : Measurable Z) :
    IsSubSigmaField (def_13_4_pairSigma Y Z) 𝓕 := by
  intro A hA
  exact (hY.prodMk hZ).comap_le A hA

/-- Conditional expectation given two random variables, defined as conditioning
on the sigma-field generated by the pair. -/
def def_13_4_pair {Ω S T : Type*} [𝓕 : MeasurableSpace Ω]
    [MeasurableSpace S] [MeasurableSpace T] (P : Measure Ω)
    (Y : Ω → S) (Z : Ω → T)
    (hσYZ : IsSubSigmaField (def_13_4_pairSigma Y Z) 𝓕)
    (X CE : Ω → ℝ) : Prop :=
  @def_13_3 Ω 𝓕 P (def_13_4_pairSigma Y Z) hσYZ X CE

/- The sigma-field generated by a family of observed random variables. -/
@[reducible]
def def_13_4_familySigma {Ω I : Type*} {S : I → Type*}
    [∀ i, MeasurableSpace (S i)] (Y : ∀ i, Ω → S i) : SigmaField Ω :=
  (inferInstance : MeasurableSpace ((i : I) → S i)).comap
    (fun ω i => Y i ω)

/-- Conditional expectation given a family of random variables, defined as
conditioning on the sigma-field generated by the whole family. -/
def def_13_4_family {Ω I : Type*} {S : I → Type*}
    [𝓕 : MeasurableSpace Ω] [∀ i, MeasurableSpace (S i)]
    (P : Measure Ω) (Y : ∀ i, Ω → S i)
    (hσY : IsSubSigmaField (def_13_4_familySigma Y) 𝓕)
    (X CE : Ω → ℝ) : Prop :=
  @def_13_3 Ω 𝓕 P (def_13_4_familySigma Y) hσY X CE
