import Mathlib
import ToyApollo.Output.def_13_6
import ToyApollo.Output.thm_12_6

/-
TASK ID: def_13_7
TYPE: Definition
SOURCE PLAN: chapter13-martingale-stopping-time
TASK CONTENT:
\begin{defbox}{13.7}
\end{defbox}

A sequence of random variables .(Xn)\infty

n=0 is a martingale relative to filtration

(\mathcal{F}n)\infty

n=0 if it satisfies the following three conditions:

1. E[\vertXn\vert] < \infty for all n, ie.,Xn \in L1(P) .

2. .(Xn)\infty

n=0 is adapted to .(\mathcal{F}n)\infty

n=0.

3. E[Xn+1\vert\mathcal{F}n]= Xn as. forn \geq 0.

The third condition captures the idea that the expected value of the next

observation, given the current and all past observations, is equal to the current

observation.

When the filtration is defined by a sequence of random variables .(Yn)n\geq0, then

random variable Xn is a measurable function of .(Y0,Y 1,...,Y n) (Theorem 12.6).

We can express the last condition in Definition 13.7 as E[Xn+1\vertY0,Y 1,...,Y n]=

Xn.

Martingale can be used to model a variety of stochastic processes, including a

betting system, where Xn represents the amount of money in the gambler's pocket

at time n The essence of a martingale is that, regardless of the betting strategy

adopted, the expected value of Xn+1 in the next step, given the history up to time

n, is always equal to the current value Xn. In other words, a martingale represents a

fair game.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open scoped ProbabilityTheory

noncomputable section

/-- The one-step martingale condition from Definition 13.7:
`E[X_{n+1} | F_n] = X_n` almost surely. -/
def def_13_7_oneStepCondition {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (P : Measure Ω) (𝓕n : ℕ → MeasurableSpace Ω)
    (X : ℕ → Ω → ℝ) : Prop :=
  ∀ n : ℕ, P[X (n + 1) | 𝓕n n] =ᵐ[P] X n

/-- Definition 13.7: a real-valued stochastic process is a martingale relative
to a filtration when it is integrable, adapted, and satisfies the one-step
conditional expectation identity. -/
def def_13_7 {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (P : Measure Ω) (𝓕n : ℕ → MeasurableSpace Ω)
    (X : ℕ → Ω → ℝ) : Prop :=
  def_13_6_isFiltration (𝓕 := 𝓕) 𝓕n ∧
    (∀ n : ℕ, Integrable (X n) P) ∧
    def_13_6_adapted 𝓕n X ∧
    def_13_7_oneStepCondition P 𝓕n X

theorem def_13_7_isFiltration {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓕n : ℕ → MeasurableSpace Ω} {X : ℕ → Ω → ℝ}
    (h : def_13_7 P 𝓕n X) :
    def_13_6_isFiltration (𝓕 := 𝓕) 𝓕n :=
  h.1

theorem def_13_7_integrable {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓕n : ℕ → MeasurableSpace Ω} {X : ℕ → Ω → ℝ}
    (h : def_13_7 P 𝓕n X) (n : ℕ) :
    Integrable (X n) P :=
  h.2.1 n

theorem def_13_7_adapted {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓕n : ℕ → MeasurableSpace Ω} {X : ℕ → Ω → ℝ}
    (h : def_13_7 P 𝓕n X) :
    def_13_6_adapted 𝓕n X :=
  h.2.2.1

theorem def_13_7_condExp_succ {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓕n : ℕ → MeasurableSpace Ω} {X : ℕ → Ω → ℝ}
    (h : def_13_7 P 𝓕n X) (n : ℕ) :
    P[X (n + 1) | 𝓕n n] =ᵐ[P] X n :=
  h.2.2.2 n

/-- The finite observation history `(Y_0, ..., Y_n)` used in the textbook
paragraph following Definition 13.7. -/
def def_13_7_history {Ω : Type*} (Y : ℕ → Ω → ℝ) (n : ℕ) :
    Ω → Fin (n + 1) → ℝ :=
  fun ω k => Y k.1 ω

/-- The sigma-field generated by the finite history `(Y_0, ..., Y_n)`. -/
@[reducible]
def def_13_7_historySigma {Ω : Type*} (Y : ℕ → Ω → ℝ) (n : ℕ) :
    MeasurableSpace Ω :=
  (inferInstance : MeasurableSpace (Fin (n + 1) → ℝ)).comap
    (def_13_7_history Y n)

/-- Theorem 12.6 supplies the textbook claim that an adapted `X_n` is a
measurable function of the finite history `(Y_0, ..., Y_n)`. -/
theorem def_13_7_history_factorization {Ω : Type*}
    (Y : ℕ → Ω → ℝ) (X : ℕ → Ω → ℝ) (n : ℕ)
    (hX : Measurable[def_13_7_historySigma Y n] (X n)) :
    ∃ g : (Fin (n + 1) → ℝ) → ℝ,
      Measurable g ∧ X n = g ∘ def_13_7_history Y n :=
  thm_12_6_factorization (def_13_7_history Y n) (X n) hX

/-- The same final condition written with the finite observation history:
`E[X_{n+1} | Y_0, ..., Y_n] = X_n`. -/
def def_13_7_historyCondition {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (Y : ℕ → Ω → ℝ) (X : ℕ → Ω → ℝ) : Prop :=
  ∀ n : ℕ, P[X (n + 1) | def_13_7_historySigma Y n] =ᵐ[P] X n
