import Mathlib
import ToyApollo.Output.def_13_3
import ToyApollo.Output.def_13_4

/-
TASK ID: def_13_5
TYPE: Definition
SOURCE PLAN: chapter13-sub-sigma-algebra
TASK CONTENT:
\begin{defbox}{13.5}
\end{defbox}

Let .(\Omega, \mathcal{F},P) be a probability space. The conditional probability of an event A

in. \mathcal{F}given a random variable X is defined as

P(A\vertX) \coloneqqE[1A\vert\sigma(X)].

When the conditional expectation E[X\vertY] as regarded as a function of Y ,w e

write it as E[X\vertY = y]This is a function from R to R, with y as the argument.

However, the more fundamental definition of conditional expectation E[X\vertY] is a

function from. \Omega to. R, which is measurable with respect to \sigma-field\sigma(Y) .
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open ProbabilityTheory

noncomputable section

/-- The real-valued indicator random variable `1_A` used in Definition 13.5. -/
def def_13_5_eventIndicator {Ω : Type*} (A : Set Ω) : Ω → ℝ :=
  A.indicator (fun _ => (1 : ℝ))

/-- Definition 13.5: the conditional probability `P(A | X)` is the conditional
expectation of the event indicator `1_A` given the sigma-field generated by
the observation `X`. -/
def def_13_5 {Ω S : Type*} [𝓕 : MeasurableSpace Ω] [MeasurableSpace S]
    (P : Measure Ω) (A : Set Ω) (_hA : IsMeasurableIn 𝓕 A)
    (X : Ω → S) (hσX : IsSubSigmaField (def_13_4_sigma X) 𝓕)
    (CP : Ω → ℝ) : Prop :=
  @def_13_4 Ω S 𝓕 _ P X hσX (def_13_5_eventIndicator A) CP

/-- The notation `E[Z | Y = y]` is represented by a function on the observation
space whose composition with `Y` gives the conditional-expectation version on
`Ω`. -/
def def_13_5_versionAsFunctionOfObservation {Ω S : Type*}
    (Y : Ω → S) (g : S → ℝ) (CE : Ω → ℝ) : Prop :=
  CE = g ∘ Y

/-- If the conditional probability is represented by a function of the observed
value, then its fundamental random-variable version is obtained by composing
with the observation. -/
theorem def_13_5_apply_versionAsFunctionOfObservation {Ω S : Type*}
    (Y : Ω → S) (g : S → ℝ) :
    def_13_5_versionAsFunctionOfObservation Y g (g ∘ Y) := by
  rfl
