import Mathlib
import ToyApollo.Output.def_13_7

/-
TASK ID: def_13_8
TYPE: Definition
SOURCE PLAN: chapter13-martingale-stopping-time
TASK CONTENT:
\begin{defbox}{13.8}
\end{defbox}

Given a filtration.(\mathcal{F}n)\infty

n=0 and a random variable

T : \Omega \to{ 0, 1, 2,..., }\cup{ \infty }

defined on .(\Omega, \mathcal{F},P) , we say that T is a stopping time relative to the filtration

(\mathcal{F}n)\infty

n=0 if the event.{T \leq n} is\mathcal{F}n-measurable for all n.

If.(Xn)\infty

n=0 is a sequence of random variables and T is a stopping time relative

to.(\sigma(X0,...,X n))n\geq0, we define a random variable XT by

XT () \coloneqqXT( )().

The random variable XT represents the value of the sequence .(Xn)n\geq0 at the

stopping time T , which is the time at which the martingale is terminated. Formally,

for each \in \Omega , we define XT () \coloneqqXT( )(), where T( )is the time at which

the stopping rule is applied to the realization . .
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory

noncomputable section

/-- Definition 13.8: `T` is a stopping time relative to a filtration when the
event `{T ≤ n}` is measurable with respect to the information available at time
`n`, for every finite `n`.  The codomain `WithTop ℕ` represents
`{0, 1, 2, ...} ∪ {∞}`. -/
def def_13_8_isStoppingTime {Ω : Type*}
    (𝓕n : ℕ → MeasurableSpace Ω) (T : Ω → WithTop ℕ) : Prop :=
  ∀ n : ℕ, @MeasurableSet Ω (𝓕n n) {ω | T ω ≤ (n : WithTop ℕ)}

/-- Exported Definition 13.8: stopping time relative to a filtration. -/
def def_13_8 {Ω : Type*}
    (𝓕n : ℕ → MeasurableSpace Ω) (T : Ω → WithTop ℕ) : Prop :=
  def_13_8_isStoppingTime 𝓕n T

theorem def_13_8_event_le_measurable {Ω : Type*}
    {𝓕n : ℕ → MeasurableSpace Ω} {T : Ω → WithTop ℕ}
    (hT : def_13_8 𝓕n T) (n : ℕ) :
    @MeasurableSet Ω (𝓕n n) {ω | T ω ≤ (n : WithTop ℕ)} :=
  hT n

/-- The finite observation history `(X_0, ..., X_n)` used in the natural
filtration of the process. -/
def def_13_8_history {Ω : Type*} (X : ℕ → Ω → ℝ) (n : ℕ) :
    Ω → Fin (n + 1) → ℝ :=
  fun ω k => X k.1 ω

/-- The sigma-field generated by the finite history `(X_0, ..., X_n)`. -/
@[reducible]
def def_13_8_historySigma {Ω : Type*} (X : ℕ → Ω → ℝ) (n : ℕ) :
    MeasurableSpace Ω :=
  (inferInstance : MeasurableSpace (Fin (n + 1) → ℝ)).comap
    (def_13_8_history X n)

/-- The natural filtration generated by a real-valued process. -/
@[reducible]
def def_13_8_naturalFiltration {Ω : Type*}
    (X : ℕ → Ω → ℝ) : ℕ → MeasurableSpace Ω :=
  fun n => def_13_8_historySigma X n

/-- Stopping time relative to the natural filtration
`σ(X_0, ..., X_n)`. -/
def def_13_8_stoppingTimeForSequence {Ω : Type*}
    (X : ℕ → Ω → ℝ) (T : Ω → WithTop ℕ) : Prop :=
  def_13_8 (def_13_8_naturalFiltration X) T

theorem def_13_8_sequence_event_le_measurable {Ω : Type*}
    {X : ℕ → Ω → ℝ} {T : Ω → WithTop ℕ}
    (hT : def_13_8_stoppingTimeForSequence X T) (n : ℕ) :
    @MeasurableSet Ω (def_13_8_historySigma X n)
      {ω | T ω ≤ (n : WithTop ℕ)} :=
  hT n

/-- The stopped value `X_T`.  Since Definition 13.8 allows `T = ∞`, the
formal object records the finite stopped value as `some (X_n ω)` and records
the infinite case as `none` rather than inventing an arbitrary value. -/
def def_13_8_stoppedValue {Ω S : Type*}
    (X : ℕ → Ω → S) (T : Ω → WithTop ℕ) : Ω → Option S :=
  fun ω =>
    match T ω with
    | none => none
    | some n => some (X n ω)

theorem def_13_8_stoppedValue_finite {Ω S : Type*}
    (X : ℕ → Ω → S) (T : Ω → WithTop ℕ) (ω : Ω) (n : ℕ)
    (hT : T ω = (n : WithTop ℕ)) :
    def_13_8_stoppedValue X T ω = some (X n ω) := by
  simp [def_13_8_stoppedValue, hT]

theorem def_13_8_stoppedValue_top {Ω S : Type*}
    (X : ℕ → Ω → S) (T : Ω → WithTop ℕ) (ω : Ω)
    (hT : T ω = ⊤) :
    def_13_8_stoppedValue X T ω = none := by
  simp [def_13_8_stoppedValue, hT]
