import Mathlib
import ToyApollo.Output.def_13_8

/-
TASK ID: ex_13_6_1
TYPE: Example_Proof
SOURCE PLAN: chapter13-martingale-stopping-time
TASK CONTENT:
\textbf{Example 13.6.1 (Natural Filtration)} \\

Suppose Y1,Y 2,.is a sequence of random variables defined on probability space .(\Omega, \mathcal{F},P) .

Let \mathcal{F}0 \coloneqq {\emptyset,\Omega } and \mathcal{F}n \coloneqq \sigma(Y1,Y 2,...,Y n),f o r n = 1, 2, 3,... The n .(\mathcal{F}n)n\geq0 is a

filtration. If fn(y1,...,y n) is any \mathcal{B}(Rn)-measurable function defined on Rn, then the sequence

(fn(Y1,...,Y n))\infty

i=1 is adapted to .(\mathcal{F}n)n\geq0. This means that fn(Y1,Y 2,...,Y n) depends only on

the information available up to and including time n. This filtration is called the natural filtration

for the sequence .(Yi)i\geq1.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory

noncomputable section

/-- The one-indexed finite history `(Y_1, ..., Y_n)` from Example 13.6.1. -/
def ex_13_6_1_history {Ω : Type*} (Y : ℕ → Ω → ℝ) (n : ℕ) :
    Ω → Fin n → ℝ :=
  fun ω k => Y (k.1 + 1) ω

/-- The natural filtration from Example 13.6.1: `F_0` is trivial and, for
positive `n`, `F_n` is generated by `(Y_1, ..., Y_n)`. -/
@[reducible]
def ex_13_6_1_naturalFiltration {Ω : Type*}
    (Y : ℕ → Ω → ℝ) : ℕ → MeasurableSpace Ω
  | 0 => ⊥
  | n + 1 =>
      (inferInstance : MeasurableSpace (Fin (n + 1) → ℝ)).comap
        (ex_13_6_1_history Y (n + 1))

theorem ex_13_6_1_naturalFiltration_zero {Ω : Type*}
    (Y : ℕ → Ω → ℝ) :
    ex_13_6_1_naturalFiltration Y 0 = ⊥ :=
  rfl

theorem ex_13_6_1_naturalFiltration_succ {Ω : Type*}
    (Y : ℕ → Ω → ℝ) (n : ℕ) :
    ex_13_6_1_naturalFiltration Y (n + 1) =
      (inferInstance : MeasurableSpace (Fin (n + 1) → ℝ)).comap
        (ex_13_6_1_history Y (n + 1)) :=
  rfl

/-- Projection from a longer one-indexed history to its first `n` coordinates. -/
def ex_13_6_1_historyProjection {n m : ℕ} (h : n ≤ m) :
    (Fin m → ℝ) → (Fin n → ℝ) :=
  fun v k => v (Fin.castLE h k)

theorem ex_13_6_1_historyProjection_measurable {n m : ℕ} (h : n ≤ m) :
    Measurable (ex_13_6_1_historyProjection h) := by
  exact measurable_pi_lambda _ fun k => measurable_pi_apply (Fin.castLE h k)

theorem ex_13_6_1_historyProjection_comp {Ω : Type*}
    (Y : ℕ → Ω → ℝ) {n m : ℕ} (h : n ≤ m) :
    ex_13_6_1_history Y n =
      ex_13_6_1_historyProjection h ∘ ex_13_6_1_history Y m := by
  funext ω k
  simp [ex_13_6_1_history, ex_13_6_1_historyProjection]

theorem ex_13_6_1_history_measurable_self {Ω : Type*}
    (Y : ℕ → Ω → ℝ) (n : ℕ) :
    @Measurable Ω (Fin n → ℝ) (ex_13_6_1_naturalFiltration Y n)
      _ (ex_13_6_1_history Y n) := by
  cases n with
  | zero =>
      have hconst :
          ex_13_6_1_history Y 0 = fun _ : Ω => (default : Fin 0 → ℝ) := by
        funext ω k
        exact Fin.elim0 k
      rw [hconst]
      exact measurable_const
  | succ n =>
      exact Measurable.of_comap_le le_rfl

theorem ex_13_6_1_history_measurable_of_le {Ω : Type*}
    (Y : ℕ → Ω → ℝ) {n m : ℕ} (h : n ≤ m) :
    @Measurable Ω (Fin n → ℝ) (ex_13_6_1_naturalFiltration Y m)
      _ (ex_13_6_1_history Y n) := by
  have hself := ex_13_6_1_history_measurable_self Y m
  have hproj := ex_13_6_1_historyProjection_measurable h
  have hcomp : @Measurable Ω (Fin n → ℝ) (ex_13_6_1_naturalFiltration Y m)
      _ (ex_13_6_1_historyProjection h ∘ ex_13_6_1_history Y m) :=
    hproj.comp hself
  simpa [ex_13_6_1_historyProjection_comp Y h] using hcomp

/-- The natural sigma-fields are increasing: earlier histories are projections
of later histories. -/
theorem ex_13_6_1_naturalFiltration_mono {Ω : Type*}
    (Y : ℕ → Ω → ℝ) {n m : ℕ} (h : n ≤ m) :
    ex_13_6_1_naturalFiltration Y n ≤ ex_13_6_1_naturalFiltration Y m := by
  cases n with
  | zero =>
      exact bot_le
  | succ n =>
      exact (ex_13_6_1_history_measurable_of_le Y h).comap_le

/-- If the observations are random variables on the ambient sigma-field, then
each generated natural sigma-field is a sub-sigma-field of that ambient one. -/
theorem ex_13_6_1_naturalFiltration_sub_ambient {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] (Y : ℕ → Ω → ℝ)
    (hY : ∀ n : ℕ, @Measurable Ω ℝ 𝓕 _ (Y n)) (n : ℕ) :
    ex_13_6_1_naturalFiltration Y n ≤ 𝓕 := by
  cases n with
  | zero =>
      exact bot_le
  | succ n =>
      have hhist : @Measurable Ω (Fin (n + 1) → ℝ) 𝓕 _
          (ex_13_6_1_history Y (n + 1)) := by
        exact measurable_pi_lambda _ fun k => hY (k.1 + 1)
      exact hhist.comap_le

/-- The generated natural sigma-field family is a filtration whenever the
observations are random variables on the ambient measurable space. -/
theorem ex_13_6_1_naturalFiltration_isFiltration {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] (Y : ℕ → Ω → ℝ)
    (hY : ∀ n : ℕ, @Measurable Ω ℝ 𝓕 _ (Y n)) :
    def_13_6_isFiltration (𝓕 := 𝓕) (ex_13_6_1_naturalFiltration Y) := by
  refine ⟨?_, ?_⟩
  · intro n
    exact ex_13_6_1_naturalFiltration_sub_ambient Y hY n
  · intro n m hnm
    exact ex_13_6_1_naturalFiltration_mono Y hnm

/-- A history-dependent transform `f_n(Y_0,...,Y_n)`. -/
def ex_13_6_1_historyTransform {Ω S : Type*} [Inhabited S]
    (Y : ℕ → Ω → ℝ) (f : (n : ℕ) → (Fin n → ℝ) → S) :
    ℕ → Ω → S
  | 0 => fun _ => default
  | n + 1 => fun ω => f (n + 1) (ex_13_6_1_history Y (n + 1) ω)

/-- The sequence `f_n(Y_0,...,Y_n)` is adapted to the natural filtration when
each `f_n` is measurable on the finite history space. -/
theorem ex_13_6_1_historyTransform_adapted {Ω S : Type*}
    [MeasurableSpace S] [Inhabited S] (Y : ℕ → Ω → ℝ)
    (f : (n : ℕ) → (Fin n → ℝ) → S)
    (hf : ∀ n : ℕ, Measurable (f n)) :
    def_13_6_adapted (ex_13_6_1_naturalFiltration Y)
      (ex_13_6_1_historyTransform Y f) := by
  intro n
  cases n with
  | zero =>
      simp [ex_13_6_1_historyTransform]
  | succ n =>
      exact (hf (n + 1)).comp (Measurable.of_comap_le le_rfl)

/-- Example 13.6.1 packaged as a reusable statement: measurable functions of
the finite history are adapted to the natural filtration generated by that
history. -/
def ex_13_6_1 {Ω S : Type*} [MeasurableSpace S] [Inhabited S]
    (Y : ℕ → Ω → ℝ)
    (f : (n : ℕ) → (Fin n → ℝ) → S) : Prop :=
  (∀ n : ℕ, Measurable (f n)) →
    def_13_6_adapted (ex_13_6_1_naturalFiltration Y)
      (ex_13_6_1_historyTransform Y f)

theorem ex_13_6_1_holds {Ω S : Type*} [MeasurableSpace S] [Inhabited S]
    (Y : ℕ → Ω → ℝ)
    (f : (n : ℕ) → (Fin n → ℝ) → S) :
    ex_13_6_1 Y f :=
  ex_13_6_1_historyTransform_adapted Y f

/-- Source-facing package for Example 13.6.1: the generated natural
sigma-fields form a filtration, and measurable functions of the finite history
are adapted to it. -/
def ex_13_6_1_source_package {Ω S : Type*} [𝓕 : MeasurableSpace Ω]
    [MeasurableSpace S] [Inhabited S] (Y : ℕ → Ω → ℝ)
    (f : (n : ℕ) → (Fin n → ℝ) → S) : Prop :=
  (∀ n : ℕ, @Measurable Ω ℝ 𝓕 _ (Y n)) →
    (∀ n : ℕ, Measurable (f n)) →
      def_13_6_isFiltration (𝓕 := 𝓕) (ex_13_6_1_naturalFiltration Y) ∧
        def_13_6_adapted (ex_13_6_1_naturalFiltration Y)
          (ex_13_6_1_historyTransform Y f)

theorem ex_13_6_1_source_package_holds {Ω S : Type*} [𝓕 : MeasurableSpace Ω]
    [MeasurableSpace S] [Inhabited S] (Y : ℕ → Ω → ℝ)
    (f : (n : ℕ) → (Fin n → ℝ) → S) :
    ex_13_6_1_source_package Y f := by
  intro hY hf
  exact ⟨ex_13_6_1_naturalFiltration_isFiltration Y hY,
    ex_13_6_1_historyTransform_adapted Y f hf⟩
