import Mathlib
import ToyApollo.Output.def_13_8

/-
TASK ID: ex_13_6_4
TYPE: Example_Proof
SOURCE PLAN: chapter13-martingale-stopping-time
TASK CONTENT:
\textbf{Example 13.6.4 (Example of Stopping Time)} \\

Let.(Xn)\infty

n=0 be a sequence of random variables and let .(\mathcal{F}n)\infty

n=0 be the filtration defined by \mathcal{F}n =

\sigma(X0,X 1,...,X n)Define a random variable T as the first time n that the values of Xn exceed

100. Mathematically, we write

T( )=

{

min{n : Xn() \geq 100} if Xn() \geq 100 for some n

\infty otherwise.

When the sequence.(Xn())n\geq1 never exceeds the threshold 100, we define T( )to be infinity for

this realization. The random variable T is a stopping time relative to filtration .(\mathcal{F}n)\infty

n=0 because

the event.{ : T( )\leq n} can be written as the union of .{ : Xi() \geq 100},f o ri = 0, 1,...,n ,

which are all\mathcal{F}n-measurable.
-/

-- WRITE FINAL LEAN CODE BELOW

noncomputable section

/-- The event that the process has crossed the threshold by time `n`. -/
def ex_13_6_4_hitsBy {Ω : Type*}
    (X : ℕ → Ω → ℝ) (threshold : ℝ) (n : ℕ) : Set Ω :=
  {ω | ∃ i : ℕ, i ≤ n ∧ threshold ≤ X i ω}

/-- First passage time above a threshold, with value `∞` if the threshold is
never reached. -/
def ex_13_6_4_firstPassageTime {Ω : Type*}
    (X : ℕ → Ω → ℝ) (threshold : ℝ) : Ω → WithTop ℕ :=
  fun ω => by
    classical
    if h : ∃ n : ℕ, threshold ≤ X n ω then
      exact (Nat.find h : WithTop ℕ)
    else
      exact ⊤

theorem ex_13_6_4_firstPassageTime_le_iff {Ω : Type*}
    (X : ℕ → Ω → ℝ) (threshold : ℝ) (n : ℕ) (ω : Ω) :
    ex_13_6_4_firstPassageTime X threshold ω ≤ (n : WithTop ℕ) ↔
      ω ∈ ex_13_6_4_hitsBy X threshold n := by
  classical
  unfold ex_13_6_4_firstPassageTime ex_13_6_4_hitsBy
  by_cases h : ∃ m : ℕ, threshold ≤ X m ω
  · simp [h, Nat.find_le_iff]
  · simp [h]
    exact fun i _hi => lt_of_not_ge (fun hp => h ⟨i, hp⟩)

theorem ex_13_6_4_firstPassage_event {Ω : Type*}
    (X : ℕ → Ω → ℝ) (threshold : ℝ) (n : ℕ) :
    {ω | ex_13_6_4_firstPassageTime X threshold ω ≤ (n : WithTop ℕ)} =
      ex_13_6_4_hitsBy X threshold n := by
  ext ω
  exact ex_13_6_4_firstPassageTime_le_iff X threshold n ω

/-- The threshold-hit event by time `n` is measurable in the natural
filtration generated by `X_0, ..., X_n`. -/
theorem ex_13_6_4_hitsBy_measurable_natural {Ω : Type*}
    (X : ℕ → Ω → ℝ) (threshold : ℝ) (n : ℕ) :
    @MeasurableSet Ω (def_13_8_naturalFiltration X n)
      (ex_13_6_4_hitsBy X threshold n) := by
  have hhist :
      @Measurable Ω (Fin (n + 1) → ℝ) (def_13_8_naturalFiltration X n)
        _ (def_13_8_history X n) :=
    Measurable.of_comap_le le_rfl
  have hcoord :
      ∀ i : Fin (n + 1),
        @MeasurableSet Ω (def_13_8_naturalFiltration X n)
          {ω : Ω | threshold ≤ X i.1 ω} := by
    intro i
    have hi :
        @Measurable Ω ℝ (def_13_8_naturalFiltration X n) _
          (fun ω : Ω => X i.1 ω) := by
      simpa [def_13_8_history] using (measurable_pi_apply i).comp hhist
    exact measurableSet_Ici.preimage hi
  have hset :
      ex_13_6_4_hitsBy X threshold n =
        ⋃ i : Fin (n + 1), {ω : Ω | threshold ≤ X i.1 ω} := by
    ext ω
    constructor
    · intro hω
      rcases hω with ⟨i, hin, hi⟩
      exact Set.mem_iUnion.2 ⟨⟨i, Nat.lt_succ_of_le hin⟩, hi⟩
    · intro hω
      rcases Set.mem_iUnion.1 hω with ⟨i, hi⟩
      exact ⟨i.1, Nat.le_of_lt_succ i.2, hi⟩
  rw [hset]
  exact MeasurableSet.iUnion hcoord

/-- Example 13.6.4: once the finite-threshold-hit events are measurable in the
nth sigma-field, the first passage time is a stopping time.  For the threshold
100 from the text, instantiate `threshold` with `100`. -/
theorem ex_13_6_4_isStoppingTime {Ω : Type*}
    (𝓕n : ℕ → MeasurableSpace Ω) (X : ℕ → Ω → ℝ) (threshold : ℝ)
    (h_hits :
      ∀ n : ℕ, @MeasurableSet Ω (𝓕n n) (ex_13_6_4_hitsBy X threshold n)) :
    def_13_8 𝓕n (ex_13_6_4_firstPassageTime X threshold) := by
  intro n
  rw [ex_13_6_4_firstPassage_event X threshold n]
  exact h_hits n

/-- Source-facing stopping-time theorem for the natural filtration
`𝓕_n = σ(X_0, ..., X_n)`. -/
theorem ex_13_6_4_isStoppingTime_natural {Ω : Type*}
    (X : ℕ → Ω → ℝ) (threshold : ℝ) :
    def_13_8 (def_13_8_naturalFiltration X)
      (ex_13_6_4_firstPassageTime X threshold) := by
  intro n
  rw [ex_13_6_4_firstPassage_event X threshold n]
  exact ex_13_6_4_hitsBy_measurable_natural X threshold n

/-- The concrete threshold `100` used in the example. -/
def ex_13_6_4 {Ω : Type*}
    (𝓕n : ℕ → MeasurableSpace Ω) (X : ℕ → Ω → ℝ) : Prop :=
  def_13_8 𝓕n (ex_13_6_4_firstPassageTime X 100)

theorem ex_13_6_4_holds {Ω : Type*} (X : ℕ → Ω → ℝ) :
    ex_13_6_4 (def_13_8_naturalFiltration X) X := by
  exact ex_13_6_4_isStoppingTime_natural X 100
