import Mathlib
import ToyApollo.Output.def_13_7
import ToyApollo.Output.ex_13_6_1

/-
TASK ID: ex_13_6_3
TYPE: Example_Proof
SOURCE PLAN: chapter13-martingale-stopping-time
TASK CONTENT:
\textbf{Example 13.6.3 (Doob's Martingale)} \\

SupposeY1,Y 2,.is a sequence of random variables, and let X be an integrable random variable

defined on the same probability space. Define the natural filtration .(\mathcal{F}n)n\geq0 by \mathcal{F}0 ={ \emptyset,\Omega } and

\mathcal{F}n = \sigma(Y1,...,Y n),f o rn \geq 1LetZi \coloneqqE[X\vert\mathcal{F}i],f o ri = 0, 1, 2,... .

We note that Zn = E[X\vert\mathcal{F}n] is \mathcal{F}n-measurable by the definition of conditional expectation.

By the triangle inequality of conditioned expectation, we have

E[\vertZn\vert] = E[\vertE[X\vert\mathcal{F}n]\vert] \leq E[E[\vertX\vert\vert\mathcal{F}n]] = E[\vertX\vert] < \infty .

Finally, forn \geq 1, we can apply the tower property to obtain

E[Zn\vert\mathcal{F}n- 1]= E[E[X\vert\mathcal{F}n]\vert\mathcal{F}n- 1]= E[X\vert\mathcal{F}n- 1]= Zn- 1.

It proves that the sequence .(Zn)\infty

n=0 is a martingale sequence relative to .(\mathcal{F}n)n\geq0.

The stopping time T is a device that terminates a martingale. It is a random

variable such that the event .{T( )= n} can be determined by the information up to

time n. For example, a constant T is always a stopping time, but the first time that

a gambling loses ten times in a row is not, since it depends on future outcomes that

are not known at time n.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open scoped ProbabilityTheory

noncomputable section

/-- The natural filtration used in Doob's martingale example. -/
abbrev ex_13_6_3_naturalFiltration {Ω : Type*}
    (Y : ℕ → Ω → ℝ) : ℕ → MeasurableSpace Ω :=
  ex_13_6_1_naturalFiltration Y

/-- Doob's martingale process `Z_n = E[X | F_n]`. -/
def ex_13_6_3_process {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (𝓕n : ℕ → MeasurableSpace Ω)
    (X : Ω → ℝ) : ℕ → Ω → ℝ :=
  fun n => P[X | 𝓕n n]

/-- Conditional expectations are measurable with respect to the sigma-field
they condition on; this is the adaptedness step in the textbook proof. -/
theorem ex_13_6_3_process_adapted {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (𝓕n : ℕ → MeasurableSpace Ω) (X : Ω → ℝ) :
    def_13_6_adapted 𝓕n (ex_13_6_3_process P 𝓕n X) := by
  intro n
  exact stronglyMeasurable_condExp.measurable

/-- Integrability of `Z_n = E[X | F_n]`, the Lean landing place for the
textbook bound `E|E[X|F_n]| <= E|X|`. -/
theorem ex_13_6_3_process_integrable {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (𝓕n : ℕ → MeasurableSpace Ω) (X : Ω → ℝ) :
    ∀ n : ℕ, Integrable (ex_13_6_3_process P 𝓕n X n) P := by
  intro n
  exact integrable_condExp

/-- The tower-property step in Doob's martingale example. -/
theorem ex_13_6_3_oneStepCondition {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓕n : ℕ → MeasurableSpace Ω} {X : Ω → ℝ}
    (hfiltration : def_13_6_isFiltration (𝓕 := 𝓕) 𝓕n)
    (hSigmaFinite : ∀ n : ℕ, SigmaFinite (P.trim (hfiltration.1 n))) :
    def_13_7_oneStepCondition P 𝓕n
      (ex_13_6_3_process P 𝓕n X) := by
  intro n
  have hle : 𝓕n n ≤ 𝓕n (n + 1) :=
    hfiltration.2 n (n + 1) (Nat.le_succ n)
  haveI : SigmaFinite (P.trim (hfiltration.1 (n + 1))) :=
    hSigmaFinite (n + 1)
  exact condExp_condExp_of_le hle (hfiltration.1 (n + 1))

/-- Generic Doob martingale statement for any filtration. -/
theorem ex_13_6_3_doob_martingale {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓕n : ℕ → MeasurableSpace Ω} {X : Ω → ℝ}
    (hfiltration : def_13_6_isFiltration (𝓕 := 𝓕) 𝓕n)
    (hSigmaFinite : ∀ n : ℕ, SigmaFinite (P.trim (hfiltration.1 n)))
    (_hXint : Integrable X P) :
    def_13_7 P 𝓕n (ex_13_6_3_process P 𝓕n X) := by
  exact ⟨hfiltration, ex_13_6_3_process_integrable P 𝓕n X,
    ex_13_6_3_process_adapted P 𝓕n X,
    ex_13_6_3_oneStepCondition hfiltration hSigmaFinite⟩

/-- Example 13.6.3: for the natural filtration generated by observations
`Y_1, Y_2, ...`, the process `Z_n = E[X | F_n]` is a martingale. -/
theorem ex_13_6_3 {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {Y : ℕ → Ω → ℝ} {X : Ω → ℝ}
    (hY : ∀ n : ℕ, @Measurable Ω ℝ 𝓕 _ (Y n))
    (hXint : Integrable X P) :
    def_13_7 P (ex_13_6_3_naturalFiltration Y)
      (ex_13_6_3_process P (ex_13_6_3_naturalFiltration Y) X) := by
  have hfiltration :
      def_13_6_isFiltration (𝓕 := 𝓕) (ex_13_6_3_naturalFiltration Y) :=
    ex_13_6_1_naturalFiltration_isFiltration Y hY
  have hSigmaFinite :
      ∀ n : ℕ, SigmaFinite (P.trim (hfiltration.1 n)) := by
    intro n
    infer_instance
  exact ex_13_6_3_doob_martingale hfiltration hSigmaFinite hXint
