import Mathlib

/-
TASK ID: ex_12_4_3
TYPE: Example_Proof
SOURCE PLAN: chapter12-mmse-estimation
TASK CONTENT:
\textbf{Example 12.4.3 (An Example of Nonlinear MMSE Estimation)} \\

Consider a sample space .{a,b,c,d } and define a uniform distribution on the four sample points.

Define two random variables using the table

a b c d

X(. ) 1 1 2 2

Y(. ) 1 2 3 4

We want to find the nonlinear MMSE estimator of Y given X. Since the probability space is finite,

all functions defined on this probability space are measurable and have finite second moments. The

problem is equivalent to finding a function g(x) that minimizesY - g(X)2.

The\sigma-algebra generated by X contains four sets \emptyset,\Omega ,.{a,b },a n d.{c,d }The MMSE estimator of

Y given X is a function of X and is in the form

Y() =

{

\alphaif = a or = b

\betaif = c or = d.

The optimal values of \alpha and \beta can be determined using calculus. The objective function that we

are going to minimize is a multi-variable quadratic function,

4(1- \alpha) 2 + 1

4(2- \alpha) 2 + 1

4(3- \beta) 2 + 1

4(4- \beta) 2.

The solution can be derived by partially differentiating the objective function with respect to \alpha and

\beta and solving a system of linear equations.

In the followings, we can obtain the answer using the Orthogonal Principle. The MMSE estimator

Y satisfies the following property:

E[YZ ]= E[ YZ ] for all \sigma(X)-measurable functions Z.

We first considerZ = 1{a,b}Applying (12.5),we get

E[Y 1{a,b}]= 1

4 + 2

4 +0 + 0 ,

E[ Y1{a,b}]= \alphaE[1{a,b}]= \alpha

( 1

4 + 1

)

The second line follows from the fact that Y is constant on the event .{a,b }Equating the above

two values yields\alpha = 1.5.

We next consider the function Z = 1{c,d}We have

E[Y 1{c,d}]= 0 + 0 + 3

4 + 4

4,

E[ Y1{c,d}]= \betaE[1{c,d}]= \beta

( 1

4 + 1

)

This gives\beta= 3 .5.

The optimal function g(x) that minimizes mean-squared error Y- g(X) 2 is

g(x)=

{

1.5i f x= 1 ,

3.5i f x= 2 .

We implement this example using Python.

from random import choice

Omega = ['a','b','c','d'] # sample space

Y = {'a':1, 'b':2, 'c':3, 'd':4} # represent Y by a dictionary

omega= choice(Omega) # pick a sample uniformly

X=1i f (Y[omega] <= 2) else 2 # X equals 1 if Y=1, 2 if Y=2

Y_hat = 1.5 if X==1 else 3.5 # estimate random variable Y by X

print(f"Y={Y[omega]}, X={X}, Y_hat={Y_hat}")

In the program, we denote the estimate of Y by Y_hat , which is a function of X A sample output

of this program is:

Y=4, X=2, Y_hat=3.5

The conditional expectation operator in L2(P) generally provides the nonlin-

ear minimum mean-squared error estimation. Specifically, the function g(x) that

minimizes the mean-squared error E[(Y- g(X)) 2] is given by the conditional

expectationg(x)= E [Y\vertX= x ].
-/

-- WRITE FINAL LEAN CODE BELOW

noncomputable section

/-- The four-point sample space `{a,b,c,d}` used in Example 12.4.3. -/
inductive ex_12_4_3_Ω where
  | a
  | b
  | c
  | d
  deriving DecidableEq, Fintype

open ex_12_4_3_Ω

/-- The random variable `X`: it is constant on `{a,b}` and on `{c,d}`. -/
def ex_12_4_3_X : ex_12_4_3_Ω → ℝ
  | a => 1
  | b => 1
  | c => 2
  | d => 2

/-- The random variable `Y` from the source table. -/
def ex_12_4_3_Y : ex_12_4_3_Ω → ℝ
  | a => 1
  | b => 2
  | c => 3
  | d => 4

/-- Uniform expectation on the four-point space. -/
def ex_12_4_3_uniformExpectation (Z : ex_12_4_3_Ω → ℝ) : ℝ :=
  (Z a + Z b + Z c + Z d) / 4

/-- The atom `{a,b}` of the sigma-algebra generated by `X`. -/
def ex_12_4_3_atomAB (ω : ex_12_4_3_Ω) : Prop :=
  ω = a ∨ ω = b

/-- The atom `{c,d}` of the sigma-algebra generated by `X`. -/
def ex_12_4_3_atomCD (ω : ex_12_4_3_Ω) : Prop :=
  ω = c ∨ ω = d

/-- Indicator of the atom `{a,b}`. -/
def ex_12_4_3_indicatorAB : ex_12_4_3_Ω → ℝ
  | a => 1
  | b => 1
  | c => 0
  | d => 0

/-- Indicator of the atom `{c,d}`. -/
def ex_12_4_3_indicatorCD : ex_12_4_3_Ω → ℝ
  | a => 0
  | b => 0
  | c => 1
  | d => 1

/-- A `σ(X)`-measurable estimator is constant on the two atoms of `X`. -/
def ex_12_4_3_estimator (α β : ℝ) : ex_12_4_3_Ω → ℝ
  | a => α
  | b => α
  | c => β
  | d => β

/-- The textbook answer as a function of the observed value `X`. -/
def ex_12_4_3_g (x : ℝ) : ℝ :=
  if x = 1 then (3 / 2 : ℝ) else if x = 2 then (7 / 2 : ℝ) else 0

/-- Mean-squared error of the two-atom estimator. -/
def ex_12_4_3_mse (α β : ℝ) : ℝ :=
  ex_12_4_3_uniformExpectation
    (fun ω => (ex_12_4_3_Y ω - ex_12_4_3_estimator α β ω) ^ 2)

/-- The explicit quadratic objective displayed in the source. -/
def ex_12_4_3_objective (α β : ℝ) : ℝ :=
  ((1 - α) ^ 2 + (2 - α) ^ 2 + (3 - β) ^ 2 + (4 - β) ^ 2) / 4

theorem ex_12_4_3_X_eq_one_iff (ω : ex_12_4_3_Ω) :
    ex_12_4_3_X ω = 1 ↔ ex_12_4_3_atomAB ω := by
  cases ω <;> simp [ex_12_4_3_X, ex_12_4_3_atomAB]

theorem ex_12_4_3_X_eq_two_iff (ω : ex_12_4_3_Ω) :
    ex_12_4_3_X ω = 2 ↔ ex_12_4_3_atomCD ω := by
  cases ω <;> simp [ex_12_4_3_X, ex_12_4_3_atomCD]

theorem ex_12_4_3_mse_eq_objective (α β : ℝ) :
    ex_12_4_3_mse α β = ex_12_4_3_objective α β := by
  unfold ex_12_4_3_mse ex_12_4_3_uniformExpectation ex_12_4_3_objective
    ex_12_4_3_Y ex_12_4_3_estimator
  ring

theorem ex_12_4_3_objective_sub_min (α β : ℝ) :
    ex_12_4_3_objective α β - ex_12_4_3_objective (3 / 2) (7 / 2) =
      (α - 3 / 2) ^ 2 / 2 + (β - 7 / 2) ^ 2 / 2 := by
  unfold ex_12_4_3_objective
  ring

theorem ex_12_4_3_objective_minimal (α β : ℝ) :
    ex_12_4_3_objective (3 / 2) (7 / 2) ≤ ex_12_4_3_objective α β := by
  have h := ex_12_4_3_objective_sub_min α β
  nlinarith [sq_nonneg (α - 3 / 2), sq_nonneg (β - 7 / 2)]

theorem ex_12_4_3_mse_minimal (α β : ℝ) :
    ex_12_4_3_mse (3 / 2) (7 / 2) ≤ ex_12_4_3_mse α β := by
  simpa [ex_12_4_3_mse_eq_objective] using ex_12_4_3_objective_minimal α β

theorem ex_12_4_3_E_Y_indicatorAB :
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorAB ω) = 3 / 4 := by
  norm_num [ex_12_4_3_uniformExpectation, ex_12_4_3_Y, ex_12_4_3_indicatorAB]

theorem ex_12_4_3_E_estimator_indicatorAB (α β : ℝ) :
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_estimator α β ω * ex_12_4_3_indicatorAB ω) = α / 2 := by
  unfold ex_12_4_3_uniformExpectation ex_12_4_3_estimator ex_12_4_3_indicatorAB
  ring

theorem ex_12_4_3_alpha_of_atomAB_equation (α β : ℝ)
    (h :
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorAB ω) =
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_estimator α β ω * ex_12_4_3_indicatorAB ω)) :
    α = 3 / 2 := by
  rw [ex_12_4_3_E_Y_indicatorAB, ex_12_4_3_E_estimator_indicatorAB] at h
  nlinarith

theorem ex_12_4_3_E_Y_indicatorCD :
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorCD ω) = 7 / 4 := by
  norm_num [ex_12_4_3_uniformExpectation, ex_12_4_3_Y, ex_12_4_3_indicatorCD]

theorem ex_12_4_3_E_estimator_indicatorCD (α β : ℝ) :
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_estimator α β ω * ex_12_4_3_indicatorCD ω) = β / 2 := by
  unfold ex_12_4_3_uniformExpectation ex_12_4_3_estimator ex_12_4_3_indicatorCD
  ring

theorem ex_12_4_3_beta_of_atomCD_equation (α β : ℝ)
    (h :
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorCD ω) =
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_estimator α β ω * ex_12_4_3_indicatorCD ω)) :
    β = 7 / 2 := by
  rw [ex_12_4_3_E_Y_indicatorCD, ex_12_4_3_E_estimator_indicatorCD] at h
  nlinarith

theorem ex_12_4_3_orthogonal_principle_values (α β : ℝ)
    (hAB :
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorAB ω) =
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_estimator α β ω * ex_12_4_3_indicatorAB ω))
    (hCD :
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorCD ω) =
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_estimator α β ω * ex_12_4_3_indicatorCD ω)) :
    α = 3 / 2 ∧ β = 7 / 2 :=
  ⟨ex_12_4_3_alpha_of_atomAB_equation α β hAB,
    ex_12_4_3_beta_of_atomCD_equation α β hCD⟩

theorem ex_12_4_3_estimator_eq_g_comp_X :
    ex_12_4_3_estimator (3 / 2) (7 / 2) =
      fun ω => ex_12_4_3_g (ex_12_4_3_X ω) := by
  funext ω
  cases ω <;> norm_num [ex_12_4_3_estimator, ex_12_4_3_g, ex_12_4_3_X]

theorem ex_12_4_3_optimal_atomAB :
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorAB ω) =
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_estimator (3 / 2) (7 / 2) ω *
        ex_12_4_3_indicatorAB ω) := by
  rw [ex_12_4_3_E_Y_indicatorAB, ex_12_4_3_E_estimator_indicatorAB]
  norm_num

theorem ex_12_4_3_optimal_atomCD :
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorCD ω) =
    ex_12_4_3_uniformExpectation
      (fun ω => ex_12_4_3_estimator (3 / 2) (7 / 2) ω *
        ex_12_4_3_indicatorCD ω) := by
  rw [ex_12_4_3_E_Y_indicatorCD, ex_12_4_3_E_estimator_indicatorCD]
  norm_num

/-- Example 12.4.3: on the finite uniform space, the nonlinear MMSE estimator
given `X` is the function of `X` with values `1.5` on `X = 1` and `3.5` on
`X = 2`; equivalently, it minimizes the displayed two-variable quadratic MSE
and satisfies the two atom equations from the Orthogonality Principle. -/
theorem ex_12_4_3 :
    (∀ α β : ℝ, ex_12_4_3_mse (3 / 2) (7 / 2) ≤ ex_12_4_3_mse α β) ∧
      (ex_12_4_3_estimator (3 / 2) (7 / 2) =
        fun ω => ex_12_4_3_g (ex_12_4_3_X ω)) ∧
      (ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorAB ω) =
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_estimator (3 / 2) (7 / 2) ω *
          ex_12_4_3_indicatorAB ω)) ∧
      (ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_Y ω * ex_12_4_3_indicatorCD ω) =
      ex_12_4_3_uniformExpectation
        (fun ω => ex_12_4_3_estimator (3 / 2) (7 / 2) ω *
          ex_12_4_3_indicatorCD ω)) := by
  constructor
  · exact fun α β => ex_12_4_3_mse_minimal α β
  constructor
  · exact ex_12_4_3_estimator_eq_g_comp_X
  constructor
  · exact ex_12_4_3_optimal_atomAB
  · exact ex_12_4_3_optimal_atomCD
