import Mathlib
import ToyApollo.Output.def_13_3

/-
TASK ID: ex_13_2_2
TYPE: Example_Proof
SOURCE PLAN: chapter13-sub-sigma-algebra
TASK CONTENT:
\textbf{Example 13.2.2 (Conditioning on the Largest\sigma-Algebra)} \\

Consider the case \mathcal{G}= \mathcal{F}Let B be any set in \mathcal{G}, ie., B is any set in \mathcal{F}W ew a n tt ofi n d a \mathcal{G}-

measurable function, which is the same as an \mathcal{F}-measurable function E[X\vert\mathcal{F}] such that (13.3)

holds for all B \in\mathcal{F}In fact, X is such a choice for E[X\vert\mathcal{F}]Hence,E[X\vert\mathcal{F}]= X as.

We defineE[X\vertY] in terms of the \sigma-algebra generated by Y .
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open ProbabilityTheory

noncomputable section

/-- The largest conditioning sigma-field is the ambient sigma-field itself. -/
theorem ex_13_2_2_self_subSigma {Ω : Type*} [𝓕 : MeasurableSpace Ω] :
    IsSubSigmaField 𝓕 𝓕 := by
  intro A hA
  exact hA

/-- Example 13.2.2: conditioning on the full sigma-field leaves the random
variable unchanged. -/
theorem ex_13_2_2 {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (P : Measure Ω) {X : Ω → ℝ} (hXint : Integrable X P)
    (hXmeas : Measurable X) :
    @def_13_3 Ω 𝓕 P 𝓕 (@ex_13_2_2_self_subSigma Ω 𝓕) X X := by
  refine ⟨hXint, hXint, hXmeas, ?_⟩
  intro B hB
  rfl
