import Mathlib
import ToyApollo.Output.def_2_7

open Set
open scoped Classical

noncomputable section

/-- The six-point sample space used in Example 2.4.1. -/
inductive SixPoint
  | a | b | c | d | e | f
  deriving DecidableEq, Repr

open SixPoint

instance : Fintype SixPoint where
  elems := {a, b, c, d, e, f}
  complete := by
    intro x
    cases x <;> simp

/-- The two generators from the textbook example. -/
def A1 : Set SixPoint := {a, b, c}
def A2 : Set SixPoint := {c, d, e}

/-- The atoms cut out by `A₁` and `A₂`. -/
def atomAB : Set SixPoint := {a, b}
def atomC : Set SixPoint := {c}
def atomDE : Set SixPoint := {d, e}
def atomF : Set SixPoint := {f}

/-- The four atoms whose unions generate the full finite sigma-algebra. -/
def generatingAtoms : Finset (Set SixPoint) :=
  {atomAB, atomC, atomDE, atomF}

/-- The sixteen members of the sigma-algebra generated by `A₁` and `A₂`. -/
def generatedMembers : Finset (Set SixPoint) :=
  { (∅ : Set SixPoint),
    Set.univ,
    A1,
    A1ᶜ,
    A2,
    A2ᶜ,
    ({a, b, c, d, e} : Set SixPoint),
    ({f} : Set SixPoint),
    ({c} : Set SixPoint),
    ({a, b, d, e, f} : Set SixPoint),
    ({a, b, c, f} : Set SixPoint),
    ({d, e} : Set SixPoint),
    ({a, b} : Set SixPoint),
    ({c, d, e, f} : Set SixPoint),
    ({a, b, d, e} : Set SixPoint),
    ({c, f} : Set SixPoint) }

/-- Exported concrete data for Example 2.4.1. -/
structure FiniteGeneratedSigmaFieldExample where
  sampleSpace : Set SixPoint
  generators : Finset (Set SixPoint)
  atoms : Finset (Set SixPoint)
  generatedMembers : Finset (Set SixPoint)

/-- Exported declaration for Example 2.4.1. -/
def ex_2_4_1 : FiniteGeneratedSigmaFieldExample where
  sampleSpace := Set.univ
  generators := {A1, A2}
  atoms := generatingAtoms
  generatedMembers := generatedMembers

/-- The original generators are explicitly present in the listed sigma-algebra. -/
theorem ex_2_4_1_generators_mem :
    A1 ∈ ex_2_4_1.generatedMembers ∧ A2 ∈ ex_2_4_1.generatedMembers := by
  simp [ex_2_4_1, generatedMembers]

/-- The symmetric difference of `A₁` and `A₂` appears as one of the generated sets. -/
theorem ex_2_4_1_symmDiff_mem :
    ({a, b, d, e} : Set SixPoint) ∈ ex_2_4_1.generatedMembers := by
  simp [ex_2_4_1, generatedMembers]
