import Mathlib
import ToyApollo.Output.def_2_7

open Set
open scoped Classical
open scoped symmDiff

noncomputable section

/-- The six-point sample space used in Example 2.4.1. -/
inductive SixPoint
  | a | b | c | d | e | f
  deriving DecidableEq, Repr

open SixPoint

instance : Fintype SixPoint where
  elems := {a, b, c, d, e, f}
  complete := by
    intro x
    cases x <;> simp

/-- The atom index cut out by membership in `A₁` and `A₂`. -/
def atomIndex : SixPoint → Fin 4
  | a | b => 0
  | c => 1
  | d | e => 2
  | f => 3

/-- The union of the atoms whose indices lie in `I`. -/
def atomUnion (I : Finset (Fin 4)) : Set SixPoint := {x | atomIndex x ∈ I}

/-- The two generators from the textbook example. -/
def A1 : Set SixPoint := atomUnion {0, 1}
def A2 : Set SixPoint := atomUnion {1, 2}

/-- The atoms cut out by `A₁` and `A₂`. -/
def atomAB : Set SixPoint := atomUnion {0}
def atomC : Set SixPoint := atomUnion {1}
def atomDE : Set SixPoint := atomUnion {2}
def atomF : Set SixPoint := atomUnion {3}

/-- The four atoms whose unions generate the full finite sigma-algebra. -/
def generatingAtoms : Finset (Set SixPoint) :=
  {atomAB, atomC, atomDE, atomF}

/-- The sixteen members of the sigma-algebra generated by `A₁` and `A₂`. -/
def generatedMembers : Finset (Set SixPoint) :=
  Finset.univ.image atomUnion

theorem A1_eq_textbook : A1 = ({a, b, c} : Set SixPoint) := by
  ext x
  cases x <;> simp [A1, atomUnion, atomIndex]

theorem A2_eq_textbook : A2 = ({c, d, e} : Set SixPoint) := by
  ext x
  cases x <;> simp [A2, atomUnion, atomIndex]

theorem atomAB_eq_textbook : atomAB = ({a, b} : Set SixPoint) := by
  ext x
  cases x <;> simp [atomAB, atomUnion, atomIndex]

theorem atomC_eq_textbook : atomC = ({c} : Set SixPoint) := by
  ext x
  cases x <;> simp [atomC, atomUnion, atomIndex]

theorem atomDE_eq_textbook : atomDE = ({d, e} : Set SixPoint) := by
  ext x
  cases x <;> simp [atomDE, atomUnion, atomIndex]

theorem atomF_eq_textbook : atomF = ({f} : Set SixPoint) := by
  ext x
  cases x <;> simp [atomF, atomUnion, atomIndex]

theorem atomIndex_surjective : Function.Surjective atomIndex := by
  intro i
  fin_cases i
  · exact ⟨a, rfl⟩
  · exact ⟨c, rfl⟩
  · exact ⟨d, rfl⟩
  · exact ⟨f, rfl⟩

theorem atomUnion_injective : Function.Injective atomUnion := by
  intro I J hIJ
  ext i
  rcases atomIndex_surjective i with ⟨x, hx⟩
  have hxmem := congrArg (fun S : Set SixPoint => x ∈ S) hIJ
  simpa [atomUnion, hx] using hxmem

theorem generatedMembers_card : generatedMembers.card = 16 := by
  rw [generatedMembers, Finset.card_image_of_injective _ atomUnion_injective]
  simp

theorem atomUnion_mem_generatedMembers (I : Finset (Fin 4)) :
    atomUnion I ∈ generatedMembers := by
  exact Finset.mem_image.mpr ⟨I, Finset.mem_univ _, rfl⟩

theorem generatedMembers_compl_closed {S : Set SixPoint}
    (hS : S ∈ generatedMembers) : Sᶜ ∈ generatedMembers := by
  rcases Finset.mem_image.mp hS with ⟨I, _hI, rfl⟩
  refine Finset.mem_image.mpr ⟨Iᶜ, Finset.mem_univ _, ?_⟩
  ext x
  simp [atomUnion]

theorem generatedMembers_union_closed {S T : Set SixPoint}
    (hS : S ∈ generatedMembers) (hT : T ∈ generatedMembers) :
    S ∪ T ∈ generatedMembers := by
  rcases Finset.mem_image.mp hS with ⟨I, _hI, rfl⟩
  rcases Finset.mem_image.mp hT with ⟨J, _hJ, rfl⟩
  refine Finset.mem_image.mpr ⟨I ∪ J, Finset.mem_univ _, ?_⟩
  ext x
  simp [atomUnion]

theorem generatedMembers_inter_closed {S T : Set SixPoint}
    (hS : S ∈ generatedMembers) (hT : T ∈ generatedMembers) :
    S ∩ T ∈ generatedMembers := by
  rcases Finset.mem_image.mp hS with ⟨I, _hI, rfl⟩
  rcases Finset.mem_image.mp hT with ⟨J, _hJ, rfl⟩
  refine Finset.mem_image.mpr ⟨I ∩ J, Finset.mem_univ _, ?_⟩
  ext x
  simp [atomUnion]

theorem generatedMembers_iUnion_closed (F : ℕ → Set SixPoint)
    (hF : ∀ n, F n ∈ generatedMembers) :
    (⋃ n, F n) ∈ generatedMembers := by
  choose I hI using fun n => Finset.mem_image.mp (hF n)
  refine Finset.mem_image.mpr
    ⟨Finset.univ.filter (fun i : Fin 4 => ∃ n, i ∈ I n), Finset.mem_univ _, ?_⟩
  ext x
  constructor
  · intro hx
    have hx' : atomIndex x ∈ Finset.univ.filter (fun i : Fin 4 => ∃ n, i ∈ I n) := by
      simpa [atomUnion] using hx
    rcases (Finset.mem_filter.mp hx').2 with ⟨n, hn⟩
    exact mem_iUnion.mpr ⟨n, by rw [← (hI n).2]; exact hn⟩
  · intro hx
    rcases mem_iUnion.mp hx with ⟨n, hxn⟩
    rw [← (hI n).2] at hxn
    have hx' : atomIndex x ∈ Finset.univ.filter (fun i : Fin 4 => ∃ n, i ∈ I n) :=
      Finset.mem_filter.mpr ⟨Finset.mem_univ _, ⟨n, hxn⟩⟩
    simpa [atomUnion] using hx'

/-- The listed atom-union family, viewed as a measurable space. -/
@[reducible]
def listedMeasurableSpace : MeasurableSpace SixPoint where
  MeasurableSet' S := S ∈ generatedMembers
  measurableSet_empty := by
    simpa [atomUnion] using atomUnion_mem_generatedMembers (∅ : Finset (Fin 4))
  measurableSet_compl := by
    intro S hS
    exact generatedMembers_compl_closed hS
  measurableSet_iUnion := by
    intro F hF
    exact generatedMembers_iUnion_closed F hF

theorem atomAB_eq_A1_diff_A2 : atomAB = A1 \ A2 := by
  ext x
  cases x <;> simp [atomAB, A1, A2, atomUnion, atomIndex]

theorem atomC_eq_A1_inter_A2 : atomC = A1 ∩ A2 := by
  ext x
  cases x <;> simp [atomC, A1, A2, atomUnion, atomIndex]

theorem atomDE_eq_A1_compl_inter_A2 : atomDE = A1ᶜ ∩ A2 := by
  ext x
  cases x <;> simp [atomDE, A1, A2, atomUnion, atomIndex]

theorem atomF_eq_A1_compl_inter_A2_compl : atomF = A1ᶜ ∩ A2ᶜ := by
  ext x
  cases x <;> simp [atomF, A1, A2, atomUnion, atomIndex]

theorem atomUnion_singleton_measurable_generated (i : Fin 4) :
    @MeasurableSet SixPoint (generatedSigmaField ({A1, A2} : Set (Set SixPoint)))
      (atomUnion {i}) := by
  have hA1 : @MeasurableSet SixPoint
      (generatedSigmaField ({A1, A2} : Set (Set SixPoint))) A1 :=
    generatedSigmaField_contains ({A1, A2} : Set (Set SixPoint)) A1 (by simp)
  have hA2 : @MeasurableSet SixPoint
      (generatedSigmaField ({A1, A2} : Set (Set SixPoint))) A2 :=
    generatedSigmaField_contains ({A1, A2} : Set (Set SixPoint)) A2 (by simp)
  fin_cases i
  · change @MeasurableSet SixPoint
      (generatedSigmaField ({A1, A2} : Set (Set SixPoint))) atomAB
    rw [atomAB_eq_A1_diff_A2]
    exact hA1.diff hA2
  · change @MeasurableSet SixPoint
      (generatedSigmaField ({A1, A2} : Set (Set SixPoint))) atomC
    rw [atomC_eq_A1_inter_A2]
    exact hA1.inter hA2
  · change @MeasurableSet SixPoint
      (generatedSigmaField ({A1, A2} : Set (Set SixPoint))) atomDE
    rw [atomDE_eq_A1_compl_inter_A2]
    exact hA1.compl.inter hA2
  · change @MeasurableSet SixPoint
      (generatedSigmaField ({A1, A2} : Set (Set SixPoint))) atomF
    rw [atomF_eq_A1_compl_inter_A2_compl]
    exact hA1.compl.inter hA2.compl

theorem atomUnion_measurable_generated (I : Finset (Fin 4)) :
    @MeasurableSet SixPoint (generatedSigmaField ({A1, A2} : Set (Set SixPoint)))
      (atomUnion I) := by
  classical
  refine Finset.induction_on I ?empty ?insert
  · have h_empty : atomUnion (∅ : Finset (Fin 4)) = (∅ : Set SixPoint) := by
      ext x
      simp [atomUnion]
    rw [h_empty]
    exact @MeasurableSet.empty SixPoint
      (generatedSigmaField ({A1, A2} : Set (Set SixPoint)))
  · intro i I hi hI
    have h_insert : atomUnion (insert i I) = atomUnion {i} ∪ atomUnion I := by
      ext x
      simp [atomUnion]
    rw [h_insert]
    exact (atomUnion_singleton_measurable_generated i).union hI

theorem generatedSigmaField_exact :
    ∀ S : Set SixPoint,
      @MeasurableSet SixPoint (generatedSigmaField ({A1, A2} : Set (Set SixPoint))) S ↔
        S ∈ generatedMembers := by
  intro S
  constructor
  · intro hS
    have hle :
        generatedSigmaField ({A1, A2} : Set (Set SixPoint)) ≤ listedMeasurableSpace := by
      refine MeasurableSpace.generateFrom_le ?_
      intro T hT
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hT
      rcases hT with rfl | rfl
      · exact atomUnion_mem_generatedMembers {0, 1}
      · exact atomUnion_mem_generatedMembers {1, 2}
    exact hle S hS
  · intro hS
    rcases Finset.mem_image.mp hS with ⟨I, _hI, rfl⟩
    exact atomUnion_measurable_generated I

theorem generatedMembers_minimal
    (M : MeasurableSpace SixPoint)
    (hA1 : @MeasurableSet SixPoint M A1)
    (hA2 : @MeasurableSet SixPoint M A2)
    {S : Set SixPoint} (hS : S ∈ generatedMembers) :
    @MeasurableSet SixPoint M S := by
  have hle : generatedSigmaField ({A1, A2} : Set (Set SixPoint)) ≤ M := by
    refine MeasurableSpace.generateFrom_le ?_
    intro T hT
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hT
    rcases hT with rfl | rfl
    · exact hA1
    · exact hA2
  exact hle S ((generatedSigmaField_exact S).2 hS)

/-- Exported concrete data for Example 2.4.1. -/
structure FiniteGeneratedSigmaFieldExample where
  sampleSpace : Set SixPoint
  generators : Finset (Set SixPoint)
  atoms : Finset (Set SixPoint)
  generatedMembers : Finset (Set SixPoint)

/-- Exported declaration for Example 2.4.1. -/
def ex_2_4_1 : FiniteGeneratedSigmaFieldExample where
  sampleSpace := Set.univ
  generators := {A1, A2}
  atoms := generatingAtoms
  generatedMembers := generatedMembers

/-- The original generators are explicitly present in the listed sigma-algebra. -/
theorem ex_2_4_1_generators_mem :
    A1 ∈ ex_2_4_1.generatedMembers ∧ A2 ∈ ex_2_4_1.generatedMembers := by
  exact ⟨atomUnion_mem_generatedMembers {0, 1}, atomUnion_mem_generatedMembers {1, 2}⟩

/-- The textbook symmetric difference identity. -/
theorem ex_2_4_1_symmDiff_eq :
    A1 ∆ A2 = ({a, b, d, e} : Set SixPoint) := by
  ext x
  cases x <;> simp [A1, A2, atomUnion, atomIndex, Set.mem_symmDiff]

/-- The symmetric difference of `A₁` and `A₂` appears as one of the generated sets. -/
theorem ex_2_4_1_symmDiff_mem :
    ({a, b, d, e} : Set SixPoint) ∈ ex_2_4_1.generatedMembers := by
  have hmem : atomUnion ({0, 2} : Finset (Fin 4)) ∈ ex_2_4_1.generatedMembers :=
    atomUnion_mem_generatedMembers {0, 2}
  convert hmem using 1
  ext x
  cases x <;> simp [atomUnion, atomIndex]
