import ToyApollo.Output.def_3_1
import Mathlib

/-!
# Example 3.1.2: the interval-length premeasure on `ℝ`

The source object is constructed before it is compared with Lebesgue measure:

* extended-endpoint half-open intervals give the atomic semiring;
* endpoint length is extended, by finite disjoint sums, to the generated field;
* representation independence is supplied by the common-refinement theorem for
  `AddContent.supClosure`;
* only then is the resulting `intervalLength` identified with `volume` and used
  to prove countable additivity.
-/

open Set ENNReal Function MeasureTheory

/-! ## The stable field interface -/

/-- Inductive field generated by a collection of sets. -/
inductive GeneratedField {Ω : Type*} (S : Set (Set Ω)) : Set (Set Ω)
  | basic (s : Set Ω) (h : s ∈ S) : GeneratedField S s
  | empty : GeneratedField S ∅
  | compl (s : Set Ω) (h : GeneratedField S s) : GeneratedField S sᶜ
  | union (s t : Set Ω) (hs : GeneratedField S s) (ht : GeneratedField S t) :
      GeneratedField S (s ∪ t)

/-- Finite, one-sided-unbounded, and two-sided-unbounded source intervals. -/
def B0_generators : Set (Set ℝ) :=
  {s | (∃ a b : ℝ, s = Ioc a b) ∨
    (∃ b : ℝ, s = Iic b) ∨
    (∃ a : ℝ, s = Ioi a) ∨ s = univ}

/-- The source field `B₀`.  Its carrier remains definitionally the deployed
`GeneratedField` interface used by downstream files. -/
def B0 : FieldOfSets ℝ where
  carrier := GeneratedField B0_generators
  empty_mem := GeneratedField.empty
  compl_mem := GeneratedField.compl
  union_mem := GeneratedField.union

/-- Every source-field set is Borel measurable. -/
theorem measurable_of_mem_B0 (s : Set ℝ) (h : s ∈ B0.carrier) : MeasurableSet s := by
  induction h with
  | basic s hs =>
      rcases hs with (⟨a, b, rfl⟩ | ⟨b, rfl⟩ | ⟨a, rfl⟩ | rfl)
      · exact measurableSet_Ioc
      · exact measurableSet_Iic
      · exact measurableSet_Ioi
      · exact MeasurableSet.univ
  | empty => exact MeasurableSet.empty
  | compl s _ ih => exact ih.compl
  | union s t _ _ ihs iht => exact ihs.union iht

namespace IntervalPremeasure

/-! ## Extended-endpoint atoms -/

/-- An ordered interval `(left,right]` with endpoints in `[-∞,+∞]`. -/
structure HalfOpen where
  left : EReal
  right : EReal
  ordered : left ≤ right

/-- The real trace of an extended-real half-open interval. -/
def HalfOpen.carrier (I : HalfOpen) : Set ℝ :=
  Real.toEReal ⁻¹' Ioc I.left I.right

/-- Textbook endpoint length: finite endpoint difference, and `∞` for every
nondegenerate unbounded interval. -/
noncomputable def HalfOpen.length (I : HalfOpen) : ℝ≥0∞ :=
  (I.right - I.left).toENNReal

/-- Open-closed intervals in an arbitrary ordered endpoint space. -/
private def iocSets (α : Type*) [LinearOrder α] : Set (Set α) :=
  {s | ∃ u v : α, u ≤ v ∧ s = Ioc u v}

/-- Pull a family of sets back along a function. -/
private def pullbackSets {α β : Type*} (f : α → β) (C : Set (Set β)) : Set (Set α) :=
  (fun s : Set β => f ⁻¹' s) '' C

/-- Pullback preserves the set-semiring operations.  `Finset.image` may merge
equal (in particular empty) preimages; its set union is nevertheless unchanged. -/
private theorem isSetSemiring_pullback {α β : Type*} (f : α → β)
    {C : Set (Set β)} (hC : IsSetSemiring C) :
    IsSetSemiring (pullbackSets f C) where
  empty_mem := by
    refine ⟨∅, hC.empty_mem, ?_⟩
    simp
  inter_mem := by
    rintro _ ⟨s, hs, rfl⟩ _ ⟨t, ht, rfl⟩
    refine ⟨s ∩ t, hC.inter_mem s hs t ht, ?_⟩
    ext x
    simp
  sdiff_eq_sUnion' := by
    classical
    rintro _ ⟨s, hs, rfl⟩ _ ⟨t, ht, rfl⟩
    obtain ⟨I, hIC, hIdis, hdiff⟩ := hC.sdiff_eq_sUnion' s hs t ht
    let J : Finset (Set α) := I.image (fun u => f ⁻¹' u)
    refine ⟨J, ?_, ?_, ?_⟩
    · intro u hu
      rcases Finset.mem_image.mp hu with ⟨v, hv, rfl⟩
      exact ⟨v, hIC hv, rfl⟩
    · intro u hu v hv huv
      rcases Finset.mem_image.mp hu with ⟨u', hu', rfl⟩
      rcases Finset.mem_image.mp hv with ⟨v', hv', rfl⟩
      have huv' : u' ≠ v' := by
        intro h
        subst v'
        exact huv rfl
      exact (hIdis hu' hv' huv').preimage f
    · calc
        f ⁻¹' s \ f ⁻¹' t = f ⁻¹' (s \ t) := by ext x; simp
        _ = f ⁻¹' (⋃₀ (I : Set (Set β))) :=
          congrArg (fun u : Set β => f ⁻¹' u) hdiff
        _ = ⋃₀ (J : Set (Set α)) := by
          ext x
          simp [J]

/-- The atomic interval family, expressed as real preimages of EReal `Ioc`s. -/
def atoms : Set (Set ℝ) :=
  pullbackSets Real.toEReal (iocSets EReal)

theorem atoms_isSetSemiring : IsSetSemiring atoms := by
  exact isSetSemiring_pullback Real.toEReal IsSetSemiring.Ioc

theorem HalfOpen.carrier_mem_atoms (I : HalfOpen) : I.carrier ∈ atoms := by
  exact ⟨Ioc I.left I.right, ⟨I.left, I.right, I.ordered, rfl⟩, rfl⟩

/-! ## Relating atoms to the stable generator family -/

/-- The EReal atom encoding is extensionally the already deployed generator
family.  Reversed finite endpoints merely encode the empty atom. -/
theorem atoms_eq_B0_generators : atoms = B0_generators := by
  classical
  ext s
  constructor
  · rintro ⟨_, ⟨u, v, huv, rfl⟩, rfl⟩
    cases u with
    | bot =>
        cases v with
        | bot =>
            exact Or.inl ⟨0, 0, by ext x; simp⟩
        | coe v =>
            exact Or.inr (Or.inl ⟨v, by ext x; simp⟩)
        | top =>
            exact Or.inr (Or.inr (Or.inr (by ext x; simp)))
    | coe u =>
        cases v with
        | bot => simp at huv
        | coe v =>
            exact Or.inl ⟨u, v, by ext x; simp⟩
        | top =>
            exact Or.inr (Or.inr (Or.inl ⟨u, by ext x; simp⟩))
    | top =>
        cases v with
        | bot => simp at huv
        | coe v => simp at huv
        | top =>
            exact Or.inl ⟨0, 0, by ext x; simp⟩
  · intro hs
    rcases hs with (⟨a, b, rfl⟩ | ⟨b, rfl⟩ | ⟨a, rfl⟩ | rfl)
    · by_cases hab : a ≤ b
      · refine ⟨Ioc (a : EReal) (b : EReal), ?_, ?_⟩
        · exact ⟨a, b, EReal.coe_le_coe hab, rfl⟩
        · ext x
          simp
      · refine ⟨Ioc (0 : EReal) 0, ⟨0, 0, le_rfl, rfl⟩, ?_⟩
        ext x
        simp only [mem_preimage, mem_Ioc, EReal.coe_lt_coe_iff,
          EReal.coe_le_coe_iff]
        grind
    · refine ⟨Ioc (⊥ : EReal) b, ⟨⊥, b, bot_le, rfl⟩, ?_⟩
      ext x
      simp
    · refine ⟨Ioc (a : EReal) ⊤, ⟨a, ⊤, le_top, rfl⟩, ?_⟩
      ext x
      simp
    · refine ⟨Ioc (⊥ : EReal) ⊤, ⟨⊥, ⊤, bot_le, rfl⟩, ?_⟩
      ext x
      simp

/-! ## Independent atomic length -/

/-- Canonical set-level interval length, defined without choosing endpoints and
without referring to a measure.  For a nonempty bounded interval it is the
diameter `sSup-sInf`; every nonempty unbounded atom has value `∞`. -/
noncomputable def atomLength (s : Set ℝ) : ℝ≥0∞ := by
  classical
  exact if s = ∅ then 0
    else if BddBelow s ∧ BddAbove s then ENNReal.ofReal (sSup s - sInf s)
    else ⊤

@[simp] theorem atomLength_empty : atomLength (∅ : Set ℝ) = 0 := by
  simp [atomLength]

theorem atomLength_Ioc (a b : ℝ) (hab : a ≤ b) :
    atomLength (Ioc a b) = ENNReal.ofReal (b - a) := by
  rcases hab.eq_or_lt with rfl | hab
  · simp [atomLength]
  · have hne : Ioc a b ≠ (∅ : Set ℝ) := (Set.nonempty_Ioc.mpr hab).ne_empty
    simp [atomLength, hne, csInf_Ioc hab, csSup_Ioc hab]

theorem atomLength_Iic (b : ℝ) : atomLength (Iic b) = ⊤ := by
  have hne : Iic b ≠ (∅ : Set ℝ) := Set.nonempty_Iic.ne_empty
  simp [atomLength, hne, not_bddBelow_Iic]

theorem atomLength_Ioi (a : ℝ) : atomLength (Ioi a) = ⊤ := by
  simp [atomLength, not_bddAbove_Ioi]

theorem atomLength_univ : atomLength (univ : Set ℝ) = ⊤ := by
  simp [atomLength, not_bddBelow_univ]

theorem atomLength_ne_top_iff (s : Set ℝ) :
    atomLength s ≠ ⊤ ↔ BddBelow s ∧ BddAbove s := by
  by_cases hs : s = ∅
  · subst s
    simp [atomLength]
  · by_cases hb : BddBelow s ∧ BddAbove s
    · simp [atomLength, hs, hb]
    · simp [atomLength, hs, hb]

/-- The canonical set-level definition evaluates to the textbook endpoint
length on every EReal half-open atom. -/
theorem atomLength_carrier (I : HalfOpen) :
    atomLength I.carrier = I.length := by
  rcases I with ⟨l, r, hlr⟩
  cases l with
  | bot =>
      cases r with
      | bot => simp [HalfOpen.carrier, HalfOpen.length, atomLength]
      | coe r =>
          have hcarrier :
              (HalfOpen.mk ⊥ r bot_le).carrier = Iic r := by
            ext x
            simp [HalfOpen.carrier]
          rw [hcarrier, atomLength_Iic]
          simp [HalfOpen.length]
      | top =>
          have hcarrier :
              (HalfOpen.mk ⊥ ⊤ bot_le).carrier = univ := by
            ext x
            simp [HalfOpen.carrier]
          rw [hcarrier, atomLength_univ]
          simp [HalfOpen.length]
  | coe l =>
      cases r with
      | bot => simp at hlr
      | coe r =>
          have hlr' : l ≤ r := EReal.coe_le_coe_iff.mp hlr
          have hcarrier :
              (HalfOpen.mk l r (EReal.coe_le_coe hlr')).carrier = Ioc l r := by
            ext x
            simp [HalfOpen.carrier]
          rw [hcarrier, atomLength_Ioc l r hlr']
          simp only [HalfOpen.length, ← EReal.coe_sub, EReal.real_coe_toENNReal]
      | top =>
          have hcarrier :
              (HalfOpen.mk l ⊤ le_top).carrier = Ioi l := by
            ext x
            simp [HalfOpen.carrier]
          rw [hcarrier, atomLength_Ioi]
          simp [HalfOpen.length]
  | top =>
      cases r with
      | bot => simp at hlr
      | coe r => simp at hlr
      | top => simp [HalfOpen.carrier, HalfOpen.length, atomLength]

/-- Endpoint length is representation-independent.  In particular, different
degenerate atoms such as `(⊥,⊥]` and `(⊤,⊤]` are not equated; their common empty
carrier is sent separately to zero by `atomLength_carrier`. -/
theorem HalfOpen.length_eq_of_carrier_eq (I J : HalfOpen)
    (h : I.carrier = J.carrier) : I.length = J.length := by
  by_cases hIempty : I.carrier = ∅
  · have hJempty : J.carrier = ∅ := by
      rw [← h]
      exact hIempty
    have hIzero : I.length = 0 := by
      rw [← atomLength_carrier I, hIempty, atomLength_empty]
    have hJzero : J.length = 0 := by
      rw [← atomLength_carrier J, hJempty, atomLength_empty]
    rw [hIzero, hJzero]
  · calc
      I.length = atomLength I.carrier := (atomLength_carrier I).symm
      _ = atomLength J.carrier := congrArg atomLength h
      _ = J.length := atomLength_carrier J

/-- A bounded atom is an ordinary finite-endpoint `Ioc` (with the empty atom
represented by `(0,0]`). -/
private theorem atom_eq_Ioc_of_bounded {s : Set ℝ} (hs : s ∈ atoms)
    (hb : BddBelow s ∧ BddAbove s) :
    ∃ a b : ℝ, a ≤ b ∧ s = Ioc a b := by
  rw [atoms_eq_B0_generators] at hs
  rcases hs with (⟨a, b, rfl⟩ | ⟨b, rfl⟩ | ⟨a, rfl⟩ | rfl)
  · by_cases hab : a ≤ b
    · exact ⟨a, b, hab, rfl⟩
    · refine ⟨0, 0, le_rfl, ?_⟩
      ext x
      simp only [mem_Ioc]
      grind
  · exact (not_bddBelow_Iic b hb.1).elim
  · exact (not_bddAbove_Ioi a hb.2).elim
  · exact (not_bddBelow_univ hb.1).elim

/-! ## The ENNReal endpoint telescope -/

/-- Direct bounded ENNReal telescope.  This follows the rightmost-interval
removal proof pattern, without instantiating the group-valued library interval
content constructor (whose value type requires an additive group). -/
private theorem atomLength_sUnion_bounded
    (I : Finset (Set ℝ))
    (hI : (I : Set (Set ℝ)) ⊆
      {s | ∃ u v : ℝ, u ≤ v ∧ s = Ioc u v})
    (hdis : PairwiseDisjoint (I : Set (Set ℝ)) id)
    (u v : ℝ) (huv : u ≤ v)
    (hunion : ⋃₀ (I : Set (Set ℝ)) = Ioc u v) :
    atomLength (Ioc u v) = ∑ s ∈ I, atomLength s := by
  classical
  induction hn : I.card generalizing I u v with
  | zero =>
      have hI0 : I = ∅ := Finset.card_eq_zero.mp hn
      subst I
      simp only [Finset.coe_empty, sUnion_empty] at hunion
      rw [← hunion]
      simp
  | succ n ih =>
      rcases huv.eq_or_lt with rfl | huv
      · have hUempty : ⋃₀ (I : Set (Set ℝ)) = (∅ : Set ℝ) := by
          simpa using hunion
        have hparts : ∀ s ∈ I, s = ∅ := by
          intro s hs
          apply Set.subset_empty_iff.mp
          rw [← hUempty]
          exact subset_sUnion_of_mem hs
        rw [atomLength_Ioc u u le_rfl]
        simp only [sub_self, ENNReal.ofReal_zero]
        symm
        apply Finset.sum_eq_zero
        intro s hs
        rw [hparts s hs, atomLength_empty]
      · have hv : v ∈ ⋃₀ (I : Set (Set ℝ)) := by
          rw [hunion]
          exact ⟨huv, le_rfl⟩
        obtain ⟨t, htI, hvt⟩ : ∃ t ∈ I, v ∈ t := by
          simpa using hv
        rcases hI htI with ⟨u', v', hu'v', rfl⟩
        have hsub : Ioc u' v' ⊆ Ioc u v := by
          rw [← hunion]
          exact subset_sUnion_of_mem htI
        have ⟨hv'v, huu'⟩ : v' ≤ v ∧ u ≤ u' :=
          (Ioc_subset_Ioc_iff (by grind)).mp hsub
        obtain rfl : v = v' := by grind
        let I' := I.erase (Ioc u' v)
        have I'I : (I' : Set (Set ℝ)) ⊆ (I : Set (Set ℝ)) :=
          Finset.coe_subset.mpr (Finset.erase_subset _ _)
        have I_eq_insert : I = insert (Ioc u' v) I' := by
          simp [I', htI]
        have UI' : ⋃₀ (I' : Set (Set ℝ)) = Ioc u u' := by
          have hremove :
              (Ioc u' v ∪ ⋃₀ (I' : Set (Set ℝ))) \ Ioc u' v =
                ⋃₀ (I' : Set (Set ℝ)) := by
            refine Disjoint.sup_sdiff_cancel_left ?_
            simp only [Finset.coe_erase, disjoint_sUnion_right, mem_diff,
              Finset.mem_singleton, and_imp, I']
            intro q hq hne
            exact (hdis hq htI hne).symm
          simp only [I_eq_insert, Finset.coe_insert, sUnion_insert] at hunion
          grind
        have hI' : (I' : Set (Set ℝ)) ⊆
            {s | ∃ a b : ℝ, a ≤ b ∧ s = Ioc a b} :=
          I'I.trans hI
        have hdis' : PairwiseDisjoint (I' : Set (Set ℝ)) id :=
          hdis.subset I'I
        have hcard : I'.card = n := by
          simp [I', htI, hn]
        have IH : atomLength (Ioc u u') = ∑ s ∈ I', atomLength s :=
          ih (I := I') (u := u) (v := u') hI' hdis' huu' UI' hcard
        rw [I_eq_insert, Finset.sum_insert, atomLength_Ioc u v huv.le,
          atomLength_Ioc u' v hu'v', ← IH, atomLength_Ioc u u' huu']
        · rw [← ENNReal.ofReal_add (sub_nonneg.mpr hu'v') (sub_nonneg.mpr huu')]
          congr 1
          ring
        · simp [I']

private theorem exists_atomLength_eq_top_of_not_bddBelow
    (I : Finset (Set ℝ)) (h : ¬ BddBelow (⋃₀ (I : Set (Set ℝ)))) :
    ∃ s ∈ I, atomLength s = ⊤ := by
  by_contra htop
  push_neg at htop
  apply h
  have hb : BddBelow (⋃ s ∈ (I : Set (Set ℝ)), s) :=
    (I.finite_toSet.bddBelow_biUnion).mpr fun s hs =>
      ((atomLength_ne_top_iff s).mp (htop s hs)).1
  simpa [sUnion_eq_biUnion] using hb

private theorem exists_atomLength_eq_top_of_not_bddAbove
    (I : Finset (Set ℝ)) (h : ¬ BddAbove (⋃₀ (I : Set (Set ℝ)))) :
    ∃ s ∈ I, atomLength s = ⊤ := by
  by_contra htop
  push_neg at htop
  apply h
  have hb : BddAbove (⋃ s ∈ (I : Set (Set ℝ)), s) :=
    (I.finite_toSet.bddAbove_biUnion).mpr fun s hs =>
      ((atomLength_ne_top_iff s).mp (htop s hs)).2
  simpa [sUnion_eq_biUnion] using hb

/-- Atomic finite additivity, including empty, bounded, and unbounded targets. -/
theorem atomLength_sUnion
    (I : Finset (Set ℝ)) (hI : (I : Set (Set ℝ)) ⊆ atoms)
    (hdis : PairwiseDisjoint (I : Set (Set ℝ)) id)
    (hmem : ⋃₀ (I : Set (Set ℝ)) ∈ atoms) :
    atomLength (⋃₀ (I : Set (Set ℝ))) = ∑ s ∈ I, atomLength s := by
  rw [atoms_eq_B0_generators] at hmem
  rcases hmem with (⟨a, b, habUnion⟩ | ⟨b, hbUnion⟩ | ⟨a, haUnion⟩ | hUniv)
  · by_cases hab : a ≤ b
    · have hsub (s : Set ℝ) (hs : s ∈ I) : s ⊆ Ioc a b := by
        rw [← habUnion]
        exact subset_sUnion_of_mem hs
      have hI' : (I : Set (Set ℝ)) ⊆
          {s | ∃ u v : ℝ, u ≤ v ∧ s = Ioc u v} := by
        intro s hs
        exact atom_eq_Ioc_of_bounded (hI hs)
          ⟨bddBelow_Ioc.mono (hsub s hs), bddAbove_Ioc.mono (hsub s hs)⟩
      rw [habUnion]
      exact atomLength_sUnion_bounded I hI' hdis a b hab habUnion
    · have hEmpty : Ioc a b = (∅ : Set ℝ) := by
        ext x
        simp only [mem_Ioc, Set.mem_empty_iff_false]
        grind
      have hsub (s : Set ℝ) (hs : s ∈ I) : s ⊆ (∅ : Set ℝ) := by
        rw [← hEmpty, ← habUnion]
        exact subset_sUnion_of_mem hs
      have hI' : (I : Set (Set ℝ)) ⊆
          {s | ∃ u v : ℝ, u ≤ v ∧ s = Ioc u v} := by
        intro s hs
        refine ⟨0, 0, le_rfl, ?_⟩
        simpa using Set.subset_empty_iff.mp (hsub s hs)
      have hUnion0 : ⋃₀ (I : Set (Set ℝ)) = Ioc (0 : ℝ) 0 := by
        rw [habUnion, hEmpty]
        simp
      rw [habUnion, hEmpty]
      simpa [atomLength] using
        atomLength_sUnion_bounded I hI' hdis 0 0 le_rfl hUnion0
  · have hnot : ¬ BddBelow (⋃₀ (I : Set (Set ℝ))) := by
      rw [hbUnion]
      exact not_bddBelow_Iic b
    have htop := exists_atomLength_eq_top_of_not_bddBelow I hnot
    rw [hbUnion, atomLength_Iic]
    exact (ENNReal.sum_eq_top.mpr htop).symm
  · have hnot : ¬ BddAbove (⋃₀ (I : Set (Set ℝ))) := by
      rw [haUnion]
      exact not_bddAbove_Ioi a
    have htop := exists_atomLength_eq_top_of_not_bddAbove I hnot
    rw [haUnion, atomLength_Ioi]
    exact (ENNReal.sum_eq_top.mpr htop).symm
  · have hnot : ¬ BddBelow (⋃₀ (I : Set (Set ℝ))) := by
      rw [hUniv]
      exact not_bddBelow_univ
    have htop := exists_atomLength_eq_top_of_not_bddBelow I hnot
    rw [hUniv, atomLength_univ]
    exact (ENNReal.sum_eq_top.mpr htop).symm

/-- The independent endpoint-length additive content on source atoms. -/
noncomputable def atomContent : AddContent ℝ≥0∞ atoms where
  toFun := atomLength
  empty' := atomLength_empty
  sUnion' := atomLength_sUnion

/-- Independent finite-disjoint extension to finite unions of atoms. -/
noncomputable def ringContent : AddContent ℝ≥0∞ (supClosure atoms) :=
  atomContent.supClosure atoms_isSetSemiring

/-! ## Existing generated field = finite-disjoint normal forms -/

private theorem generatedField_sUnion_finset (I : Finset (Set ℝ))
    (hI : (I : Set (Set ℝ)) ⊆ GeneratedField B0_generators) :
    GeneratedField B0_generators (⋃₀ (I : Set (Set ℝ))) := by
  classical
  induction I using Finset.induction with
  | empty => simpa using (GeneratedField.empty : GeneratedField B0_generators ∅)
  | @insert s I hs ih =>
      rw [Finset.coe_insert, sUnion_insert]
      apply GeneratedField.union
      · exact hI (by simp)
      · exact ih fun t ht => hI (by simp [ht])

/-- The stable inductive field is exactly the finite-union closure of source
atoms. -/
theorem generatedField_eq_supClosure_atoms :
    GeneratedField B0_generators = supClosure atoms := by
  ext s
  constructor
  · intro hs
    induction hs with
    | basic s hs =>
        apply subset_supClosure
        rwa [atoms_eq_B0_generators]
    | empty => exact subset_supClosure atoms_isSetSemiring.empty_mem
    | compl s _ ih =>
        have hunivAtom : (univ : Set ℝ) ∈ atoms := by
          rw [atoms_eq_B0_generators]
          exact Or.inr (Or.inr (Or.inr rfl))
        have hdiff : (univ : Set ℝ) \ s ∈ supClosure atoms :=
          atoms_isSetSemiring.isSetRing_supClosure.sdiff_mem
            (subset_supClosure hunivAtom) ih
        convert hdiff using 1
        ext x
        simp
    | union s t _ _ ihs iht =>
        exact atoms_isSetSemiring.isSetRing_supClosure.union_mem ihs iht
  · intro hs
    obtain ⟨P, hP⟩ := atoms_isSetSemiring.mem_supClosure_iff.mp hs
    have hUnion : ⋃₀ (P.parts : Set (Set ℝ)) = s := by
      rw [← sSup_eq_sUnion, ← Finset.sup_id_eq_sSup, P.sup_parts]
    rw [← hUnion]
    apply generatedField_sUnion_finset P.parts
    intro t ht
    apply GeneratedField.basic
    have := hP ht
    simpa [atoms_eq_B0_generators] using this

/-- A textbook normal form is a finite pairwise-disjoint partition into
half-open atoms. -/
def NormalForm (s : Set ℝ) :=
  {P : Finpartition s // (P.parts : Set (Set ℝ)) ⊆ atoms}

noncomputable def NormalForm.length {s : Set ℝ} (P : NormalForm s) : ℝ≥0∞ :=
  ∑ t ∈ P.val.parts, atomLength t

theorem mem_B0_iff_nonempty_normalForm {s : Set ℝ} :
    s ∈ B0.carrier ↔ Nonempty (NormalForm s) := by
  change GeneratedField B0_generators s ↔ _
  rw [generatedField_eq_supClosure_atoms]
  constructor
  · intro hs
    obtain ⟨P, hP⟩ := atoms_isSetSemiring.mem_supClosure_iff.mp hs
    exact ⟨⟨P, hP⟩⟩
  · rintro ⟨⟨P, hP⟩⟩
    exact atoms_isSetSemiring.mem_supClosure_iff.mpr ⟨P, hP⟩

theorem ringContent_eq_normalForm {s : Set ℝ} (P : NormalForm s) :
    ringContent s = P.length := by
  exact AddContent.supClosure_apply_finpartition atoms_isSetSemiring atomContent P.property

/-- The explicit representation-independence theorem.  It is proved entirely
inside the additive-content/common-refinement layer, before `volume` is used. -/
theorem normalForm_length_eq {s : Set ℝ} (P Q : NormalForm s) :
    P.length = Q.length := by
  rw [← ringContent_eq_normalForm P, ← ringContent_eq_normalForm Q]

end IntervalPremeasure

/-! ## Independent interval length on `B₀` -/

/-- Textbook length on the existing source field. -/
noncomputable def intervalLength
    (s : {s : Set ℝ // s ∈ B0.carrier}) : ℝ≥0∞ :=
  IntervalPremeasure.ringContent s.val

theorem intervalLength_eq_normalForm
    (s : {s : Set ℝ // s ∈ B0.carrier})
    (P : IntervalPremeasure.NormalForm s.val) :
    intervalLength s = P.length := by
  exact IntervalPremeasure.ringContent_eq_normalForm P

private theorem intervalLength_eq_atomLength
    (s : Set ℝ) (hs : s ∈ B0.carrier)
    (ha : s ∈ IntervalPremeasure.atoms) :
    intervalLength ⟨s, hs⟩ = IntervalPremeasure.atomLength s := by
  change IntervalPremeasure.ringContent s = IntervalPremeasure.atomLength s
  exact AddContent.supClosure_apply_of_mem IntervalPremeasure.atoms_isSetSemiring
    IntervalPremeasure.atomContent ha

theorem intervalLength_empty :
    intervalLength ⟨∅, B0.empty_mem⟩ = 0 := by
  rw [intervalLength_eq_atomLength ∅ B0.empty_mem
    IntervalPremeasure.atoms_isSetSemiring.empty_mem]
  exact IntervalPremeasure.atomLength_empty

theorem intervalLength_Ioc (a b : ℝ)
    (h : Ioc a b ∈ B0.carrier) :
    intervalLength ⟨Ioc a b, h⟩ = ENNReal.ofReal (b - a) := by
  have ha : Ioc a b ∈ IntervalPremeasure.atoms := by
    rw [IntervalPremeasure.atoms_eq_B0_generators]
    exact Or.inl ⟨a, b, rfl⟩
  rw [intervalLength_eq_atomLength _ h ha]
  by_cases hab : a ≤ b
  · exact IntervalPremeasure.atomLength_Ioc a b hab
  · have hEmpty : Ioc a b = (∅ : Set ℝ) := by
      ext x
      simp only [mem_Ioc, Set.mem_empty_iff_false]
      grind
    rw [hEmpty, IntervalPremeasure.atomLength_empty]
    rw [ENNReal.ofReal_of_nonpos (sub_nonpos.mpr (not_le.mp hab).le)]

theorem intervalLength_Iic (b : ℝ)
    (h : Iic b ∈ B0.carrier) : intervalLength ⟨Iic b, h⟩ = ⊤ := by
  have ha : Iic b ∈ IntervalPremeasure.atoms := by
    rw [IntervalPremeasure.atoms_eq_B0_generators]
    exact Or.inr (Or.inl ⟨b, rfl⟩)
  rw [intervalLength_eq_atomLength _ h ha]
  exact IntervalPremeasure.atomLength_Iic b

theorem intervalLength_Ioi (a : ℝ)
    (h : Ioi a ∈ B0.carrier) : intervalLength ⟨Ioi a, h⟩ = ⊤ := by
  have ha : Ioi a ∈ IntervalPremeasure.atoms := by
    rw [IntervalPremeasure.atoms_eq_B0_generators]
    exact Or.inr (Or.inr (Or.inl ⟨a, rfl⟩))
  rw [intervalLength_eq_atomLength _ h ha]
  exact IntervalPremeasure.atomLength_Ioi a

theorem intervalLength_univ (h : (univ : Set ℝ) ∈ B0.carrier) :
    intervalLength ⟨univ, h⟩ = ⊤ := by
  have ha : (univ : Set ℝ) ∈ IntervalPremeasure.atoms := by
    rw [IntervalPremeasure.atoms_eq_B0_generators]
    exact Or.inr (Or.inr (Or.inr rfl))
  rw [intervalLength_eq_atomLength _ h ha]
  exact IntervalPremeasure.atomLength_univ

/-- Independent finite additivity on disjoint source-field sets. -/
theorem intervalLength_union {s t : Set ℝ}
    (hs : s ∈ B0.carrier) (ht : t ∈ B0.carrier)
    (hut : s ∪ t ∈ B0.carrier) (hdis : Disjoint s t) :
    intervalLength ⟨s ∪ t, hut⟩ =
      intervalLength ⟨s, hs⟩ + intervalLength ⟨t, ht⟩ := by
  change IntervalPremeasure.ringContent (s ∪ t) =
    IntervalPremeasure.ringContent s + IntervalPremeasure.ringContent t
  have hs' : s ∈ supClosure IntervalPremeasure.atoms := by
    change GeneratedField B0_generators s at hs
    rw [IntervalPremeasure.generatedField_eq_supClosure_atoms] at hs
    exact hs
  have ht' : t ∈ supClosure IntervalPremeasure.atoms := by
    change GeneratedField B0_generators t at ht
    rw [IntervalPremeasure.generatedField_eq_supClosure_atoms] at ht
    exact ht
  have hut' : s ∪ t ∈ supClosure IntervalPremeasure.atoms := by
    change GeneratedField B0_generators (s ∪ t) at hut
    rw [IntervalPremeasure.generatedField_eq_supClosure_atoms] at hut
    exact hut
  exact addContent_union' hs' ht' hut' hdis

/-! ## The late, reusable bridge to Lebesgue measure -/

namespace IntervalPremeasure

theorem measurable_of_mem_atoms {s : Set ℝ} (hs : s ∈ atoms) : MeasurableSet s := by
  apply measurable_of_mem_B0 s
  apply GeneratedField.basic
  rwa [← atoms_eq_B0_generators]

/-- Volume agrees with the independently defined atomic endpoint length. -/
theorem volume_eq_atomLength {s : Set ℝ} (hs : s ∈ atoms) :
    volume s = atomLength s := by
  rw [atoms_eq_B0_generators] at hs
  rcases hs with (⟨a, b, rfl⟩ | ⟨b, rfl⟩ | ⟨a, rfl⟩ | rfl)
  · by_cases hab : a ≤ b
    · rw [Real.volume_Ioc, atomLength_Ioc a b hab]
    · have hEmpty : Ioc a b = (∅ : Set ℝ) := by
        ext x
        simp only [mem_Ioc, Set.mem_empty_iff_false]
        grind
      simp [hEmpty]
  · rw [Real.volume_Iic, atomLength_Iic]
  · rw [Real.volume_Ioi, atomLength_Ioi]
  · rw [Real.volume_univ, atomLength_univ]

/-- The atom bridge in the exact extended-endpoint form. -/
theorem volume_halfOpen (I : HalfOpen) : volume I.carrier = I.length := by
  calc
    volume I.carrier = atomLength I.carrier :=
      volume_eq_atomLength (HalfOpen.carrier_mem_atoms I)
    _ = I.length := atomLength_carrier I

theorem volume_eq_normalForm_length {s : Set ℝ} (P : NormalForm s) :
    volume s = P.length := by
  nth_rewrite 1 [← P.val.sup_parts]
  rw [Finset.sup_set_eq_biUnion,
    measure_biUnion_finset P.val.disjoint
      (fun t ht => measurable_of_mem_atoms (P.property ht))]
  apply Finset.sum_congr rfl
  intro t ht
  exact volume_eq_atomLength (P.property ht)

end IntervalPremeasure

/-- General, reusable bridge; representation independence has already been
proved and was not obtained by rewriting to `volume`. -/
theorem intervalLength_eq_volume (s : Set ℝ) (hs : s ∈ B0.carrier) :
    intervalLength ⟨s, hs⟩ = volume s := by
  obtain ⟨P⟩ := (IntervalPremeasure.mem_B0_iff_nonempty_normalForm).mp hs
  calc
    intervalLength ⟨s, hs⟩ = P.length := intervalLength_eq_normalForm ⟨s, hs⟩ P
    _ = volume s := (IntervalPremeasure.volume_eq_normalForm_length P).symm

theorem volume_eq_intervalLength (s : Set ℝ) (hs : s ∈ B0.carrier) :
    volume s = intervalLength ⟨s, hs⟩ :=
  (intervalLength_eq_volume s hs).symm

/-! ## Countable additivity and final source premeasure -/

theorem intervalLength_iUnion
    (A : ℕ → Set ℝ) (hA : ∀ i, A i ∈ B0.carrier)
    (hU : (⋃ i, A i) ∈ B0.carrier)
    (hdis : Pairwise (Disjoint on A)) :
    intervalLength ⟨⋃ i, A i, hU⟩ =
      ∑' i, intervalLength ⟨A i, hA i⟩ := by
  calc
    intervalLength ⟨⋃ i, A i, hU⟩ = volume (⋃ i, A i) :=
      intervalLength_eq_volume _ hU
    _ = ∑' i, volume (A i) :=
      measure_iUnion hdis (fun i => measurable_of_mem_B0 (A i) (hA i))
    _ = ∑' i, intervalLength ⟨A i, hA i⟩ := by
      apply tsum_congr
      intro i
      exact (intervalLength_eq_volume (A i) (hA i)).symm

/-- Example 3.1.2: the independently defined interval-length function is a
premeasure on `B₀`. -/
noncomputable def Example_3_1_2 : Premeasure B0 where
  μ₀ := intervalLength
  map_empty := intervalLength_empty
  sigma_additive := intervalLength_iUnion

@[simp] theorem Example_3_1_2_apply
    (s : {s : Set ℝ // s ∈ B0.carrier}) :
    Example_3_1_2.μ₀ s = intervalLength s := rfl

/-- Task-id landing: records the source-facing defining property rather than
introducing a second premeasure wrapper. -/
theorem ex_3_1_2 : Example_3_1_2.μ₀ = intervalLength := rfl
