import ToyApollo.Output.def_3_2
import ToyApollo.Output.thm_3_1
import ToyApollo.Output.ex_3_1_2
import ToyApollo.Output.def_3_3
import Mathlib.MeasureTheory.Measure.Lebesgue.Basic
import Mathlib.MeasureTheory.Constructions.BorelSpace.Order
import Mathlib.Tactic

open MeasureTheory Set ENNReal

/-- The interval pre-measure from Example 3.1.2 is σ-finite. -/
theorem Example_3_1_2_sigmaFinite : IsSigmaFinite Example_3_1_2 := by
  refine ⟨fun n => Ioc (-(n : ℝ)) n, ?_, ?_, ?_⟩
  · intro n
    exact GeneratedField.basic _ (Or.inl ⟨-(n : ℝ), (n : ℝ), rfl⟩)
  · ext x
    constructor
    · intro _
      simp
    · intro _
      rcases exists_nat_gt |x| with ⟨n, hn⟩
      refine mem_iUnion.mpr ⟨n, ?_⟩
      rw [mem_Ioc]
      constructor
      · have hleft : -(n : ℝ) < -|x| := by linarith
        exact lt_of_lt_of_le hleft (neg_abs_le x)
      · have hright : x ≤ |x| := le_abs_self x
        linarith
  · intro n
    rw [Example_3_1_2_apply, intervalLength_Ioc]
    exact ENNReal.ofReal_lt_top

/-- The field `B0` from Example 3.1.2 generates the Borel σ-algebra on `ℝ`. -/
theorem generateFrom_B0_eq_borel : MeasurableSpace.generateFrom B0.carrier = borel ℝ := by
  apply le_antisymm
  · exact MeasurableSpace.generateFrom_le fun s hs => measurable_of_mem_B0 s hs
  · rw [borel_eq_generateFrom_Ioc]
    exact MeasurableSpace.generateFrom_mono fun s hs => by
      rcases hs with ⟨a, b, _, rfl⟩
      exact GeneratedField.basic _ (Or.inl ⟨a, b, rfl⟩)

/-- `volume` is the Borel-measure extension of the pre-measure from Example 3.1.2. -/
theorem volume_extends_Example_3_1_2 (s : Set ℝ) (hs : s ∈ B0.carrier) :
    volume s = Example_3_1_2.μ₀ ⟨s, hs⟩ := by
  rw [Example_3_1_2_apply]
  exact volume_eq_intervalLength s hs

/--
The unique extension of the interval-length pre-measure to the Borel σ-algebra on `ℝ`
is the standard Lebesgue/Borel measure `volume`.
-/
theorem borel_measure_extension_unique (μ : Measure ℝ)
    (h : ∀ a b, μ (Ioc a b) = ENNReal.ofReal (b - a)) :
    μ = volume := by
  haveI : IsLocallyFiniteMeasure μ := ⟨by
    intro x
    refine ⟨Ioo (x - 1) (x + 1), Ioo_mem_nhds (by linarith) (by linarith), ?_⟩
    calc
      μ (Ioo (x - 1) (x + 1)) ≤ μ (Ioc (x - 1) (x + 1)) := measure_mono Ioo_subset_Ioc_self
      _ = ENNReal.ofReal ((x + 1) - (x - 1)) := h (x - 1) (x + 1)
      _ < ⊤ := ENNReal.ofReal_lt_top⟩
  apply Measure.ext_of_Ioc
  intro a b _
  rw [h a b, Real.volume_Ioc]

private theorem castMeasure_apply {X : Type*} {m₁ m₂ : MeasurableSpace X}
    (h : m₁ = m₂) (μ : @Measure X m₂) (s : Set X) :
    (Eq.mpr (congrArg (fun m => @Measure X m) h) μ) s = μ s := by
  subst m₂
  rfl

private theorem generateFrom_B0_eq_real_measurable :
    MeasurableSpace.generateFrom B0.carrier =
      (inferInstance : MeasurableSpace ℝ) :=
  generateFrom_B0_eq_borel.trans BorelSpace.measurable_eq.symm

/-- The standard Borel/Lebesgue measure, transported to the measurable space
generated by the interval field `B0`. -/
noncomputable def borelVolumeOnGenerated :
    @Measure ℝ (MeasurableSpace.generateFrom B0.carrier) :=
  Eq.mpr
    (congrArg (fun m => @Measure ℝ m) generateFrom_B0_eq_real_measurable)
    volume

/-- The transported Borel measure is an extension of the interval-length premeasure. -/
theorem borelVolumeOnGenerated_isExtension :
    IsExtension B0 Example_3_1_2 borelVolumeOnGenerated := by
  intro s hs
  change
    (Eq.mpr
      (congrArg (fun m => @Measure ℝ m) generateFrom_B0_eq_real_measurable)
      volume) s = Example_3_1_2.μ₀ ⟨s, hs⟩
  exact
    (castMeasure_apply generateFrom_B0_eq_real_measurable volume s).trans
      (volume_extends_Example_3_1_2 s hs)

/-- Example 3.1.4: the interval-length premeasure has a unique Borel extension. -/
theorem ex_3_1_4 :
    ∃! μ : @Measure ℝ (MeasurableSpace.generateFrom B0.carrier),
      IsExtension B0 Example_3_1_2 μ :=
  extension_unique B0 Example_3_1_2 Example_3_1_2_sigmaFinite

/-- Every extension of the interval-length premeasure is the transported Borel measure. -/
theorem borelVolumeOnGenerated_unique
    (μ : @Measure ℝ (MeasurableSpace.generateFrom B0.carrier))
    (hμ : IsExtension B0 Example_3_1_2 μ) :
    μ = borelVolumeOnGenerated :=
  ex_3_1_4.unique hμ borelVolumeOnGenerated_isExtension
