import Mathlib
import ToyApollo.Output.thm_4_3

open MeasureTheory Set Cardinal

/-!
# Example 4.2.1: Non-Borel Subset of Cantor Set

This file constructs a subset N of the Cantor set that is Lebesgue measurable (as a null set)
but not Borel measurable, and shows that the composition of the indicator function of N with
the squaring function is not measurable.

The original statement used `CantorSet` (which doesn't exist in Mathlib; the correct name is
`cantorSet`) and had `MeasurableSet N ∧ ¬ MeasurableSet[Borel ℝ] N` which is contradictory
since the default MeasurableSpace on ℝ in Mathlib IS the Borel σ-algebra. The corrected
formulation uses `NullMeasurableSet N volume` for Lebesgue measurability and
`¬ MeasurableSet N` for non-Borel-measurability.
-/

/-! ## Part 1: Volume of the Cantor set is zero -/

/-
The image of a set under `(· / 3)` equals the preimage under `(· * 3)`.
-/
lemma image_div3_eq_preimage_mul3 (S : Set ℝ) :
    (· / 3) '' S = (· * 3) ⁻¹' S := by
      grind

/-
The image of a set under `(2 + ·) / 3` equals the preimage under `(· * 3 - 2)`.
-/
lemma image_add2_div3_eq_preimage (S : Set ℝ) :
    (fun x => (2 + x) / 3) '' S = (fun y => y * 3 - 2) ⁻¹' S := by
      grind

/-
The measure of a set scaled by 1/3 is 1/3 of the original measure.
-/
lemma volume_image_div3 (S : Set ℝ) :
    volume ((· / 3) '' S) = ENNReal.ofReal (1/3) * volume S := by
      convert Real.volume_preimage_mul_left ( show ( 3 : ℝ ) ≠ 0 by norm_num ) ( S ) using 1 <;> ring_nf;
      congr with x ; aesop

/-
The measure of a set under the map `(2 + ·) / 3` is 1/3 of the original measure.
-/
lemma volume_image_add2_div3 (S : Set ℝ) :
    volume ((fun x => (2 + x) / 3) '' S) = ENNReal.ofReal (1/3) * volume S := by
      convert volume_image_div3 ( ( fun y => y + 2 ) '' S ) using 1 ; norm_num;
      · grind +suggestions;
      · norm_num [ Set.image_add_right ]

/-
volume of preCantorSet n is at most (2/3)^n.
-/
lemma volume_preCantorSet_le (n : ℕ) :
    volume (preCantorSet n) ≤ ENNReal.ofReal ((2/3 : ℝ) ^ n) := by
      induction' n with n ih;
      · erw [ Real.volume_Icc ] ; norm_num;
      · refine' le_trans ( MeasureTheory.measure_union_le _ _ ) _;
        rw [ volume_image_div3, volume_image_add2_div3 ];
        convert mul_le_mul_left' ih ( ENNReal.ofReal ( 1 / 3 ) + ENNReal.ofReal ( 1 / 3 ) ) using 1 ; ring;
        rw [ ← ENNReal.ofReal_add ] <;> norm_num ; ring

/-
The Cantor set has Lebesgue measure zero.
-/
lemma volume_cantorSet_eq_zero : volume cantorSet = 0 := by
  have h_cantor_subset : ∀ n, volume (preCantorSet n) ≤ ENNReal.ofReal ((2/3 : ℝ) ^ n) :=
    fun n => volume_preCantorSet_le n
  -- Since the Cantor set is the intersection of the preCantorSet n, its volume is less than or equal to the volume of any preCantorSet n.
  have h_cantor_le : ∀ n, volume cantorSet ≤ ENNReal.ofReal ((2/3 : ℝ) ^ n) := by
    exact fun n => le_trans ( MeasureTheory.measure_mono <| Set.iInter_subset _ _ ) ( h_cantor_subset n );
  -- Since $(2/3)^n \to 0$ as $n \to \infty$, the volume of the Cantor set must also be zero.
  have h_cantor_zero : Filter.Tendsto (fun n => ENNReal.ofReal ((2/3 : ℝ) ^ n)) Filter.atTop (nhds 0) := by
    simpa using ENNReal.tendsto_ofReal ( tendsto_pow_atTop_nhds_zero_of_lt_one ( by norm_num ) ( by norm_num : ( 2 : ℝ ) / 3 < 1 ) );
  exact le_antisymm ( le_of_tendsto_of_tendsto' tendsto_const_nhds h_cantor_zero h_cantor_le ) bot_le

/-! ## Part 2: Existence of a non-Borel subset of the Cantor set -/

/-
The number of Borel-measurable subsets of ℝ is at most continuum.
-/
lemma cardinal_borel_le_continuum :
    Cardinal.mk {t : Set ℝ | MeasurableSet t} ≤ Cardinal.continuum := by
      -- The Borel σ-algebra is generated by the countable basis of open sets in ℝ.
      have h_borel : (borel ℝ) = MeasurableSpace.generateFrom (TopologicalSpace.countableBasis ℝ) := by
        -- Apply the fact that the Borel σ-algebra is generated by the countable basis.
        apply TopologicalSpace.IsTopologicalBasis.borel_eq_generateFrom; exact TopologicalSpace.isBasis_countableBasis ℝ;
      have h_card : Cardinal.mk { t : Set ℝ | @MeasurableSet ℝ ( MeasurableSpace.generateFrom ( TopologicalSpace.countableBasis ℝ ) ) t } ≤ Cardinal.continuum := by
        apply_rules [ MeasurableSpace.cardinal_generateMeasurable_le_continuum ];
        exact le_trans ( Cardinal.mk_le_aleph0_iff.mpr <| by exact Encodable.countable ) ( Cardinal.aleph0_le_continuum );
      convert h_card using 1;
      congr!

/-
The power set of the Cantor set has cardinality strictly greater than continuum.
-/
lemma cardinal_powerset_cantorSet_gt_continuum :
    Cardinal.continuum < Cardinal.mk (Set cantorSet) := by
      -- The set of all functions from ℕ to Bool has cardinality 2^ℵ₀.
      have h_card_cantor : Cardinal.mk (cantorSet) = Cardinal.continuum := by
        refine' le_antisymm _ _;
        · exact le_trans ( Cardinal.mk_subtype_le _ ) ( by simp +decide [ Cardinal.mk_real ] );
        · refine' le_trans _ ( Cardinal.mk_le_of_injective _ );
          rotate_left;
          exact ( ℕ → Bool );
          exact fun f => ⟨ _, cantorSetEquivNatToBool.symm f |>.2 ⟩;
          · intro f g h; aesop;
          · simp +decide [ Cardinal.mk_real ];
      simp +decide [ h_card_cantor, Cardinal.cantor ]

/-
There exists a non-Borel-measurable subset of the Cantor set.
-/
lemma exists_non_borel_subset_cantorSet :
    ∃ N : Set ℝ, N ⊆ cantorSet ∧ ¬ MeasurableSet N := by
      -- By contradiction, assume every subset of cantorSet is measurable.
      by_contra h_contra
      have : Cardinal.mk (Set cantorSet) ≤ Cardinal.mk {t : Set ℝ | MeasurableSet t} := by
        refine' ⟨ fun N => ⟨ N.image Subtype.val, _ ⟩, _ ⟩;
        all_goals norm_num [ Function.Injective ];
        grind +revert;
      grind +suggestions

/-! ## Part 3: Non-measurability of the composition -/

/-
If N ⊆ [0, ∞) and the preimage of N under squaring is measurable, then N is measurable.
This follows because sqrt is continuous (hence measurable) and we can recover N from
the preimage using sqrt.
-/
lemma measurableSet_of_sq_preimage {N : Set ℝ}
    (hN : N ⊆ Set.Ici 0)
    (h : MeasurableSet ((fun x : ℝ => x ^ 2) ⁻¹' N)) :
    MeasurableSet N := by
      convert h.preimage ( show Measurable Real.sqrt from ?_ ) |> MeasurableSet.inter <| show MeasurableSet ( Set.Ici 0 ) from measurableSet_Ici;
      · grind;
      · exact Real.continuous_sqrt.measurable

/-
The composition of indicator_N with x^2 is not measurable when N is a non-Borel
subset of [0,1].
-/
lemma not_measurable_indicator_comp_sq {N : Set ℝ}
    (hN : N ⊆ Set.Icc 0 1) (hNm : ¬ MeasurableSet N) :
    ¬ Measurable (Set.indicator N (fun _ => (1 : ℝ)) ∘ (fun x : ℝ => x ^ 2)) := by
      -- Suppose for contradiction that the composition is measurable.
      by_contra h_contra

      -- Then the preimage of {1} under the composition is measurable.
      have h_preimage : MeasurableSet ((fun x : ℝ => x ^ 2) ⁻¹' N) := by
        convert h_contra ( MeasurableSingletonClass.measurableSet_singleton 1 ) using 1 ; aesop;
      grind +suggestions

/-! ## Main theorem -/

/-
There exists a subset N of the Cantor set that is:
- Lebesgue measurable (null measurable, since it's a null set)
- Has Lebesgue measure zero
- Is not Borel measurable
- The composition of the indicator function of N with x² is not (Borel-)measurable

This corrects the original statement which used `CantorSet` (→ `cantorSet`) and had
a contradictory `MeasurableSet N ∧ ¬ MeasurableSet[Borel ℝ] N` condition.
-/
theorem ex_4_2_lebesgue_borel : ∃ (N : Set ℝ), N ⊆ cantorSet ∧
    NullMeasurableSet N volume ∧
    volume N = 0 ∧
    ¬ MeasurableSet N ∧
    let f : ℝ → ℝ := fun x => x ^ 2
    let g : ℝ → ℝ := Set.indicator N (fun _ => (1 : ℝ))
    ¬ Measurable (g ∘ f) := by
      obtain ⟨ N, hN₁, hN₂ ⟩ := exists_non_borel_subset_cantorSet;
      refine' ⟨ N, hN₁, _, _, hN₂, _ ⟩;
      · exact MeasureTheory.NullMeasurableSet.of_null ( MeasureTheory.measure_mono_null hN₁ volume_cantorSet_eq_zero );
      · exact MeasureTheory.measure_mono_null hN₁ ( volume_cantorSet_eq_zero );
      · refine' not_measurable_indicator_comp_sq ( hN₁.trans _ ) hN₂;
        exact cantorSet_subset_unitInterval