import Mathlib
import ToyApollo.Output.ch8_discrete_pmf_core
import ToyApollo.Output.thm_8_6

open MeasureTheory Set
open Ch8DiscretePMFCore
open scoped BigOperators

noncomputable section

/- 
TASK ID: ex_8_4_3
TYPE: Example_Proof
SOURCE PLAN: 34_chap8_total_variation_distance
TASK CONTENT:
\textbf{Example 8.4.3 (Total Variation Distance Between Bernoulli and Poisson)} \\
Let $P$ be a Bernoulli distribution with $P(\{1\})=\lambda$ and $P(\{0\})=1-\lambda$ and $Q$ be a Poisson distribution with mean $\lambda$, where $\lambda$ is a real number between 0 and 1. For $k\ge 0$, $Q(\{k\})=\dfrac{\lambda^k}{k!}e^{-\lambda}$. Applying Theorem 8.6, we obtain
\[
d_{TV}(P,Q)
=
\frac{1}{2}|1-\lambda-e^{-\lambda}|
+
\frac{1}{2}|\lambda-\lambda e^{-\lambda}|
+
\frac{1}{2}\sum_{k=2}^{\infty} \frac{\lambda^k}{k!}e^{-\lambda}.
\]

The infinite sum on the right-hand side can be simplified to $\frac{1}{2}(1-e^{\lambda}-\lambda e^{-\lambda})$. We thus have
\[
d_{TV}(P,Q)
=
\frac{1}{2}|1-\lambda-e^{-\lambda}|
+
\frac{1}{2}|\lambda-\lambda e^{-\lambda}|
+
\frac{1}{2}(1-e^{\lambda}-\lambda e^{-\lambda}).
\]

Since $1-\lambda$ is less than or equal to $e^{-\lambda}$ for all $\lambda$, we can simplify this expression as follows:
\[
d_{TV}(P,Q)
=
\frac{1}{2}\left[e^{-\lambda}+\lambda-1+\lambda-\lambda e^{-\lambda}+1-e^{\lambda}-\lambda e^{-\lambda}\right]
=
\lambda(1-e^{-\lambda}).
\]

In the rest of this section, we assume that the sample space $\mathcal{X}$ is a Polish space, i.e., it is separable and equipped with a complete metric function. To be precise, we assume that the space $\mathcal{X}$ has a countable dense subset, and we can measure the distance between two points in $\mathcal{X}$ using a complete metric. We take the Borel algebra generated by the open sets in $\mathcal{X}$ as the $\sigma$-algebra $\mathcal{F}$. This is a convenient and natural assumption in the study of total variation distance and optimal transport problems in general. A measurable space $(\mathcal{X},\mathcal{F})$ arising in this way is also called a \textit{standard Borel space}. It is worth noting that any discrete space and Euclidean space $\mathbb{R}^d$ are Polish. Hence, discrete random variables and continuous random variables can all be defined on Polish spaces.

It is interesting to construct coupling such that the probability of the event $X=Y$ is as large as possible. This is the diagonal event $\{(\omega,\omega): \omega\in \mathcal{X}\}$ in the product space $\mathcal{X}\times \mathcal{X}$. With the additional assumptions stated in the previous paragraph, we can guarantee that the diagonal event in the product space is measurable, so that the event $\{X=Y\}$ has well-defined probability. The coupling inequality below gives a lower bound on the extent of how much we can make $X$ equal to $Y$.
-/

lemma poisson_tail_sum (lam : NNReal) :
    ∑' n, ProbabilityTheory.poissonPMFReal lam (n + 2)
      = 1 - Real.exp (-(lam : ℝ)) - (lam : ℝ) * Real.exp (-(lam : ℝ)) := by
  have htail :
      HasSum (fun n => ProbabilityTheory.poissonPMFReal lam (n + 2))
        (1 - Finset.sum (Finset.range 2) (fun i => ProbabilityTheory.poissonPMFReal lam i)) := by
    exact (hasSum_nat_add_iff' 2).2 (ProbabilityTheory.poissonPMFRealSum lam)
  rw [htail.tsum_eq]
  have hsum_two :
      Finset.sum (Finset.range 2) (fun i => ProbabilityTheory.poissonPMFReal lam i)
        = ProbabilityTheory.poissonPMFReal lam 0 + ProbabilityTheory.poissonPMFReal lam 1 := by
    rw [Finset.sum_range_succ, Finset.sum_range_one]
  rw [hsum_two]
  simp [ProbabilityTheory.poissonPMFReal]
  ring

/-- Example 8.4.3: the TV distance between `Bernoulli(λ)` and `Poisson(λ)` equals
`λ (1 - e^{-λ})` for `0 ≤ λ ≤ 1`. -/
theorem ex_8_4_3 (lam : NNReal) (hlam : lam ≤ 1) :
    totalVariationDistance (bernoulliNatPMF lam hlam).toMeasure (ProbabilityTheory.poissonPMF lam).toMeasure
      = (lam : ℝ) * (1 - Real.exp (-(lam : ℝ))) := by
  let term : ℕ → ℝ := fun n =>
    |((bernoulliNatPMF lam hlam) n).toReal - ProbabilityTheory.poissonPMFReal lam n|
  have hsum_term : Summable term := by
    simpa [term, TVCore.pmfDiff, TVCore.pmfReal, poissonPMF_toReal] using
      (TVCore.summable_abs_pmfDiff (bernoulliNatPMF lam hlam) (ProbabilityTheory.poissonPMF lam))
  have hsplit : ∑' n, term n = (Finset.sum (Finset.range 2) term) + ∑' n, term (n + 2) := by
    simpa using (Summable.sum_add_tsum_nat_add 2 hsum_term).symm
  have hterm0 :
      term 0 = Real.exp (-(lam : ℝ)) + (lam : ℝ) - 1 := by
    have hineq : 1 - (lam : ℝ) ≤ Real.exp (-(lam : ℝ)) := Real.one_sub_le_exp_neg (lam : ℝ)
    have hnonpos : (1 - (lam : ℝ)) - Real.exp (-(lam : ℝ)) ≤ 0 := by
      linarith
    rw [show term 0 =
      |(1 - (lam : ℝ)) - ProbabilityTheory.poissonPMFReal lam 0| by
        simp [term, bernoulliNatPMF_zero, poissonPMF_toReal]]
    simp [ProbabilityTheory.poissonPMFReal, abs_of_nonpos hnonpos]
    ring
  have hlam_nonneg : 0 ≤ (lam : ℝ) := by exact_mod_cast lam.2
  have hExpLeOne : Real.exp (-(lam : ℝ)) ≤ 1 := by
    rw [Real.exp_le_one_iff]
    linarith
  have hterm1 :
      term 1 = (lam : ℝ) - (lam : ℝ) * Real.exp (-(lam : ℝ)) := by
    have hnonneg : 0 ≤ (lam : ℝ) - Real.exp (-(lam : ℝ)) * (lam : ℝ) := by
      nlinarith
    have hpoisson1 :
        ProbabilityTheory.poissonPMFReal lam 1 = Real.exp (-(lam : ℝ)) * (lam : ℝ) := by
      simp [ProbabilityTheory.poissonPMFReal, mul_comm, mul_left_comm, mul_assoc]
    rw [show term 1 = |(lam : ℝ) - ProbabilityTheory.poissonPMFReal lam 1| by
      simp [term, bernoulliNatPMF_one]]
    rw [hpoisson1]
    rw [abs_of_nonneg hnonneg]
    ring
  have htail_term :
      ∀ n, term (n + 2) = ProbabilityTheory.poissonPMFReal lam (n + 2) := by
    intro n
    have hbern : ((bernoulliNatPMF lam hlam) (n + 2)).toReal = 0 :=
      bernoulliNatPMF_ge_two lam hlam (by omega)
    have hnonneg : 0 ≤ ProbabilityTheory.poissonPMFReal lam (n + 2) :=
      ProbabilityTheory.poissonPMFReal_nonneg
    change
      |((bernoulliNatPMF lam hlam) (n + 2)).toReal - ProbabilityTheory.poissonPMFReal lam (n + 2)|
        = ProbabilityTheory.poissonPMFReal lam (n + 2)
    rw [hbern]
    simpa [sub_eq_add_neg, zero_add, abs_neg] using
      (abs_of_nonneg hnonneg : |ProbabilityTheory.poissonPMFReal lam (n + 2)| =
        ProbabilityTheory.poissonPMFReal lam (n + 2))
  have hsum_two : Finset.sum (Finset.range 2) term = term 0 + term 1 := by
    rw [Finset.sum_range_succ, Finset.sum_range_one]
  calc
    totalVariationDistance (bernoulliNatPMF lam hlam).toMeasure (ProbabilityTheory.poissonPMF lam).toMeasure
        = (1 / 2 : ℝ) * ∑' n, term n := by
            simpa [term, poissonPMF_toReal] using
              (thm_8_6_discrete_pmf (bernoulliNatPMF lam hlam) (ProbabilityTheory.poissonPMF lam))
    _ = (1 / 2 : ℝ) * (Finset.sum (Finset.range 2) term + (∑' n, term (n + 2))) := by
            rw [hsplit]
    _ = (1 / 2 : ℝ) *
          (term 0 + term 1 + (∑' n, ProbabilityTheory.poissonPMFReal lam (n + 2))) := by
            congr 1
            rw [hsum_two]
            rw [tsum_congr htail_term]
    _ = (1 / 2 : ℝ) *
          ((Real.exp (-(lam : ℝ)) + (lam : ℝ) - 1)
            + ((lam : ℝ) - (lam : ℝ) * Real.exp (-(lam : ℝ)))
            + (1 - Real.exp (-(lam : ℝ)) - (lam : ℝ) * Real.exp (-(lam : ℝ)))) := by
            rw [hterm0, hterm1, poisson_tail_sum]
    _ = (lam : ℝ) * (1 - Real.exp (-(lam : ℝ))) := by
            ring
