import Mathlib

/-
TASK ID: ex_8_3_3
TYPE: Example_Proof
SOURCE PLAN: 33_chap8_monge_kantorovich
TASK CONTENT:
\textbf{Example 8.3.3 (Nonexistence of Solution in Monge's Problem)} \\
Monge's problem may fail to have a solution, because it is not allowed to split any mass. Consider the measures $\mu$ and $\nu$ given by $\mu=2\delta_{x_1}$ and $\nu=\delta_{y_1}+\delta_{y_2}$, where $x_1$, $y_1$, and $y_2$ are distinct real numbers. The measure $\mu$ represents two units of sand at position $x_1$, and we want to move the sand to positions $y_1$ and $y_2$. Suppose that the three points $x_1$, $y_1$, and $t_2$ are distinct. There is no transport map $T$ such that $T_{\#}\mu=\nu$, because any transport map must move both units of sand from $x_1$ to either $y_1$ or $y_2$, which violates the constraint that we cannot split the mass. Therefore, Monge's problem does not have a solution in this case.

Kantorovich's problem can be seen as a relaxation of Monge's problem by allowing the splitting of mass. One of the advantages of the Kantorovich problem is that it guarantees the existence of feasible solution, even when Monge's problem does not have a solution. Moreover, in finite sample spaces, the optimal solution can be found efficiently using linear programming.

The Kantorovich version of the transport problem differs from Monge's problem in that it deals with transport plan rather than transport map. To illustrate this, we consider an example borrowed from Villani [9]. There are $m$ bread bakeries in a city that produce bread and $n$ restaurants that demand bread on a daily basis. The amount of bread produced by each bakery and the demand of each restaurant are known in advance. The optimization problem is to minimize the total transport cost of bread from the bakeries to the restaurants.

In contrast to Monge's problem, the output of a bakery can be sent to different restaurants. This is possible because the unit of bread is assumed to be infinitely divisible. The problem can be interpreted as finding the optimal coupling of the production measure (which describes the amount of bread produced by each bakery) and the demand measure (which describes the amount of bread demanded by each restaurant).

Before we formally state the Kantorovich problem, we first define some relevant concepts. For simplicity, let $\mathcal{X}$ and $\mathcal{Y}$ be metric spaces, and let $\mathcal{B}(\mathcal{X}\times \mathcal{Y})$ be the Borel algebra that is generated by the open sets in the form $A\times B$, where $A$ and $B$ are open sets in $\mathcal{X}$ and $\mathcal{Y}$, respectively. We define the projection function $\pi_1$ from $\mathcal{X}\times \mathcal{Y}$ to $\mathcal{X}$ by $\pi_1(x,y)=x$ and the projection to $\mathcal{Y}$ by $\pi_2(x,y)=y$. The \textit{marginals} of a probability measure $\mu$ on $\mathcal{X}\times \mathcal{Y}$ are the image measures $(\pi_1)_{\#}\mu$ and $(\pi_2)_{\#}\mu$, which are probability measures on $\mathcal{X}$ and $\mathcal{Y}$, respectively. A \textit{transport plan} between two probability measures $P$ and $Q$ defined on $\mathcal{X}$ and $\mathcal{Y}$, respectively, is a probability measure on $\mathcal{X}\times \mathcal{Y}$ with marginals $P$ and $Q$.

Let $\mathcal{PM}(\mathcal{X}\times \mathcal{Y})$ denote the set of all probability measures on the measurable space $(\mathcal{X}\times \mathcal{Y},\mathcal{B}(\mathcal{X}\times \mathcal{Y}))$. Given a cost function $c(x,y):\mathcal{X}\times \mathcal{Y}\to \bar{\mathbb{R}}_{\ge 0}$, the Kantorovich problem is to find a transport plan $\mu$ in
\[
\Pi(P,Q)\triangleq \{\mu\in \mathcal{PM}(\mathcal{X}\times \mathcal{Y}) : (\pi_1)_{\#}\mu=P,\ (\pi_2)_{\#}\nu=Q\},
\]
which minimizes
\begin{equation}
E[c(X,Y)] = \int_{\mathcal{X}\times \mathcal{Y}} c(x,y)\, d\mu(x,y).
\tag{8.2}
\end{equation}

An optimal transport plan $\mu^{*}$ is a transport plan that solves the Kantorovich problem with the minimum cost.

The spaces $\mathcal{X}$ and $\mathcal{Y}$ in this optimization problem can be finite sets or closed intervals in $\mathbb{R}$. We give a discrete example below.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory Set
open scoped ENNReal

noncomputable section

/-- Example 8.3.3: a transport map cannot split the two units of mass concentrated at one source
point into two distinct target atoms. -/
theorem ex_8_3_3 (x₁ y₁ y₂ : ℝ) (hy : y₁ ≠ y₂) :
    ¬ ∃ T : ℝ → ℝ, Measurable T ∧
      Measure.map T ((2 : ℝ≥0∞) • Measure.dirac x₁) = Measure.dirac y₁ + Measure.dirac y₂ := by
  intro h
  rcases h with ⟨T, hT, hmap⟩
  have hy1 : MeasurableSet ({y₁} : Set ℝ) := measurableSet_singleton y₁
  have h_rhs : (Measure.dirac y₁ + Measure.dirac y₂) {y₁} = 1 := by
    simp [Measure.add_apply, hy1, hy]
  by_cases hTy : T x₁ = y₁
  · have h_lhs :
        Measure.map T ((2 : ℝ≥0∞) • Measure.dirac x₁) {y₁} = 2 := by
      rw [Measure.map_apply hT hy1, Measure.smul_apply]
      simp [Set.mem_preimage, hTy]
    have : (2 : ℝ≥0∞) = 1 := by
      calc
        (2 : ℝ≥0∞) = Measure.map T ((2 : ℝ≥0∞) • Measure.dirac x₁) {y₁} := h_lhs.symm
        _ = (Measure.dirac y₁ + Measure.dirac y₂) {y₁} := by rw [hmap]
        _ = 1 := h_rhs
    norm_num at this
  · have h_lhs :
        Measure.map T ((2 : ℝ≥0∞) • Measure.dirac x₁) {y₁} = 0 := by
      rw [Measure.map_apply hT hy1, Measure.smul_apply]
      simp [Set.mem_preimage, hTy]
    have : (0 : ℝ≥0∞) = 1 := by
      calc
        (0 : ℝ≥0∞) = Measure.map T ((2 : ℝ≥0∞) • Measure.dirac x₁) {y₁} := h_lhs.symm
        _ = (Measure.dirac y₁ + Measure.dirac y₂) {y₁} := by rw [hmap]
        _ = 1 := h_rhs
    norm_num at this
