import Mathlib
import ToyApollo.Output.thm_13_16

/-
TASK ID: prob_13_11
TYPE: Problem
SOURCE PLAN: chapter13-problems
TASK CONTENT:
\textbf{13.11.} (Polya's Urn Model)Consider an urn containing b black balls and w white

balls at time 0. At time i (for i \in N), we pick a ball uniformly at random from the

urn. If the color of the ball is black, we put two black balls back to the urn. If the

color is white, we put two white balls back. There are b +w+i balls in the urn after

step i Let Bi denote the number of black balls in the urn after step i :

(a) Compute the probabilities P(B 1 =b) and P(B 1 = b + 1).

(b) Let \mathcal{F}i be the \sigma -algebra generated by B 0,B 1,...,B i ,f o r i \geq 1. Let Z i =

Bi/(b + w+ i) be the fraction of black balls in the urn after the i -th step. Show

that (Z i)i\geq 0 is a martingale relative to the filtration (\mathcal{F}i)i\geq 0. (We define B 0 = b,

Z0 = b/(b + w), and \mathcal{F}0 ={ \emptyset,\Omega}.)

(c) Compute E [Zi] for i \geq 1.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open scoped ProbabilityTheory

noncomputable section

/-- Part (a): after the first draw, the number of black balls is still `b`
exactly when the first draw is white, and is `b + 1` exactly when the first
draw is black. -/
theorem prob_13_11_first_step_probabilities
    {b w total pStay pIncrease : ℝ}
    (htotal : total = b + w)
    (hStay : pStay = w / total)
    (hIncrease : pIncrease = b / total) :
    pStay = w / (b + w) ∧ pIncrease = b / (b + w) := by
  subst total
  exact ⟨hStay, hIncrease⟩

/-- The one-step algebra behind the martingale property.  If the current urn
has `B` black balls among `N` total balls, then the conditional expectation of
the next black fraction is the current black fraction. -/
theorem prob_13_11_polya_step_martingale
    {B N : ℝ} (hN : N ≠ 0) (hN1 : N + 1 ≠ 0) :
    (B / N) * ((B + 1) / (N + 1)) +
        (1 - B / N) * (B / (N + 1)) =
      B / N := by
  field_simp [hN, hN1]
  ring

/-- A named form of the black-ball fraction `Z_i = B_i / (b + w + i)`. -/
def prob_13_11_blackFraction (b w : ℝ) (B : ℕ → ℝ) (i : ℕ) : ℝ :=
  B i / (b + w + i)

/-- The source-facing black-fraction process. At time zero the textbook fixes
`B_0 = b`, so the process starts from the constant fraction `b/(b+w)`;
positive times use the random black count after that draw. -/
def prob_13_11_blackFractionProcess {Ω : Type*}
    (b w : ℝ) (B : ℕ → Ω → ℝ) : ℕ → Ω → ℝ
  | 0 => fun _ => b / (b + w)
  | n + 1 => fun ω => B (n + 1) ω / (b + w + (n + 1 : ℕ))

/-- Projection from a longer zero-indexed history to an earlier one. -/
def prob_13_11_historyProjection {n m : ℕ} (h : n ≤ m) :
    (Fin (m + 1) → ℝ) → (Fin (n + 1) → ℝ) :=
  fun v k => v (Fin.castLE (Nat.succ_le_succ h) k)

theorem prob_13_11_historyProjection_measurable {n m : ℕ} (h : n ≤ m) :
    Measurable (prob_13_11_historyProjection h) := by
  exact measurable_pi_lambda _ fun k =>
    measurable_pi_apply (Fin.castLE (Nat.succ_le_succ h) k)

theorem prob_13_11_historyProjection_comp {Ω : Type*}
    (B : ℕ → Ω → ℝ) {n m : ℕ} (h : n ≤ m) :
    def_13_7_history B n =
      prob_13_11_historyProjection h ∘ def_13_7_history B m := by
  funext ω k
  simp [def_13_7_history, prob_13_11_historyProjection]

/-- The filtration used by the Polya urn proof. Time zero is the trivial
sigma-field fixed by the source; positive times are generated by
`B_0,...,B_i`. -/
@[reducible]
def prob_13_11_historyFiltration {Ω : Type*}
    (B : ℕ → Ω → ℝ) : ℕ → MeasurableSpace Ω
  | 0 => ⊥
  | n + 1 => def_13_7_historySigma B (n + 1)

theorem prob_13_11_history_measurable_self {Ω : Type*}
    (B : ℕ → Ω → ℝ) (n : ℕ) :
    @Measurable Ω (Fin (n + 1) → ℝ)
      (def_13_7_historySigma B n) _ (def_13_7_history B n) :=
  Measurable.of_comap_le le_rfl

theorem prob_13_11_history_measurable_of_le {Ω : Type*}
    (B : ℕ → Ω → ℝ) {n m : ℕ} (h : n ≤ m) :
    @Measurable Ω (Fin (n + 1) → ℝ)
      (def_13_7_historySigma B m) _ (def_13_7_history B n) := by
  have hself := prob_13_11_history_measurable_self B m
  have hproj := prob_13_11_historyProjection_measurable h
  have hcomp :
      @Measurable Ω (Fin (n + 1) → ℝ)
        (def_13_7_historySigma B m) _
        (prob_13_11_historyProjection h ∘ def_13_7_history B m) :=
    hproj.comp hself
  simpa [prob_13_11_historyProjection_comp B h] using hcomp

theorem prob_13_11_historyFiltration_mono {Ω : Type*}
    (B : ℕ → Ω → ℝ) {n m : ℕ} (h : n ≤ m) :
    prob_13_11_historyFiltration B n ≤
      prob_13_11_historyFiltration B m := by
  cases n with
  | zero =>
      exact bot_le
  | succ n =>
      cases m with
      | zero =>
          cases Nat.not_succ_le_zero n h
      | succ m =>
          exact (prob_13_11_history_measurable_of_le B h).comap_le

theorem prob_13_11_historyFiltration_sub_ambient {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] (B : ℕ → Ω → ℝ)
    (hB : ∀ n : ℕ, @Measurable Ω ℝ 𝓕 _ (B n)) (n : ℕ) :
    prob_13_11_historyFiltration B n ≤ 𝓕 := by
  cases n with
  | zero =>
      exact bot_le
  | succ n =>
      have hhist :
          @Measurable Ω (Fin (n + 2) → ℝ) 𝓕 _
            (def_13_7_history B (n + 1)) := by
        exact measurable_pi_lambda _ fun k => hB k.1
      exact hhist.comap_le

/-- Source-facing assumptions for the concrete Polya urn process.  `D (n+1)`
is the black-draw increment at step `n+1`; the urn update and conditional mean
of this increment are the source transition law from which the martingale
condition is proved below. -/
structure Prob1311PolyaUrnModel {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (P : Measure Ω) (b w : ℝ) (B D : ℕ → Ω → ℝ) where
  initial_black_count : B 0 = fun _ => b
  black_count_measurable : ∀ n : ℕ, @Measurable Ω ℝ 𝓕 _ (B n)
  black_count_integrable : ∀ n : ℕ, Integrable (B n) P
  draw_integrable : ∀ n : ℕ, Integrable (D (n + 1)) P
  total_ne_zero : ∀ n : ℕ, b + w + (n : ℝ) ≠ 0
  next_total_ne_zero : ∀ n : ℕ, b + w + (n : ℝ) + 1 ≠ 0
  black_count_update :
    ∀ n : ℕ, B (n + 1) =ᵐ[P] fun ω => B n ω + D (n + 1) ω
  draw_conditional_mean :
    ∀ n : ℕ,
      P[D (n + 1) |
          prob_13_11_historyFiltration B n] =ᵐ[P]
        fun ω => B n ω / (b + w + (n : ℝ))

/-- The generated urn history is a filtration. -/
theorem prob_13_11_history_filtration {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {b w : ℝ} {B D : ℕ → Ω → ℝ}
    (M : Prob1311PolyaUrnModel P b w B D) :
    def_13_6_isFiltration (𝓕 := 𝓕) (prob_13_11_historyFiltration B) :=
  ⟨prob_13_11_historyFiltration_sub_ambient B M.black_count_measurable,
    fun _ _ hnm => prob_13_11_historyFiltration_mono B hnm⟩

/-- The black-fraction process is adapted to the generated urn history. -/
theorem prob_13_11_fraction_adapted {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (b w : ℝ) (B : ℕ → Ω → ℝ) :
    def_13_6_adapted (prob_13_11_historyFiltration B)
      (prob_13_11_blackFractionProcess b w B) := by
  intro n
  cases n with
  | zero =>
      simp [prob_13_11_blackFractionProcess, prob_13_11_historyFiltration]
  | succ n =>
      let k : Fin (n + 2) := ⟨n + 1, Nat.lt_succ_self (n + 1)⟩
      let g : (Fin (n + 2) → ℝ) → ℝ :=
        fun z => z k / (b + w + (n + 1 : ℕ))
      have hg : Measurable g := by
        change Measurable
          (fun z : Fin (n + 2) → ℝ => z k / (b + w + (n + 1 : ℕ)))
        exact (measurable_pi_apply k).div_const _
      have hhist :
          Measurable[prob_13_11_historyFiltration B (n + 1)]
            (def_13_7_history B (n + 1)) :=
        prob_13_11_history_measurable_self B (n + 1)
      have hcomp :
          Measurable[prob_13_11_historyFiltration B (n + 1)]
            (g ∘ def_13_7_history B (n + 1)) :=
        hg.comp hhist
      simpa [prob_13_11_blackFractionProcess, def_13_7_history, g, k]
        using hcomp

/-- Each black-count coordinate is measurable with respect to the generated
urn history up to that time. -/
theorem prob_13_11_black_count_history_measurable {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] {b : ℝ} {B : ℕ → Ω → ℝ}
    (hB0 : B 0 = fun _ => b) (n : ℕ) :
    Measurable[prob_13_11_historyFiltration B n] (B n) := by
  cases n with
  | zero =>
      rw [hB0]
      exact measurable_const
  | succ n =>
      let k : Fin (n + 2) := ⟨n + 1, Nat.lt_succ_self (n + 1)⟩
      have hhist :
          Measurable[prob_13_11_historyFiltration B (n + 1)]
            (def_13_7_history B (n + 1)) :=
        prob_13_11_history_measurable_self B (n + 1)
      have hcoord :
          Measurable[prob_13_11_historyFiltration B (n + 1)]
            ((fun z : Fin (n + 2) → ℝ => z k) ∘
              def_13_7_history B (n + 1)) :=
        (measurable_pi_apply k).comp hhist
      simpa [prob_13_11_historyFiltration, def_13_7_history, k] using hcoord

/-- The black-fraction process is integrable once the black-count coordinates
are integrable. -/
theorem prob_13_11_fraction_integrable {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsFiniteMeasure P] {b w : ℝ}
    {B D : ℕ → Ω → ℝ}
    (M : Prob1311PolyaUrnModel P b w B D) :
    ∀ n : ℕ, Integrable (prob_13_11_blackFractionProcess b w B n) P := by
  intro n
  cases n with
  | zero =>
      simp [prob_13_11_blackFractionProcess]
  | succ n =>
      simpa [prob_13_11_blackFractionProcess] using
        (M.black_count_integrable (n + 1)).div_const
          (b + w + (n + 1 : ℕ))

/-- Conditional-expectation algebra for one Polya urn update. -/
theorem prob_13_11_condExp_update_to_fraction {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] {P : Measure Ω} {𝓖 : MeasurableSpace Ω}
    (h𝓖 : 𝓖 ≤ 𝓕) [SigmaFinite (P.trim h𝓖)]
    {B D : Ω → ℝ} {N : ℝ}
    (hN : N ≠ 0) (hN1 : N + 1 ≠ 0)
    (hBsm : StronglyMeasurable[𝓖] B)
    (hBi : Integrable B P) (hDi : Integrable D P)
    (hDce : P[D | 𝓖] =ᵐ[P] fun ω => B ω / N) :
    P[fun ω => (B ω + D ω) / (N + 1) | 𝓖] =ᵐ[P]
      fun ω => B ω / N := by
  have hsum :
      P[B + D | 𝓖] =ᵐ[P] fun ω => B ω + B ω / N := by
    have hBce : P[B | 𝓖] =ᵐ[P] B := by
      exact Filter.EventuallyEq.of_eq
        (condExp_of_stronglyMeasurable h𝓖 hBsm hBi)
    calc
      P[B + D | 𝓖] =ᵐ[P] P[B | 𝓖] + P[D | 𝓖] := condExp_add hBi hDi 𝓖
      _ =ᵐ[P] B + fun ω => B ω / N := hBce.add hDce
      _ =ᵐ[P] fun ω => B ω + B ω / N := Filter.EventuallyEq.rfl
  have hscaled :
      P[(fun ω => (1 / (N + 1) : ℝ) • (B + D) ω) | 𝓖] =ᵐ[P]
        fun ω => (1 / (N + 1) : ℝ) • (B ω + B ω / N) := by
    calc
      P[(fun ω => (1 / (N + 1) : ℝ) • (B + D) ω) | 𝓖]
          =ᵐ[P] (1 / (N + 1) : ℝ) • P[B + D | 𝓖] :=
        condExp_smul (1 / (N + 1) : ℝ) (B + D) 𝓖
      _ =ᵐ[P] fun ω => (1 / (N + 1) : ℝ) • (B ω + B ω / N) := by
        filter_upwards [hsum] with ω hω
        simp [hω]
  have hcongr :
      P[fun ω => (B ω + D ω) / (N + 1) | 𝓖] =ᵐ[P]
        P[(fun ω => (1 / (N + 1) : ℝ) • (B + D) ω) | 𝓖] := by
    apply condExp_congr_ae
    filter_upwards with ω
    simp [div_eq_mul_inv, mul_comm]
  exact hcongr.trans <| hscaled.trans <| by
    filter_upwards with ω
    simp [smul_eq_mul]
    field_simp [hN, hN1]

/-- The Polya urn update and draw conditional mean imply Definition 13.7's
one-step martingale condition for the black-fraction process. -/
theorem prob_13_11_urn_oneStep {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsFiniteMeasure P] {b w : ℝ}
    {B D : ℕ → Ω → ℝ}
    (M : Prob1311PolyaUrnModel P b w B D) :
    def_13_7_oneStepCondition P (prob_13_11_historyFiltration B)
      (prob_13_11_blackFractionProcess b w B) := by
  intro n
  let N : ℝ := b + w + (n : ℝ)
  have h𝓖 : prob_13_11_historyFiltration B n ≤ 𝓕 :=
    prob_13_11_historyFiltration_sub_ambient B M.black_count_measurable n
  have hBsm : StronglyMeasurable[prob_13_11_historyFiltration B n] (B n) :=
    (prob_13_11_black_count_history_measurable M.initial_black_count n).stronglyMeasurable
  have hupdate :
      prob_13_11_blackFractionProcess b w B (n + 1) =ᵐ[P]
        fun ω => (B n ω + D (n + 1) ω) / (N + 1) := by
    filter_upwards [M.black_count_update n] with ω hω
    simp [prob_13_11_blackFractionProcess, N, hω, Nat.cast_add,
      Nat.cast_one, add_assoc]
  have hce_update :
      P[prob_13_11_blackFractionProcess b w B (n + 1) |
          prob_13_11_historyFiltration B n] =ᵐ[P]
        P[fun ω => (B n ω + D (n + 1) ω) / (N + 1) |
          prob_13_11_historyFiltration B n] :=
    condExp_congr_ae hupdate
  have hdraw :
      P[D (n + 1) | prob_13_11_historyFiltration B n] =ᵐ[P]
        fun ω => B n ω / N := by
    simpa [N] using M.draw_conditional_mean n
  have halg :
      P[fun ω => (B n ω + D (n + 1) ω) / (N + 1) |
          prob_13_11_historyFiltration B n] =ᵐ[P]
        fun ω => B n ω / N :=
    prob_13_11_condExp_update_to_fraction h𝓖 (M.total_ne_zero n)
      (M.next_total_ne_zero n) hBsm (M.black_count_integrable n)
      (M.draw_integrable n) hdraw
  have hcurrent :
      (fun ω => B n ω / N) =ᵐ[P]
        prob_13_11_blackFractionProcess b w B n := by
    cases n with
    | zero =>
        refine Filter.Eventually.of_forall ?_
        intro ω
        simp [prob_13_11_blackFractionProcess, N, M.initial_black_count]
    | succ n =>
        refine Filter.Eventually.of_forall ?_
        intro ω
        simp [prob_13_11_blackFractionProcess, N, Nat.cast_add,
          Nat.cast_one, add_assoc]
  exact hce_update.trans (halg.trans hcurrent)

/-- Part (b): the concrete black-fraction process is a martingale relative to
the filtration generated by the urn history. -/
theorem prob_13_11_fraction_martingale {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] {P : Measure Ω} [IsFiniteMeasure P] {b w : ℝ}
    {B D : ℕ → Ω → ℝ}
    (M : Prob1311PolyaUrnModel P b w B D) :
    def_13_7 P (prob_13_11_historyFiltration B)
      (prob_13_11_blackFractionProcess b w B) :=
  ⟨prob_13_11_history_filtration M, prob_13_11_fraction_integrable M,
    prob_13_11_fraction_adapted b w B,
    prob_13_11_urn_oneStep M⟩

/-- The source initial value `Z_0 = b/(b+w)` gives the corresponding initial
expectation on a probability space. -/
theorem prob_13_11_initial_expectation {Ω : Type*} [MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {b w : ℝ}
    {B : ℕ → Ω → ℝ} :
    ∫ ω, prob_13_11_blackFractionProcess b w B 0 ω ∂P = b / (b + w) := by
  simp [prob_13_11_blackFractionProcess]

/-- Part (c): once part (b) has established that `Z` is a martingale, Theorem
13.16 gives constant expectations, so `E[Z_i] = b / (b + w)`. -/
theorem prob_13_11_expected_fraction {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {b w : ℝ}
    {B D : ℕ → Ω → ℝ}
    (M : Prob1311PolyaUrnModel P b w B D)
    (hSigmaFinite :
      ∀ n : ℕ,
        SigmaFinite (P.trim
          ((def_13_7_isFiltration (prob_13_11_fraction_martingale M)).1 n)))
    (i : ℕ) (hi : 1 ≤ i) :
    ∫ ω, prob_13_11_blackFractionProcess b w B i ω ∂P = b / (b + w) := by
  rw [thm_13_16 (prob_13_11_fraction_martingale M) hSigmaFinite i hi,
    prob_13_11_initial_expectation]

/-- Problem 13.11, bundled as the first-step probabilities, the martingale
one-step algebra for the Polya fraction, and the resulting expected fraction. -/
theorem prob_13_11 :
    (∀ {b w total pStay pIncrease : ℝ},
      total = b + w →
      pStay = w / total →
      pIncrease = b / total →
      pStay = w / (b + w) ∧ pIncrease = b / (b + w)) ∧
    (∀ {B N : ℝ}, N ≠ 0 → N + 1 ≠ 0 →
      (B / N) * ((B + 1) / (N + 1)) +
          (1 - B / N) * (B / (N + 1)) =
        B / N) ∧
    (∀ {Ω : Type*} [𝓕 : MeasurableSpace Ω]
      {P : Measure Ω} [IsFiniteMeasure P] {b w : ℝ} {B D : ℕ → Ω → ℝ},
      Prob1311PolyaUrnModel P b w B D →
      def_13_7 P (prob_13_11_historyFiltration B)
        (prob_13_11_blackFractionProcess b w B)) ∧
    (∀ {Ω : Type*} [𝓕 : MeasurableSpace Ω]
      {P : Measure Ω} [IsProbabilityMeasure P] {b w : ℝ}
      {B D : ℕ → Ω → ℝ}
      (M : Prob1311PolyaUrnModel P b w B D),
      (∀ n : ℕ, SigmaFinite (P.trim
        ((def_13_7_isFiltration (prob_13_11_fraction_martingale M)).1 n))) →
      ∀ i : ℕ, 1 ≤ i →
        ∫ ω, prob_13_11_blackFractionProcess b w B i ω ∂P =
          b / (b + w)) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro b w total pStay pIncrease htotal hStay hIncrease
    exact prob_13_11_first_step_probabilities htotal hStay hIncrease
  · intro B N hN hN1
    exact prob_13_11_polya_step_martingale hN hN1
  · intro Ω 𝓕 P _ b w B D M
    exact prob_13_11_fraction_martingale M
  · intro Ω 𝓕 P _ b w B D M hSigmaFinite i hi
    exact prob_13_11_expected_fraction M hSigmaFinite i hi

