import Mathlib
import ToyApollo.Output.def_13_2
import ToyApollo.Output.thm_13_11
import ToyApollo.Output.thm_13_4

/-!
Support layer for Theorem 13.12.

This file contains the countable-partition conditional-expectation
construction and atomwise integral verification used by the source-facing
parent theorem `thm_13_12`.
-/

open MeasureTheory Filter
open scoped ENNReal

noncomputable section

/-- A countable partition of the sample space by atoms `A_i`. -/
def thm_13_12_countablePartition {Ω : Type*} (A : ℕ → Set Ω) : Prop :=
  (∀ ω : Ω, ∃ i : ℕ, ω ∈ A i) ∧
    Pairwise fun i j : ℕ => Disjoint (A i) (A j)

/-- The statement that the sigma-field `𝓖` is generated by the countable
partition atoms. -/
def thm_13_12_generatedByPartition {Ω : Type*}
    (𝓖 : SigmaField Ω) (A : ℕ → Set Ω) : Prop :=
  𝓖 = MeasurableSpace.generateFrom (Set.range A)

/-- Every partition atom is measurable in the sigma-field generated by the
atoms. -/
theorem thm_13_12_atom_measurableIn_generated {Ω : Type*}
    {𝓖 : SigmaField Ω} {A : ℕ → Set Ω}
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A) (i : ℕ) :
    IsMeasurableIn 𝓖 (A i) := by
  rw [hGenerated]
  exact MeasurableSpace.measurableSet_generateFrom
    (show A i ∈ Set.range A by exact ⟨i, rfl⟩)

/-- Since `𝓖` is a sub-sigma-field of the ambient sigma-field, every generated
partition atom is ambient-measurable. -/
theorem thm_13_12_atom_measurable_ambient {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] {𝓖 : SigmaField Ω}
    (h𝓖 : IsSubSigmaField 𝓖 𝓕) {A : ℕ → Set Ω}
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A) (i : ℕ) :
    @MeasurableSet Ω 𝓕 (A i) :=
  h𝓖 (thm_13_12_atom_measurableIn_generated hGenerated i)

/-- Every set in the sigma-field generated by a countable partition is
saturated with respect to the partition atoms: each atom is either contained in
the set or disjoint from it. -/
theorem thm_13_12_generated_set_atom_saturated {Ω : Type*}
    {𝓖 : SigmaField Ω} {A : ℕ → Set Ω}
    (hPartition : thm_13_12_countablePartition A)
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A)
    {B : Set Ω} (hB : IsMeasurableIn 𝓖 B) :
    ∀ i : ℕ, A i ⊆ B ∨ Disjoint (A i) B := by
  classical
  let mSat : MeasurableSpace Ω :=
    { MeasurableSet' := fun C : Set Ω =>
        ∀ i : ℕ, A i ⊆ C ∨ Disjoint (A i) C
      measurableSet_empty := by
        intro i
        exact Or.inr (Set.disjoint_left.mpr (fun _ _ h => h))
      measurableSet_compl := by
        intro C hC i
        rcases hC i with hsub | hdis
        · exact Or.inr (Set.disjoint_left.mpr (fun _ hA hC => hC (hsub hA)))
        · exact Or.inl (fun ω hω hωC => (Set.disjoint_left.mp hdis hω hωC).elim)
      measurableSet_iUnion := by
        intro C hC i
        by_cases hex : ∃ n : ℕ, A i ⊆ C n
        · rcases hex with ⟨n, hn⟩
          exact Or.inl (fun ω hω => Set.mem_iUnion.mpr ⟨n, hn hω⟩)
        · exact Or.inr (by
            exact Set.disjoint_left.mpr (fun ω hωA hωU => by
              rcases Set.mem_iUnion.mp hωU with ⟨n, hωCn⟩
              rcases hC n i with hsub | hdis
              · exact (hex ⟨n, hsub⟩).elim
              · exact (Set.disjoint_left.mp hdis hωA hωCn).elim)) }
  have hle : MeasurableSpace.generateFrom (Set.range A) ≤ mSat := by
    apply MeasurableSpace.generateFrom_le
    intro C hC
    rcases hC with ⟨j, rfl⟩
    intro i
    by_cases hij : i = j
    · subst hij
      exact Or.inl subset_rfl
    · exact Or.inr (hPartition.2 hij)
  have hBgen : @MeasurableSet Ω (MeasurableSpace.generateFrom (Set.range A)) B := by
    rw [hGenerated] at hB
    exact hB
  exact hle B hBgen

/-- The guarded scalar `E[X | A_i]` used in the countable atom formula.  The
guard is internal: under the theorem hypotheses atoms are measurable and finite,
and null atoms use the same harmless zero representative as Definition 13.2. -/
noncomputable def thm_13_12_atomConditionalExpectation
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsFiniteMeasure P]
    (A : ℕ → Set Ω) (X : Ω → ℝ) (i : ℕ) : ℝ := by
  classical
  exact
    if hA : MeasurableSet (A i) then
      def_13_2_atomConditionalExpectation P A X i hA (measure_ne_top P (A i))
    else
      0

theorem thm_13_12_atomConditionalExpectation_of_null
    {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsFiniteMeasure P]
    {A : ℕ → Set Ω} (X : Ω → ℝ) {i : ℕ}
    (hAi : MeasurableSet (A i)) (hA0 : P (A i) = 0) :
    thm_13_12_atomConditionalExpectation P A X i = 0 := by
  unfold thm_13_12_atomConditionalExpectation
  simp [hAi, def_13_2_atomConditionalExpectation, hA0]

theorem thm_13_12_atomConditionalExpectation_of_wellDefined
    {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsFiniteMeasure P]
    {A : ℕ → Set Ω} (X : Ω → ℝ) {i : ℕ}
    (hAi : MeasurableSet (A i)) (hA0 : P (A i) ≠ 0) :
    thm_13_12_atomConditionalExpectation P A X i =
      def_13_1 P (A i) hAi hA0 (measure_ne_top P (A i)) X := by
  unfold thm_13_12_atomConditionalExpectation
  simp [hAi, def_13_2_atomConditionalExpectation, hA0]

/-- Local normalized-integral form of Definition 13.1, used only to assemble
the atom-level integral calculation for Theorem 13.12. -/
theorem thm_13_12_def_13_1_simple_formula {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : Set Ω) (hA : MeasurableSet A)
    (hA0 : P A ≠ 0) (hA_top : P A ≠ ⊤) (X : Ω → ℝ) :
    def_13_1 P A hA hA0 hA_top X = (∫ ω in A, X ω ∂P) / (P A).toReal := by
  unfold def_13_1 def_13_1_conditionalEventExpectation def_13_1_conditionalMeasure
  rw [integral_smul_measure]
  simp [smul_eq_mul, one_div, div_eq_inv_mul]

/-- The `i`-th countable atom term `E[X|A_i] 1_{A_i}`. -/
noncomputable def thm_13_12_atomTerm
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsFiniteMeasure P]
    (A : ℕ → Set Ω) (X : Ω → ℝ) (i : ℕ) : Ω → ℝ :=
  (A i).indicator
    (fun _ => thm_13_12_atomConditionalExpectation P A X i)

/-- Each atom summand is measurable with respect to the sigma-field generated
by the partition. -/
theorem thm_13_12_atomTerm_gmeasurable {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsFiniteMeasure P] {𝓖 : SigmaField Ω}
    {A : ℕ → Set Ω} {X : Ω → ℝ}
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A) (i : ℕ) :
    GMeasurable 𝓖 (@thm_13_12_atomTerm Ω 𝓕 P _ A X i) := by
  exact measurable_const.indicator
    (thm_13_12_atom_measurableIn_generated hGenerated i)

/-- Finite partial sums of the atom formula are `𝓖`-measurable. -/
theorem thm_13_12_partialSum_gmeasurable {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsFiniteMeasure P] {𝓖 : SigmaField Ω}
    {A : ℕ → Set Ω} {X : Ω → ℝ}
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A) (n : ℕ) :
    GMeasurable 𝓖
      (fun ω : Ω => ∑ i ∈ Finset.range n,
        @thm_13_12_atomTerm Ω 𝓕 P _ A X i ω) := by
  classical
  induction n with
  | zero =>
      simpa using (measurable_zero : Measurable[𝓖] (fun _ω : Ω => (0 : ℝ)))
  | succ n ih =>
      simpa [Finset.sum_range_succ] using
        ih.add (@thm_13_12_atomTerm_gmeasurable Ω 𝓕 P _ 𝓖 A X hGenerated n)

/-- The countable-partition formula `∑ᵢ E[X|A_i] 1_{A_i}`. -/
noncomputable def thm_13_12_countablePartitionConditionalExpectation
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsFiniteMeasure P]
    (A : ℕ → Set Ω) (X : Ω → ℝ) : Ω → ℝ :=
  fun ω => ∑' i : ℕ, thm_13_12_atomTerm P A X i ω

/-- The countable-partition formula is measurable with respect to the
sigma-field generated by the partition atoms. -/
theorem thm_13_12_countablePartitionConditionalExpectation_gmeasurable
    {Ω : Type*} [𝓕 : MeasurableSpace Ω] {P : Measure Ω} [IsFiniteMeasure P]
    {𝓖 : SigmaField Ω} {A : ℕ → Set Ω} {X : Ω → ℝ}
    (hPartition : thm_13_12_countablePartition A)
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A) :
    GMeasurable 𝓖
      (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) := by
  classical
  refine measurable_of_tendsto_metrizable
    (f := fun n ω => ∑ i ∈ Finset.range n,
      @thm_13_12_atomTerm Ω 𝓕 P _ A X i ω)
    (g := @thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X)
    (fun n => @thm_13_12_partialSum_gmeasurable Ω 𝓕 P _ 𝓖 A X hGenerated n) ?_
  rw [tendsto_pi_nhds]
  intro ω
  change Filter.Tendsto
    (fun n : ℕ =>
      ∑ i ∈ Finset.range n, @thm_13_12_atomTerm Ω 𝓕 P _ A X i ω)
    atTop
    (nhds (∑' i : ℕ, @thm_13_12_atomTerm Ω 𝓕 P _ A X i ω))
  rcases hPartition.1 ω with ⟨k, hωk⟩
  exact (summable_of_ne_finset_zero
    (s := {k})
    (by
      intro i hi
      have hne : i ≠ k := by
        simpa using hi
      have hd : Disjoint (A i) (A k) := hPartition.2 hne
      have hωnot : ω ∉ A i := by
        intro hmem
        exact Set.disjoint_left.mp hd hmem hωk
      simp [thm_13_12_atomTerm, hωnot])).hasSum.tendsto_sum_nat

/-- On a partition atom, the countable formula has only the matching summand. -/
theorem thm_13_12_countablePartitionConditionalExpectation_of_mem
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsFiniteMeasure P]
    {A : ℕ → Set Ω} (X : Ω → ℝ)
    (hPartition : thm_13_12_countablePartition A)
    {i : ℕ} {ω : Ω} (hω : ω ∈ A i) :
    thm_13_12_countablePartitionConditionalExpectation P A X ω =
      thm_13_12_atomConditionalExpectation P A X i := by
  unfold thm_13_12_countablePartitionConditionalExpectation
  rw [tsum_eq_single i]
  · simp [thm_13_12_atomTerm, hω]
  · intro j hji
    have hd : Disjoint (A j) (A i) := hPartition.2 hji
    have hωj : ω ∉ A j := by
      intro hmem
      exact Set.disjoint_left.mp hd hmem hω
    simp [thm_13_12_atomTerm, hωj]

/-- On a positive-probability partition atom, the countable formula is the
Definition 13.1 conditional expectation for that atom. -/
theorem thm_13_12_countablePartitionConditionalExpectation_of_mem_wellDefined
    {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω) [IsFiniteMeasure P]
    {A : ℕ → Set Ω} (X : Ω → ℝ)
    (hPartition : thm_13_12_countablePartition A)
    {i : ℕ} {ω : Ω} (hω : ω ∈ A i)
    (hAi : MeasurableSet (A i)) (hA0 : P (A i) ≠ 0) :
    thm_13_12_countablePartitionConditionalExpectation P A X ω =
      def_13_1 P (A i) hAi hA0 (measure_ne_top P (A i)) X := by
  rw [thm_13_12_countablePartitionConditionalExpectation_of_mem P X hPartition hω]
  exact thm_13_12_atomConditionalExpectation_of_wellDefined X hAi hA0

/-- Atom-level integral calculation for the countable-partition formula. -/
theorem thm_13_12_countablePartitionConditionalExpectation_atom_integral
    {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsFiniteMeasure P]
    {A : ℕ → Set Ω} (X : Ω → ℝ)
    (hPartition : thm_13_12_countablePartition A)
    {i : ℕ} (hAi : MeasurableSet (A i)) :
    ∫ ω in A i, thm_13_12_countablePartitionConditionalExpectation P A X ω ∂P =
      ∫ ω in A i, X ω ∂P := by
  have hconst :
      ∫ ω in A i, thm_13_12_countablePartitionConditionalExpectation P A X ω ∂P =
        ∫ _ω in A i, thm_13_12_atomConditionalExpectation P A X i ∂P := by
    refine setIntegral_congr_ae hAi ?_
    exact Filter.Eventually.of_forall fun ω hω =>
      thm_13_12_countablePartitionConditionalExpectation_of_mem P X hPartition hω
  rw [hconst]
  by_cases hzero : P (A i) = 0
  · have hscalar :
        thm_13_12_atomConditionalExpectation P A X i = 0 :=
      thm_13_12_atomConditionalExpectation_of_null X hAi hzero
    rw [hscalar]
    have hrestrict : P.restrict (A i) = 0 := Measure.restrict_eq_zero.mpr hzero
    rw [show ∫ _ω in A i, (0 : ℝ) ∂P =
        ∫ _ω, (0 : ℝ) ∂(P.restrict (A i)) by rfl]
    rw [show ∫ ω in A i, X ω ∂P = ∫ ω, X ω ∂(P.restrict (A i)) by rfl]
    rw [hrestrict, integral_zero_measure, integral_zero_measure]
  · have hfinite : P (A i) ≠ ⊤ := measure_ne_top P (A i)
    have hreal_ne : (P (A i)).toReal ≠ 0 := by
      exact ENNReal.toReal_ne_zero.mpr ⟨hzero, hfinite⟩
    have hscalar :
        thm_13_12_atomConditionalExpectation P A X i =
          def_13_1 P (A i) hAi hzero hfinite X :=
      thm_13_12_atomConditionalExpectation_of_wellDefined X hAi hzero
    rw [hscalar, thm_13_12_def_13_1_simple_formula P (A i) hAi hzero hfinite X]
    rw [show ∫ _ω in A i, (∫ ω in A i, X ω ∂P) / (P (A i)).toReal ∂P =
        ∫ _ω, (∫ ω in A i, X ω ∂P) / (P (A i)).toReal ∂(P.restrict (A i)) by rfl]
    rw [integral_const, Measure.real_def, Measure.restrict_apply_univ]
    rw [smul_eq_mul]
    exact mul_div_cancel₀ (∫ ω in A i, X ω ∂P) hreal_ne

/-- The atomwise formula has no more L¹ mass on a partition atom than `X`
has there. -/
theorem thm_13_12_countablePartitionConditionalExpectation_atom_norm_le
    {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω} [IsFiniteMeasure P]
    {A : ℕ → Set Ω} (X : Ω → ℝ)
    (hPartition : thm_13_12_countablePartition A)
    {i : ℕ} (hAi : MeasurableSet (A i)) :
    ∫ ω in A i,
        ‖thm_13_12_countablePartitionConditionalExpectation P A X ω‖ ∂P ≤
      ∫ ω in A i, ‖X ω‖ ∂P := by
  have hconst :
      ∫ ω in A i,
          ‖thm_13_12_countablePartitionConditionalExpectation P A X ω‖ ∂P =
        ∫ _ω in A i, ‖thm_13_12_atomConditionalExpectation P A X i‖ ∂P := by
    refine setIntegral_congr_ae hAi ?_
    exact Filter.Eventually.of_forall fun ω hω => by
      rw [thm_13_12_countablePartitionConditionalExpectation_of_mem P X
        hPartition hω]
  rw [hconst]
  by_cases hzero : P (A i) = 0
  · have hscalar :
        thm_13_12_atomConditionalExpectation P A X i = 0 :=
      thm_13_12_atomConditionalExpectation_of_null X hAi hzero
    rw [hscalar]
    have hrestrict : P.restrict (A i) = 0 := Measure.restrict_eq_zero.mpr hzero
    rw [show ∫ _ω in A i, ‖(0 : ℝ)‖ ∂P =
        ∫ _ω, ‖(0 : ℝ)‖ ∂(P.restrict (A i)) by rfl]
    rw [show ∫ ω in A i, ‖X ω‖ ∂P =
        ∫ ω, ‖X ω‖ ∂(P.restrict (A i)) by rfl]
    rw [hrestrict, integral_zero_measure, integral_zero_measure]
  · have hfinite : P (A i) ≠ ⊤ := measure_ne_top P (A i)
    have hreal_ne : (P (A i)).toReal ≠ 0 := by
      exact ENNReal.toReal_ne_zero.mpr ⟨hzero, hfinite⟩
    have hreal_nonneg : 0 ≤ (P (A i)).toReal := ENNReal.toReal_nonneg
    have hscalar :
        thm_13_12_atomConditionalExpectation P A X i =
          def_13_1 P (A i) hAi hzero hfinite X :=
      thm_13_12_atomConditionalExpectation_of_wellDefined X hAi hzero
    rw [hscalar, thm_13_12_def_13_1_simple_formula P (A i) hAi hzero hfinite X]
    rw [show ∫ _ω in A i, ‖(∫ ω in A i, X ω ∂P) / (P (A i)).toReal‖ ∂P =
        ∫ _ω, ‖(∫ ω in A i, X ω ∂P) / (P (A i)).toReal‖
          ∂(P.restrict (A i)) by rfl]
    rw [integral_const, Measure.real_def, Measure.restrict_apply_univ]
    rw [smul_eq_mul]
    have hmul :
        (P (A i)).toReal *
            ‖(∫ ω in A i, X ω ∂P) / (P (A i)).toReal‖ =
          ‖∫ ω in A i, X ω ∂P‖ := by
      rw [norm_div, Real.norm_of_nonneg hreal_nonneg]
      exact mul_div_cancel₀ (‖∫ ω in A i, X ω ∂P‖) hreal_ne
    rw [hmul]
    exact norm_integral_le_integral_norm (μ := P.restrict (A i)) (f := X)

/-- If `X` is integrable, then the countable-partition atomwise formula is
integrable. -/
theorem thm_13_12_countablePartitionConditionalExpectation_integrable
    {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {𝓖 : SigmaField Ω}
    {h𝓖 : IsSubSigmaField 𝓖 𝓕} {A : ℕ → Set Ω} {X : Ω → ℝ}
    (hPartition : thm_13_12_countablePartition A)
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A)
    (hX : @AmbientIntegrable Ω 𝓕 P X) :
    @AmbientIntegrable Ω 𝓕 P
      (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) := by
  have hAi : ∀ i : ℕ, @MeasurableSet Ω 𝓕 (A i) := by
    intro i
    exact h𝓖
      (@thm_13_12_atom_measurableIn_generated Ω 𝓖 A hGenerated i)
  have hUnion : (⋃ i : ℕ, A i) = (Set.univ : Set Ω) := by
    ext ω
    constructor
    · intro _h
      trivial
    · intro _h
      rcases hPartition.1 ω with ⟨i, hωi⟩
      exact Set.mem_iUnion.mpr ⟨i, hωi⟩
  have hi : ∀ i : ℕ,
      @IntegrableOn Ω ℝ 𝓕 _ _
        (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X)
        (A i) P := by
    intro i
    have hconstInt : @IntegrableOn Ω ℝ 𝓕 _ _
        (fun _ω : Ω => @thm_13_12_atomConditionalExpectation Ω 𝓕 P _ A X i)
        (A i) P :=
      integrableOn_const (hs := measure_ne_top P (A i))
    refine hconstInt.congr_fun ?_ (hAi i)
    intro ω hω
    exact
      (@thm_13_12_countablePartitionConditionalExpectation_of_mem
        Ω 𝓕 P _ A X hPartition i ω hω).symm
  have hsumX : Summable fun i : ℕ => ∫ ω in A i, ‖X ω‖ ∂P := by
    have hXnormInt : @IntegrableOn Ω ℝ 𝓕 _ _ (fun ω : Ω => ‖X ω‖)
        (⋃ i : ℕ, A i) P :=
      hX.norm.integrableOn
    exact (hasSum_integral_iUnion (μ := P) (s := A) hAi hPartition.2
      hXnormInt).summable
  have hsumFormula : Summable fun i : ℕ =>
      ∫ ω in A i,
        ‖(@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) ω‖
          ∂P := by
    refine Summable.of_nonneg_of_le
      (fun i => integral_nonneg fun ω => norm_nonneg _) ?_ hsumX
    intro i
    exact
      @thm_13_12_countablePartitionConditionalExpectation_atom_norm_le
        Ω 𝓕 P _ A X hPartition i (hAi i)
  have hIntUnion :
      @IntegrableOn Ω ℝ 𝓕 _ _
        (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X)
        (⋃ i : ℕ, A i) P :=
    integrableOn_iUnion_of_summable_integral_norm hi hsumFormula
  simpa [AmbientIntegrable, hUnion, integrableOn_univ] using hIntUnion

/-- The theorem-level assembly of Definition 13.3 for the countable-partition
formula. -/
theorem thm_13_12_countablePartitionVersionSupport {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] {P : Measure Ω} [IsProbabilityMeasure P]
    {𝓖 : SigmaField Ω}
    {h𝓖 : IsSubSigmaField 𝓖 𝓕} {A : ℕ → Set Ω} {X : Ω → ℝ}
    (hPartition : thm_13_12_countablePartition A)
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A)
    (hX : @AmbientIntegrable Ω 𝓕 P X) :
    @def_13_3 Ω 𝓕 P 𝓖 h𝓖 X
      (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) := by
  have hFormulaInt :
      @AmbientIntegrable Ω 𝓕 P
        (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) :=
    @thm_13_12_countablePartitionConditionalExpectation_integrable
      Ω 𝓕 P _ 𝓖 h𝓖 A X hPartition hGenerated hX
  refine ⟨hX, hFormulaInt, ?_, ?_⟩
  · simpa using
      (@thm_13_12_countablePartitionConditionalExpectation_gmeasurable
        Ω 𝓕 P _ 𝓖 A X hPartition hGenerated)
  · intro B hB
    classical
    let C : ℕ → Set Ω := fun i => if A i ⊆ B then A i else ∅
    have hSat :=
      thm_13_12_generated_set_atom_saturated hPartition hGenerated hB
    have hAi : ∀ i : ℕ, @MeasurableSet Ω 𝓕 (A i) := by
      intro i
      exact h𝓖
        (@thm_13_12_atom_measurableIn_generated Ω 𝓖 A hGenerated i)
    have hCmeas : ∀ i : ℕ, @MeasurableSet Ω 𝓕 (C i) := by
      intro i
      unfold C
      by_cases hsub : A i ⊆ B
      · simp [hsub, hAi i]
      · simp [hsub]
    have hCdisjoint : Pairwise fun i j : ℕ => Disjoint (C i) (C j) := by
      intro i j hij
      unfold C
      by_cases hi : A i ⊆ B <;> by_cases hj : A j ⊆ B
      · simpa [hi, hj] using hPartition.2 hij
      · simp [hi, hj]
      · simp [hi, hj]
      · simp [hi, hj]
    have hUnion : (⋃ i : ℕ, C i) = B := by
      ext ω
      constructor
      · intro hω
        rcases Set.mem_iUnion.mp hω with ⟨i, hωi⟩
        unfold C at hωi
        by_cases hsub : A i ⊆ B
        · have hωAi : ω ∈ A i := by
            simpa [hsub] using hωi
          exact hsub hωAi
        · simp [hsub] at hωi
      · intro hωB
        rcases hPartition.1 ω with ⟨i, hωi⟩
        have hsub : A i ⊆ B := by
          rcases hSat i with hsub | hdis
          · exact hsub
          · exact (Set.disjoint_left.mp hdis hωi hωB).elim
        exact Set.mem_iUnion.mpr ⟨i, by simp [C, hsub, hωi]⟩
    calc
      ∫ ω in B,
          (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) ω ∂P
          = ∫ ω in ⋃ i : ℕ, C i,
              (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) ω ∂P := by
            rw [hUnion]
      _ = ∑' i : ℕ,
            ∫ ω in C i,
              (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) ω ∂P := by
            rw [← @thm_13_11 Ω 𝓕 P _
              (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X)
              C hFormulaInt hCmeas hCdisjoint]
      _ = ∑' i : ℕ, ∫ ω in C i, X ω ∂P := by
            apply tsum_congr
            intro i
            unfold C
            by_cases hsub : A i ⊆ B
            · simp [hsub,
                @thm_13_12_countablePartitionConditionalExpectation_atom_integral
                  Ω 𝓕 P _ A X hPartition i (hAi i)]
            · simp [hsub]
      _ = ∫ ω in ⋃ i : ℕ, C i, X ω ∂P := by
            rw [@thm_13_11 Ω 𝓕 P _ X C hX hCmeas hCdisjoint]
      _ = ∫ ω in B, X ω ∂P := by
            rw [hUnion]
