import Mathlib
import ToyApollo.Output.thm_12_4
import ToyApollo.Output.thm_12_5

/-
TASK ID: thm_12_6
TYPE: Theorem_with_Proof
SOURCE PLAN: chapter12-mmse-estimation
TASK CONTENT:
\begin{thmbox}{12.6 (Functions Measurable with Respect to\sigma( X))}
\end{thmbox}

X()= (X 1(), X2(), . . . , Xn())

Consider an \mathcal{F}-measurable vector function X()=

(X1(), X2(), . . . , Xn()) defined on a measurable space .(\Omega,\mathcal{F})A n

\mathcal{F}-measurable function Y() can be written as Y= g(X 1,X 2,...,X n) for

a .(\mathcal{B}(Rn),\mathcal{B}(R))-measurable function g if and only if Y is measurable with

respect to\sigma( X).

\textit{Proof} ( . ) Suppose that X is \mathcal{F}-measurable from \Omega to Rn, and g is

(\mathcal{B}(Rn),\mathcal{B}(R))-measurable function from Rn to R. Consider the composite

function Y= g X Given any Borel set B\in \mathcal{B} (R), the inverse image g- 1(B) is

\mathcal{B}(Rn)-measurable. Since the vector function X is.(\sigma(X),\mathcal{B}(Rn))-measurable, the

inverse imageY- 1(B)= X - 1(g- 1(B)) is in\sigma( X).

(. ) Suppose that Y is an \mathcal{F}-measurable function that is also \sigma( X)-measurable.

By definition, we have Y- 1(B)\in \sigma( X) for all Borel sets B in. R.

When Y is an indicator function .1A() for some A\in \mathcal{F} , the inverse image

Y- 1({1})= A must be in \sigma( X) by the assumption that Y is \sigma( X)-measurable.

Hence,A= X - 1(B) for someB\in \mathcal{B} (Rn)We can set

g(x1,x 2,...,x n)=

{

1i f (x1,x 2,...,x n)\in B,

0 otherwise .

Then g is Borel measurable, and Y() =g( X()) for all\in \Omega .

Next, suppose Y is a simple function in the form .

\summ

i=1 ai 1Ai ,f o r s o m eAi \in\mathcal{F}.

We can find Borel measurable function gi such that

Y() =

m\sum

i=1

aigi(X1(), . . . , Xn()).

The rest of the proof is to extend it to nonnegative measurable functions and real-

valued measurable functions. It is the standard machinery of Lebesgue integral and

the detail is omitted. \hfill $\square$

In nonlinear MMSE estimation, we define W to be the set of all random variables

on .(\Omega,\mathcal{F},P) that are measurable with respect to the \sigma-algebra \sigma( X) and have

finite second moment. We denote this set by L2(\Omega, \sigma(X), P), where P denotes the

restriction of the original probability measure to the sub- \sigma-algebra\sigma( X)Note that

L2(\Omega, \sigma(X), P) is a closed subspace of the space of all square-integrable random

variables on.(\Omega,\mathcal{F},P) .

The optimization problem can now be stated as

min

g(x1,...,xn)

Y- g(X 1,X 2,...,X n)2

with the minimum taken over all functions g: R n \to R such that. g(X1,...,X n)\in

L2(\Omega, \sigma(X), P)We project Y onto the closed subspace L2(\Omega, \sigma(X), P)B y

Theorem 12.4, a solution exists and any two solutions are equal almost surely. By

the Orthogonal Principle, the solution is characterized by

E[ YZ ]= E[YZ ]for all Z \in L 2(\Omega, \sigma(X), P). (12.5)

Indeed, the condition in (12.5) can be written in several equivalent forms,

\langleY- Y,Z \rangle= 0 for all Z \in L 2(\Omega, \sigma(X), P)

E [(Y- Y)Z ]= 0 for all Z \in L 2(\Omega, \sigma(X), P)

E [YZ ]= E[ YZ ]for all Z \in L 2(\Omega, \sigma(X), P)

E[Yh( X)]= E[ Yh( X)] for all \mathcal{B}(Rn )-measurable h(x) st. h(X) \in L2(P).

We illustrate this idea in the following example.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open scoped InnerProductSpace

noncomputable section

/-- If `g` is Borel measurable, then `g ∘ X` is measurable with respect to the
sigma-algebra generated by `X`. This is the easy direction of Theorem 12.6. -/
theorem thm_12_6_comp_measurable {Ω S : Type*} [MeasurableSpace S]
    (X : Ω → S) (g : S → ℝ) (hg : Measurable g) :
    Measurable[(inferInstance : MeasurableSpace S).comap X] (g ∘ X) :=
  hg.comp (comap_measurable X)

/-- Doob-Dynkin factorization: a real-valued function measurable with respect to
the sigma-algebra generated by `X` factors as a Borel function of `X`. -/
theorem thm_12_6_factorization {Ω S : Type*} [MeasurableSpace S]
    (X : Ω → S) (Y : Ω → ℝ)
    (hY : Measurable[(inferInstance : MeasurableSpace S).comap X] Y) :
    ∃ g : S → ℝ, Measurable g ∧ Y = g ∘ X :=
  hY.exists_eq_measurable_comp

/-- Theorem 12.6, in a general feature-space form: a real-valued function is a
measurable function of `X` iff it is measurable with respect to the
sigma-algebra generated by `X`. -/
theorem thm_12_6 {Ω S : Type*} [MeasurableSpace S]
    (X : Ω → S) (Y : Ω → ℝ) :
    (∃ g : S → ℝ, Measurable g ∧ Y = g ∘ X) ↔
      Measurable[(inferInstance : MeasurableSpace S).comap X] Y := by
  constructor
  · rintro ⟨g, hg, rfl⟩
    exact thm_12_6_comp_measurable X g hg
  · exact thm_12_6_factorization X Y

/-- The same statement specialized to a finite real vector
`X = (X₁, ..., Xₙ)`, represented in Lean as `Fin n → ℝ`. -/
theorem thm_12_6_fin {Ω : Type*} (n : ℕ)
    (X : Ω → Fin n → ℝ) (Y : Ω → ℝ) :
    (∃ g : (Fin n → ℝ) → ℝ, Measurable g ∧ Y = g ∘ X) ↔
      Measurable[(inferInstance : MeasurableSpace (Fin n → ℝ)).comap X] Y :=
  thm_12_6 X Y

/-- The MMSE projection characterization cited after Theorem 12.6: a candidate
in a closed `L²(P)` subspace is the projection exactly when its error is
orthogonal to every element of the subspace. -/
theorem thm_12_6_mmse_projection_characterization {Ω : Type*}
    [MeasurableSpace Ω] (P : Measure Ω) [IsProbabilityMeasure P]
    (W : ClosedSubmodule ℝ (Ω →₂[P] ℝ)) (Y : Ω →₂[P] ℝ) (Yhat : W) :
    Yhat = def_12_5 P W Y ↔
      ∀ Z : W,
        ⟪Y - (Yhat : Ω →₂[P] ℝ), (Z : Ω →₂[P] ℝ)⟫_ℝ = 0 :=
  thm_12_5 P W Y Yhat
