import Mathlib
import ToyApollo.Output.thm_12_6
import ToyApollo.Output.thm_13_3_l2_support

/-
TASK ID: thm_13_3
TYPE: Theorem_Statement
SOURCE PLAN: chapter13-sub-sigma-algebra
TASK CONTENT:
\begin{thmbox}{13.3}
\end{thmbox}

If X is in L2(P) , then E[X\vert\mathcal{G}] is the MMSE estimator of X that achieves the

minimum

min

Z

Z- X = E[X\vert\mathcal{G}]- X

with the minimum taken over all \mathcal{G}-measurable random variables in L2(P) .

The example of nonlinear MMSE estimator in Example 12.4.3 is indeed an

example of conditional expectation in the case of a finite sample space.

Remark 13.1 When \mathcal{G}is generated by a partition of \Omega consisting of k disjoint

events, then E[X\vert\mathcal{G}] reduces to the conditional expectation defined in the previous

section.

We first prove that the condition in (13.3) uniquely defines the conditional

expectation, up to a null set. That is, if there are two solutions to (13.3), then they

must be equal almost surely.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open ProbabilityTheory
open scoped InnerProductSpace

noncomputable section

/-- The admissible competitors in Theorem 13.3: real random variables that are
`𝓖`-measurable and square-integrable with respect to the ambient probability
measure. -/
def thm_13_3_candidate {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (P : Measure Ω) (𝓖 : SigmaField Ω) (Z : Ω → ℝ) : Prop :=
  GMeasurable 𝓖 Z ∧ @L2Function Ω 𝓕 P Z

/-- The textbook mean-square-error norm, written in Mathlib's `L²(P)`
quotient space so that almost-surely equal versions are identified. -/
def thm_13_3_l2Error {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (P : Measure Ω) (X Z : Ω → ℝ)
    (hX : @L2Function Ω 𝓕 P X) (hZ : @L2Function Ω 𝓕 P Z) : ℝ :=
  ‖@L2Function.toLp Ω 𝓕 P X hX - @L2Function.toLp Ω 𝓕 P Z hZ‖

/-- The MMSE assertion in Theorem 13.3: `Y` is a `𝓖`-measurable
square-integrable estimator of `X`, and no other `𝓖`-measurable
square-integrable estimator has smaller `L²` error. -/
def thm_13_3_MMSE {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    (P : Measure Ω) (𝓖 : SigmaField Ω) (X Y : Ω → ℝ) : Prop :=
  ∃ hX : @L2Function Ω 𝓕 P X, ∃ hY : @L2Function Ω 𝓕 P Y,
    GMeasurable 𝓖 Y ∧
      ∀ Z : Ω → ℝ, ∀ hZ : @thm_13_3_candidate Ω 𝓕 P 𝓖 Z,
        @thm_13_3_l2Error Ω 𝓕 P X Y hX hY ≤
          @thm_13_3_l2Error Ω 𝓕 P X Z hX hZ.2

/-- The conditional expectation version satisfying the `L²` projection formula
is an admissible competitor. -/
theorem thm_13_3_candidate_of_l2_projection {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓖 : SigmaField Ω} {X Y : Ω → ℝ}
    (h : @ConditionalExpectationL2ProjectionFormula Ω 𝓕 P 𝓖 X Y) :
    @thm_13_3_candidate Ω 𝓕 P 𝓖 Y := by
  rcases h with ⟨_hX, hY, hYg, _hinner⟩
  exact ⟨hYg, hY⟩

/-- Formula (13.5) in the square-integrable case is exactly the equal-inner-
products condition used by the orthogonality principle. -/
theorem thm_13_3_equal_inner_products {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓖 : SigmaField Ω} {X Y Z : Ω → ℝ}
    (h :
      @ConditionalExpectationL2ProjectionFormula Ω 𝓕 P 𝓖 X Y)
    (hZ : @thm_13_3_candidate Ω 𝓕 P 𝓖 Z) :
    ∃ hX : @L2Function Ω 𝓕 P X, ∃ hY : @L2Function Ω 𝓕 P Y,
      @l2Inner Ω 𝓕 P Y Z hY hZ.2 =
        @l2Inner Ω 𝓕 P X Z hX hZ.2 := by
  rcases h with ⟨hX, hY, _hYg, hinner⟩
  exact ⟨hX, hY, hinner Z hZ.1 hZ.2⟩

/-- The Doob-Dynkin part of Theorem 12.6 supplies the textbook statement that
competitors measurable with respect to `σ(X)` can be written as functions of
the observed feature `X`. This is the nonlinear-MMSE reading used just before
Theorem 13.3. -/
theorem thm_13_3_sigma_measurable_factorization {Ω S : Type*}
    [MeasurableSpace S] (feature : Ω → S) (Y : Ω → ℝ) :
    (∃ g : S → ℝ, Measurable g ∧ Y = g ∘ feature) ↔
      Measurable[(inferInstance : MeasurableSpace S).comap feature] Y :=
  thm_12_6 feature Y

/-- The source-facing bridge for Theorem 13.3: a conditional expectation
version satisfying the `L²` projection formula is the MMSE estimator among all
`𝓖`-measurable square-integrable competitors. -/
theorem thm_13_3_mmse_of_l2_projection_formula {Ω : Type*}
    [𝓕 : MeasurableSpace Ω] {P : Measure Ω} {𝓖 : SigmaField Ω} {X Y : Ω → ℝ}
    (hCE : @ConditionalExpectationL2ProjectionFormula Ω 𝓕 P 𝓖 X Y) :
    @thm_13_3_MMSE Ω 𝓕 P 𝓖 X Y := by
  rcases hCE with ⟨hX, hY, hYg, hinner⟩
  refine ⟨hX, hY, hYg, ?_⟩
  intro Z hZc
  rcases hZc with ⟨hZg, hZ⟩
  let D : Ω → ℝ := Z - Y
  have hDg : GMeasurable 𝓖 D := by
    exact gMeasurable_sub hZg hYg
  have hD : @L2Function Ω 𝓕 P D :=
    @l2Function_sub Ω 𝓕 P Z Y hZ hY
  have hraw :
      @l2Inner Ω 𝓕 P Y D hY hD =
        @l2Inner Ω 𝓕 P X D hX hD :=
    hinner D hDg hD
  have horthD :
      ⟪@L2Function.toLp Ω 𝓕 P X hX - @L2Function.toLp Ω 𝓕 P Y hY,
        @L2Function.toLp Ω 𝓕 P D hD⟫_ℝ = 0 := by
    rw [inner_sub_left,
      @l2Function_toLp_inner_eq_l2Inner Ω 𝓕 P X D hX hD,
      @l2Function_toLp_inner_eq_l2Inner Ω 𝓕 P Y D hY hD]
    linarith
  have hD_toLp :
      @L2Function.toLp Ω 𝓕 P D hD =
        @L2Function.toLp Ω 𝓕 P Z hZ - @L2Function.toLp Ω 𝓕 P Y hY := by
    dsimp [D]
    unfold L2Function.toLp
    rw [MemLp.toLp_sub]
  have horth :
      ⟪@L2Function.toLp Ω 𝓕 P X hX - @L2Function.toLp Ω 𝓕 P Y hY,
        @L2Function.toLp Ω 𝓕 P Z hZ - @L2Function.toLp Ω 𝓕 P Y hY⟫_ℝ = 0 := by
    rw [← hD_toLp]
    exact horthD
  exact
    hilbert_norm_le_of_inner_sub_eq_zero
      (@L2Function.toLp Ω 𝓕 P X hX)
      (@L2Function.toLp Ω 𝓕 P Y hY)
      (@L2Function.toLp Ω 𝓕 P Z hZ)
      horth

/-- Theorem 13.3: in the square-integrable case, a conditional expectation
version satisfying the `L²` projection identity is the MMSE estimator of `X`
among all `𝓖`-measurable square-integrable random variables. -/
theorem thm_13_3 {Ω : Type*} [𝓕 : MeasurableSpace Ω] (P : Measure Ω)
    [IsProbabilityMeasure P] (𝓖 : SigmaField Ω) {X Y : Ω → ℝ}
    (hCE : @ConditionalExpectationL2ProjectionFormula Ω 𝓕 P 𝓖 X Y) :
    @thm_13_3_MMSE Ω 𝓕 P 𝓖 X Y :=
  @thm_13_3_mmse_of_l2_projection_formula Ω 𝓕 P 𝓖 X Y hCE
