import Mathlib
import ToyApollo.Output.thm_2_8

/-
TASK ID: thm_10_9
TYPE: Theorem_with_Proof
SOURCE PLAN: chapter10-random-vectors
TASK CONTENT:
\begin{thmbox}{10.9}
Let $(\Omega,\mathcal{F})$ be a measurable space and
\[
V(\omega)\coloneqq (X_1(\omega),X_2(\omega),\ldots,X_d(\omega))
\]
be a mapping from $\Omega$ to $\mathbb{R}^d$, where $X_i(\omega)$ is the $i$-th component function. Then $V(\omega)$ is $(\mathcal{F},\mathcal{B}(\mathbb{R}^d))$-measurable if and only if $X_i(\omega)$ is $(\mathcal{F},\mathcal{B}(\mathbb{R}))$-measurable for $i=1,2,\ldots,d$.
\end{thmbox}

\textit{Proof}
Suppose $X_i$ is measurable for all $i$. We want to show that $V^{-1}(B)$ is $\mathcal{F}$-measurable for any Borel set $B$ in $\mathcal{B}(\mathbb{R}^d)$. Since $\mathcal{B}(\mathbb{R}^d)$ is generated by $d$-dimensional hyper-cubes (see Theorem 2.8), it is sufficient to show that $V^{-1}(C)$ is $\mathcal{F}$-measurable for any hyper-cube $C$ of the form
\[
(a_1,b_1)\times(a_2,b_2)\times\cdots\times(a_d,b_d),
\]
where $a_i,b_i$ are real numbers, possibly $\pm\infty$.

For any hyper-cube $C$, the inverse image $V^{-1}(C)$ is equal to
\[
\{\omega:X_i(\omega)\in(a_i,b_i)\text{ for }i=1,2,\ldots,d\}
=
\bigcap_{i=1}^{d}\{\omega:X_i(\omega)\in(a_i,b_i)\}.
\]
Since each set in the intersection is $\mathcal{F}$-measurable, the set $V^{-1}(C)$ is also $\mathcal{F}$-measurable.

Conversely, suppose $V$ is $\mathcal{F}$-measurable. That is, we suppose that $V^{-1}(B)$ is $\mathcal{F}$-measurable for all Borel sets $B\in\mathcal{B}(\mathbb{R}^d)$. For each $i=1,2,\ldots,d$, let $A_i$ be the cylinder
\[
A_i=\mathbb{R}\times\cdots\times\mathbb{R}\times(a_i,b_i)\times\mathbb{R}\times\cdots\times\mathbb{R},
\]
where the interval $(a_i,b_i)$ is in the $i$-th component. This is a Borel set. Then $V^{-1}(A_i)$ is $\mathcal{F}$-measurable, and it is equal to
\[
V^{-1}(A_i)=X_i^{-1}((a_i,b_i)).
\]
Hence, $X_i^{-1}((a_i,b_i))$ is $\mathcal{F}$-measurable for all $a_i,b_i\in\mathbb{R}$.
\hfill $\square$
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory

/-- A vector-valued map into `ℝ^d`, represented as `Fin d → ℝ`, is measurable
if and only if each coordinate map is measurable. -/
theorem coordinatewiseMeasurable_iff_vectorMeasurable {Ω : Type*} [MeasurableSpace Ω]
    {d : ℕ} (V : Ω → Fin d → ℝ) :
    Measurable V ↔ ∀ i : Fin d, Measurable (fun ω : Ω => V ω i) := by
  exact measurable_pi_iff

/-- Textbook Theorem 10.9. -/
theorem thm_10_9 {Ω : Type*} [MeasurableSpace Ω] {d : ℕ} (V : Ω → Fin d → ℝ) :
    Measurable V ↔ ∀ i : Fin d, Measurable (fun ω : Ω => V ω i) := by
  exact coordinatewiseMeasurable_iff_vectorMeasurable V
