import Mathlib
import ToyApollo.Output.def_13_2
import ToyApollo.Output.thm_13_1

/-
TASK ID: thm_13_2
TYPE: Theorem_with_Proof
SOURCE PLAN: chapter13-finite-partition
TASK CONTENT:
\begin{thmbox}{13.2}
\end{thmbox}

For any eventC \in\mathcal{G},

\int

C

E[X\vert\mathcal{G}] dP =

\int

C

XdP. (13.1)

In particular , we have

E[E[X\vert\mathcal{G}]] = E[X]. (13.2)

\textit{Proof} Recall that the events A1 to Ak form a partition of \Omega and are mutually

disjoint. They are the atoms of the \sigma-algebra \mathcal{G}Any event C in \mathcal{G}is a union of

some sets among A1 to Ak Thus, we can find an index set I \subseteq{ 1, 2,...,k } such

thatC =\cup i\inI Ai .

By the definition of expectation for simple function, we have

\int

C

E[X\vert\mathcal{G}] dP =

k\sum

i=1

E[X\vertAi]\cdot P(C \cap Ai) =

\sum

i\inI

E[X\vertAi]P(Ai)

=

\sum

i\inI

( 1

P(Ai)

\int

Ai

XdP

)

P(Ai),

which can be simplified to

\sum

i\inI

\int

Ai

XdP =

\int

C

XdP.

This holds for any C \in\mathcal{G}By setting C = \Omega , we obtain (13.2)\hfill $\square$

The equality in (13.2) is saying that the overall average valueE[X] is a weighted

average of the local average values E[X\vertAi]'s. In other words, the value of E[X\vert\mathcal{G}]

can be thought of as a "smoothing" of the random variable X that takes the partition

A1,A 2,...,A k into account.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open scoped BigOperators

noncomputable section

/-- The weighted atom contribution appearing in the proof of Theorem 13.2:
`E[X|A_i] * P(A_i)`. -/
def thm_13_2_atomWeightedAverage {Ω ι : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) (i : ι) : ℝ :=
  def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i) *
    (P (A i)).toReal

/-- The finite weighted average of the conditional expectations over the atoms. -/
def thm_13_2_weightedAverage {Ω ι : Type*} [MeasurableSpace Ω] [Fintype ι]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) : ℝ :=
  ∑ i, thm_13_2_atomWeightedAverage P A X hA hA_top i

def thm_13_2_sourceAtomMeasurable {Ω ι : Type*} [𝓕 : MeasurableSpace Ω]
    [Fintype ι] {P : Measure Ω} {𝓖 : MeasurableSpace Ω}
    {A : ι → Set Ω} {X : Ω → ℝ}
    (hDomain : @def_13_2_sourceDomain Ω ι 𝓕 _ P 𝓖 A X) :
    ∀ i : ι, @MeasurableSet Ω 𝓕 (A i) :=
  fun i => hDomain.2.2.2.2.2.1 (hDomain.2.2.1 i)

/-- Events in the sigma-field generated by a finite partition are represented
as finite unions of atoms. -/
def thm_13_2_atomUnion {Ω ι : Type*} (A : ι → Set Ω) (C : Set Ω) : Prop :=
  ∃ I : Finset ι, C = ⋃ i ∈ I, A i

lemma thm_13_2_atomUnion_empty {Ω ι : Type*} (A : ι → Set Ω) :
    thm_13_2_atomUnion A (∅ : Set Ω) := by
  refine ⟨∅, ?_⟩
  simp

lemma thm_13_2_atomUnion_compl {Ω ι : Type*} [Fintype ι]
    (A : ι → Set Ω) (hpart : def_13_2_isFinitePartition A)
    {C : Set Ω} (hC : thm_13_2_atomUnion A C) :
    thm_13_2_atomUnion A Cᶜ := by
  classical
  rcases hC with ⟨I, rfl⟩
  refine ⟨Finset.univ.filter (fun i => i ∉ I), ?_⟩
  ext ω
  constructor
  · intro hω
    rcases hpart.1 ω with ⟨j, hj⟩
    refine Set.mem_iUnion.2 ⟨j, ?_⟩
    refine Set.mem_iUnion.2 ⟨?_, hj⟩
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    intro hjI
    apply hω
    exact Set.mem_iUnion.2 ⟨j, Set.mem_iUnion.2 ⟨hjI, hj⟩⟩
  · intro hω hmem
    rcases Set.mem_iUnion.1 hω with ⟨j, hjrest⟩
    rcases Set.mem_iUnion.1 hjrest with ⟨hjnot, hωj⟩
    have hjnotI : j ∉ I := by simpa using hjnot
    rcases Set.mem_iUnion.1 hmem with ⟨k, hkrest⟩
    rcases Set.mem_iUnion.1 hkrest with ⟨hkI, hωk⟩
    have hjk : j ≠ k := by
      intro hEq
      exact hjnotI (by simpa [hEq] using hkI)
    exact (Set.disjoint_left.mp (hpart.2 j k hjk)) hωj hωk

lemma thm_13_2_atomUnion_iUnion {Ω ι : Type*} [Fintype ι]
    (A : ι → Set Ω) {F : ℕ → Set Ω}
    (hF : ∀ n, thm_13_2_atomUnion A (F n)) :
    thm_13_2_atomUnion A (⋃ n, F n) := by
  classical
  choose I hI using hF
  refine ⟨Finset.univ.filter (fun i => ∃ n, i ∈ I n), ?_⟩
  ext ω
  constructor
  · intro hω
    rcases Set.mem_iUnion.1 hω with ⟨n, hωn⟩
    rw [hI n] at hωn
    rcases Set.mem_iUnion.1 hωn with ⟨i, hirest⟩
    rcases Set.mem_iUnion.1 hirest with ⟨hiI, hωi⟩
    refine Set.mem_iUnion.2 ⟨i, ?_⟩
    refine Set.mem_iUnion.2 ⟨?_, hωi⟩
    simp only [Finset.mem_filter, Finset.mem_univ, true_and]
    exact ⟨n, hiI⟩
  · intro hω
    rcases Set.mem_iUnion.1 hω with ⟨i, hirest⟩
    rcases Set.mem_iUnion.1 hirest with ⟨hiJ, hωi⟩
    rcases (by simpa using hiJ : ∃ n, i ∈ I n) with ⟨n, hiIn⟩
    refine Set.mem_iUnion.2 ⟨n, ?_⟩
    rw [hI n]
    exact Set.mem_iUnion.2 ⟨i, Set.mem_iUnion.2 ⟨hiIn, hωi⟩⟩

lemma thm_13_2_generated_event_atomUnion {Ω ι : Type*} [Fintype ι]
    {𝓖 : MeasurableSpace Ω} {A : ι → Set Ω} {C : Set Ω}
    (hpart : def_13_2_isFinitePartition A)
    (hgen : def_13_2_generatesSigmaField 𝓖 A)
    (hC : @MeasurableSet Ω 𝓖 C) :
    thm_13_2_atomUnion A C := by
  classical
  let H : MeasurableSpace Ω :=
    { MeasurableSet' := thm_13_2_atomUnion A
      measurableSet_empty := thm_13_2_atomUnion_empty A
      measurableSet_compl := by
        intro s hs
        exact thm_13_2_atomUnion_compl A hpart hs
      measurableSet_iUnion := by
        intro f hf
        exact thm_13_2_atomUnion_iUnion A hf }
  have hAtoms : ∀ i : ι, @MeasurableSet Ω H (A i) := by
    intro i
    refine ⟨{i}, ?_⟩
    ext ω
    simp
  exact hgen.2 H hAtoms hC

/-- The source's simplification
`E[X|A_i] P(A_i) = ∫_{A_i} X dP`; null atoms contribute zero. -/
theorem thm_13_2_atomWeightedAverage_eq_integral {Ω ι : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ) (i : ι)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) :
    thm_13_2_atomWeightedAverage P A X hA hA_top i =
      ∫ ω in A i, X ω ∂P := by
  by_cases hAi0 : P (A i) = 0
  · unfold thm_13_2_atomWeightedAverage
    rw [def_13_2_atomConditionalExpectation_of_null P A X i (hA i) (hA_top i) hAi0]
    rw [setIntegral_measure_zero X hAi0]
    simp
  · unfold thm_13_2_atomWeightedAverage
    rw [def_13_2_atomConditionalExpectation_of_wellDefined
      P A X i (hA i) hAi0 (hA_top i)]
    rw [thm_13_1 P (A i) (hA i) hAi0 (hA_top i) X]
    have hreal : (P (A i)).toReal ≠ 0 :=
      ENNReal.toReal_ne_zero.mpr ⟨hAi0, hA_top i⟩
    field_simp [hreal]

theorem thm_13_2_weightedAverage_eq_sum_integrals {Ω ι : Type*}
    [MeasurableSpace Ω] [Fintype ι]
    (P : Measure Ω) (A : ι → Set Ω) (X : Ω → ℝ)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) :
    thm_13_2_weightedAverage P A X hA hA_top =
      ∑ i, ∫ ω in A i, X ω ∂P := by
  classical
  unfold thm_13_2_weightedAverage
  exact Finset.sum_congr rfl
    (fun i _ => thm_13_2_atomWeightedAverage_eq_integral
      P A X i hA hA_top)

/-- Integral of a single atom term. This is the calculation
`∫ E[X|A_i] 1_{A_i} dP = E[X|A_i] P(A_i)`. -/
theorem thm_13_2_integral_atomTerm {Ω ι : Type*} [MeasurableSpace Ω]
    {P : Measure Ω} {A : ι → Set Ω} {X : Ω → ℝ} (i : ι)
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) :
    ∫ ω, def_13_2_atomTerm P A X hA hA_top i ω ∂P =
      thm_13_2_atomWeightedAverage P A X hA hA_top i := by
  unfold def_13_2_atomTerm thm_13_2_atomWeightedAverage
  rw [integral_indicator_const (μ := P)
    (def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i)) (hA i)]
  rw [measureReal_def]
  change (P (A i)).toReal *
      def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i) =
    def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i) *
      (P (A i)).toReal
  ring

/-- Setting `C = Ω` in Theorem 13.2 gives the weighted-average identity:
the expectation of the finite-partition conditional expectation is the weighted
average of the local conditional expectations. -/
theorem thm_13_2_total_expectation {Ω ι : Type*} [MeasurableSpace Ω]
    [Fintype ι] {P : Measure Ω} [IsFiniteMeasure P] {A : ι → Set Ω} {X : Ω → ℝ}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) :
    ∫ ω, def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
      thm_13_2_weightedAverage P A X hA hA_top := by
  classical
  unfold def_13_2_finitePartitionConditionalExpectation thm_13_2_weightedAverage
  rw [integral_finset_sum]
  · exact Finset.sum_congr rfl
      (fun i _ => thm_13_2_integral_atomTerm i hA hA_top)
  · intro i _hi
    exact (integrable_const
      (def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i))).indicator (hA i)

/-- Integral of a single atom term over an arbitrary event `C`. -/
theorem thm_13_2_integral_atomTerm_on {Ω ι : Type*} [MeasurableSpace Ω]
    {P : Measure Ω} {A : ι → Set Ω} {X : Ω → ℝ} (i : ι) {C : Set Ω}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤)
    (hC : MeasurableSet C) :
    ∫ ω in C, def_13_2_atomTerm P A X hA hA_top i ω ∂P =
      def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i) *
        (P (C ∩ A i)).toReal := by
  unfold def_13_2_atomTerm
  rw [← integral_indicator hC]
  have hInd : (fun ω => C.indicator (fun x => (A i).indicator
      (fun _ => def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i)) x) ω)
      = (fun ω => (C ∩ A i).indicator
        (fun _ => def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i)) ω) := by
    ext ω
    by_cases hωC : ω ∈ C <;> by_cases hωA : ω ∈ A i <;> simp [hωC, hωA]
  rw [hInd]
  rw [integral_indicator_const (μ := P)
    (def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i)) (hC.inter (hA i))]
  rw [measureReal_def]
  simp [smul_eq_mul, mul_comm]

theorem thm_13_2_integral_finitePartitionCE_on {Ω ι : Type*}
    [MeasurableSpace Ω] [Fintype ι] {P : Measure Ω} [IsFiniteMeasure P]
    {A : ι → Set Ω} {X : Ω → ℝ} {C : Set Ω}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤)
    (hC : MeasurableSet C) :
    ∫ ω in C,
        def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
      ∑ i, def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i) *
        (P (C ∩ A i)).toReal := by
  classical
  unfold def_13_2_finitePartitionConditionalExpectation
  rw [integral_finset_sum]
  · exact Finset.sum_congr rfl
      (fun i _ => thm_13_2_integral_atomTerm_on i hA hA_top hC)
  · intro i _hi
    exact (integrable_const
      (def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i))).indicator (hA i)

lemma thm_13_2_inter_selected_self {Ω ι : Type*} {A : ι → Set Ω}
    {I : Finset ι} {C : Set Ω} {i : ι}
    (hC : C = ⋃ j ∈ I, A j) (hi : i ∈ I) :
    C ∩ A i = A i := by
  ext ω
  constructor
  · intro hω
    exact hω.2
  · intro hω
    exact ⟨by
      rw [hC]
      exact Set.mem_iUnion.2 ⟨i, Set.mem_iUnion.2 ⟨hi, hω⟩⟩, hω⟩

lemma thm_13_2_inter_unselected_empty {Ω ι : Type*} {A : ι → Set Ω}
    (hdisj : Pairwise fun i j => Disjoint (A i) (A j))
    {I : Finset ι} {C : Set Ω} {i : ι}
    (hC : C = ⋃ j ∈ I, A j) (hi : i ∉ I) :
    C ∩ A i = ∅ := by
  ext ω
  constructor
  · intro hω
    rw [hC] at hω
    rcases Set.mem_iUnion.1 hω.1 with ⟨j, hjrest⟩
    rcases Set.mem_iUnion.1 hjrest with ⟨hjI, hωj⟩
    have hji : j ≠ i := by
      intro hEq
      exact hi (by simpa [hEq] using hjI)
    exact (Set.disjoint_left.mp (hdisj hji)) hωj hω.2
  · intro hω
    simp at hω

theorem thm_13_2_left_selected_sum {Ω ι : Type*}
    [MeasurableSpace Ω] [Fintype ι] {P : Measure Ω} [IsFiniteMeasure P]
    {A : ι → Set Ω} {X : Ω → ℝ} {C : Set Ω} {I : Finset ι}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤)
    (hdisj : Pairwise fun i j => Disjoint (A i) (A j))
    (hC : C = ⋃ i ∈ I, A i) :
    ∫ ω in C,
        def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
      ∑ i ∈ I, thm_13_2_atomWeightedAverage P A X hA hA_top i := by
  classical
  have hCmeas : MeasurableSet C := by
    rw [hC]
    exact Finset.measurableSet_biUnion I (fun i _ => hA i)
  rw [thm_13_2_integral_finitePartitionCE_on hA hA_top hCmeas]
  calc
    (∑ i, def_13_2_atomConditionalExpectation P A X i (hA i) (hA_top i) *
        (P (C ∩ A i)).toReal)
        = ∑ i, if i ∈ I then thm_13_2_atomWeightedAverage P A X hA hA_top i else 0 := by
      refine Finset.sum_congr rfl ?_
      intro i _hi
      by_cases hiI : i ∈ I
      · rw [if_pos hiI, thm_13_2_inter_selected_self hC hiI]
        rfl
      · rw [if_neg hiI, thm_13_2_inter_unselected_empty hdisj hC hiI]
        simp
    _ = ∑ i ∈ I, thm_13_2_atomWeightedAverage P A X hA hA_top i := by
      have hfilter : Finset.univ.filter (fun i : ι => i ∈ I) = I := by
        ext i
        simp
      rw [← Finset.sum_filter, hfilter]

theorem thm_13_2_selected_weightedAverage_eq_sum_integrals {Ω ι : Type*}
    [MeasurableSpace Ω] {P : Measure Ω} {A : ι → Set Ω} {X : Ω → ℝ}
    {I : Finset ι}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) :
    ∑ i ∈ I, thm_13_2_atomWeightedAverage P A X hA hA_top i =
      ∑ i ∈ I, ∫ ω in A i, X ω ∂P := by
  exact Finset.sum_congr rfl
    (fun i _hi => thm_13_2_atomWeightedAverage_eq_integral P A X i hA hA_top)

theorem thm_13_2_right_selected_sum {Ω ι : Type*} [MeasurableSpace Ω]
    {P : Measure Ω} {A : ι → Set Ω} {X : Ω → ℝ} {C : Set Ω} {I : Finset ι}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hdisj : Pairwise fun i j => Disjoint (A i) (A j))
    (hX : Integrable X P)
    (hC : C = ⋃ i ∈ I, A i) :
    ∫ ω in C, X ω ∂P = ∑ i ∈ I, ∫ ω in A i, X ω ∂P := by
  rw [hC]
  exact integral_biUnion_finset I (fun i _ => hA i)
    (fun i _ j _ hij => hdisj hij) (fun i _ => hX.restrict)

theorem thm_13_2_selected_atoms {Ω ι : Type*}
    [MeasurableSpace Ω] [Fintype ι] {P : Measure Ω} [IsFiniteMeasure P]
    {A : ι → Set Ω} {X : Ω → ℝ} {C : Set Ω} {I : Finset ι}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤)
    (hdisj : Pairwise fun i j => Disjoint (A i) (A j))
    (hX : Integrable X P)
    (hC : C = ⋃ i ∈ I, A i) :
    ∫ ω in C,
        def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
      ∫ ω in C, X ω ∂P := by
  calc
    ∫ ω in C,
        def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
        ∑ i ∈ I, thm_13_2_atomWeightedAverage P A X hA hA_top i :=
      thm_13_2_left_selected_sum hA hA_top hdisj hC
    _ = ∑ i ∈ I, ∫ ω in A i, X ω ∂P :=
      thm_13_2_selected_weightedAverage_eq_sum_integrals hA hA_top
    _ = ∫ ω in C, X ω ∂P :=
      (thm_13_2_right_selected_sum hA hdisj hX hC).symm

/-- The finite-partition total weighted-sum identity used as a corollary of
Theorem 13.2. -/
theorem thm_13_2_total_partition_sum_integrals {Ω ι : Type*}
    [MeasurableSpace Ω] [Fintype ι]
    {P : Measure Ω} [IsFiniteMeasure P] {A : ι → Set Ω} {X : Ω → ℝ}
    (hA : ∀ i : ι, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤) :
    ∫ ω, def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
      ∑ i, ∫ ω in A i, X ω ∂P := by
  rw [thm_13_2_total_expectation hA hA_top,
    thm_13_2_weightedAverage_eq_sum_integrals P A X hA hA_top]

/-- Theorem 13.2: for every event `C` in the sigma-field generated by the
finite partition, the finite-partition conditional expectation integrates over
`C` to the same value as `X`. -/
theorem thm_13_2_canonical {Ω ι : Type*} [𝓕 : MeasurableSpace Ω] [Fintype ι]
    {P : Measure Ω} [IsFiniteMeasure P] {𝓖 : MeasurableSpace Ω}
    {A : ι → Set Ω} {X : Ω → ℝ} {C : Set Ω}
    (hDomain : @def_13_2_sourceDomain Ω ι 𝓕 _ P 𝓖 A X)
    (hC : @MeasurableSet Ω 𝓖 C) :
    let hA : ∀ i : ι, @MeasurableSet Ω 𝓕 (A i) :=
      @thm_13_2_sourceAtomMeasurable Ω ι 𝓕 _ P 𝓖 A X hDomain
    ∫ ω in C,
        @def_13_2_finitePartitionConditionalExpectation Ω ι 𝓕 _ P A X
          hA hDomain.2.2.2.1 ω ∂P =
      ∫ ω in C, X ω ∂P := by
  dsimp
  rcases thm_13_2_generated_event_atomUnion
      hDomain.2.1 hDomain.2.2.2.2.1 hC with ⟨I, hCI⟩
  exact @thm_13_2_selected_atoms Ω ι 𝓕 _ P _ A X C I
    (@thm_13_2_sourceAtomMeasurable Ω ι 𝓕 _ P 𝓖 A X hDomain)
    hDomain.2.2.2.1 hDomain.2.1.2 hDomain.2.2.2.2.2.2.2 hCI

/-- Theorem 13.2 in the exported Definition 13.2 interface: if `Y` is the
finite-partition conditional expectation of `X` given `𝓖`, then the defining
integral identity holds for every `C ∈ 𝓖`. -/
theorem thm_13_2 {Ω ι : Type*} [𝓕 : MeasurableSpace Ω] [Fintype ι]
    {P : Measure Ω} [IsFiniteMeasure P] {𝓖 : MeasurableSpace Ω}
    {A : ι → Set Ω} {X Y : Ω → ℝ} {C : Set Ω}
    (hY : @def_13_2 Ω ι 𝓕 _ P 𝓖 A X Y)
    (hC : @MeasurableSet Ω 𝓖 C) :
    ∫ ω in C, Y ω ∂P = ∫ ω in C, X ω ∂P := by
  rcases hY with ⟨hDomain, hA, hA_top, rfl⟩
  rcases thm_13_2_generated_event_atomUnion
      hDomain.2.1 hDomain.2.2.2.2.1 hC with ⟨I, hCI⟩
  exact @thm_13_2_selected_atoms Ω ι 𝓕 _ P _ A X C I
    hA hA_top hDomain.2.1.2 hDomain.2.2.2.2.2.2.2 hCI

/-- The total-expectation identity `(13.2)`: if the atoms cover `Ω`, then
the expectation of the finite-partition conditional expectation equals the
ordinary expectation of `X`. -/
theorem thm_13_2_total_expectation_eq_integral_of_partition {Ω ι : Type*}
    [MeasurableSpace Ω] [Fintype ι]
    {P : Measure Ω} [IsFiniteMeasure P] {A : ι → Set Ω} {X : Ω → ℝ}
    (hA : ∀ i, MeasurableSet (A i))
    (hA_top : ∀ i : ι, P (A i) ≠ ⊤)
    (hdisj : Pairwise fun i j => Disjoint (A i) (A j))
    (hcover : (⋃ i, A i) = Set.univ)
    (hX : ∀ i, IntegrableOn X (A i) P) :
    ∫ ω, def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
      ∫ ω, X ω ∂P := by
  calc
    ∫ ω, def_13_2_finitePartitionConditionalExpectation P A X hA hA_top ω ∂P =
        ∑ i, ∫ ω in A i, X ω ∂P :=
      thm_13_2_total_partition_sum_integrals hA hA_top
    _ = ∫ ω in ⋃ i, A i, X ω ∂P :=
      (integral_iUnion_fintype hA hdisj hX).symm
    _ = ∫ ω, X ω ∂P := by
      rw [hcover, setIntegral_univ]

/-- The total-expectation identity `(13.2)`, obtained from Theorem 13.2 by
setting `C = Ω`. -/
theorem thm_13_2_total_expectation_eq_integral {Ω ι : Type*}
    [𝓕 : MeasurableSpace Ω] [Fintype ι]
    {P : Measure Ω} [IsFiniteMeasure P] {𝓖 : MeasurableSpace Ω}
    {A : ι → Set Ω} {X Y : Ω → ℝ}
    (hY : @def_13_2 Ω ι 𝓕 _ P 𝓖 A X Y) :
    ∫ ω, Y ω ∂P = ∫ ω, X ω ∂P := by
  simpa [setIntegral_univ] using
    (@thm_13_2 Ω ι 𝓕 _ P _ 𝓖 A X Y Set.univ hY
      (@MeasurableSet.univ Ω 𝓖))
