import Mathlib
import ToyApollo.Output.thm_13_12

/-
TASK ID: thm_13_13
TYPE: Theorem_with_Proof
SOURCE PLAN: chapter13-discrete-random-variable
TASK CONTENT:
\begin{thmbox}{13.13}
\end{thmbox}

Suppose X and Y are discrete random variables taking values in

{0,1,2,..., }Let the joint pmf of X and Y be pXY (x, y), and the marginal

distribution of Y be pY (y)= \sum

x\geq 0 pXY (x, y)When g(X) is integrable, we

have

E[g(X)\vertY= y ]=

\sum

x\geq 0

g(x)pX\vertY (x\verty),

where pX\vertY (x\verty) is defined as pXY (x,y)

pY (y) In particular , if X is integrable, the

conditional expectation of X given Y is

E[X\vertY= y ]=

\sum

x\geq 0

xpX\vertY (x\verty).

\textit{Proof} Let Ay be the event .{: Y() = y },f o r y= 0 ,1,2,3... F r o m

Theorem 13.12,f o r\in A y ,we have

E[g(X)\vertY]()= 1

P(Ay)

\int

Ay

g(x)dP = 1

pY (y)

\sum

x\geq 0

g(x)pXY (x, y).

Thus, we can write

E[g(X)\vertY= y ]=

\sum

x\geq 0

g(x) pXY (x, y)

pY (y) =

\sum

x\geq 0

g(x)pX\vertY (x\verty)

fory= 0 ,1,2,... \hfill $\square$
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open scoped BigOperators

noncomputable section

/-- The atom `A_y = {ω : Y(ω) = y}` induced by a discrete observation `Y`. -/
def thm_13_13_atom {Ω : Type*} (Y : Ω → ℕ) (y : ℕ) : Set Ω :=
  {ω | Y ω = y}

/-- The atoms of a natural-valued random variable form the countable partition
used in Theorem 13.12. -/
theorem thm_13_13_atoms_countablePartition {Ω : Type*} (Y : Ω → ℕ) :
    thm_13_12_countablePartition (thm_13_13_atom Y) := by
  constructor
  · intro ω
    exact ⟨Y ω, rfl⟩
  · intro i j hij
    rw [Set.disjoint_left]
    intro ω hi hj
    exact hij (hi.symm.trans hj)

/-- Joint and marginal pmf data for the discrete pair `(X,Y)`.  The last
clause identifies the marginal mass of `Y=y` with the probability of the atom
`A_y`, exactly the substitution made in the textbook proof. -/
def thm_13_13_discreteJointLaw {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X Y : Ω → ℕ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ) : Prop :=
  (∀ y : ℕ, pY y = ∑' x : ℕ, pXY x y) ∧
    (∀ x y : ℕ, pXY x y =
      (P {ω | X ω = x ∧ Y ω = y}).toReal) ∧
    (∀ y : ℕ, pY y = (P (thm_13_13_atom Y y)).toReal)

/-- The conditional pmf `p_{X|Y}(x|y) = p_{XY}(x,y) / p_Y(y)`. -/
def thm_13_13_conditionalPMF
    (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ) (x y : ℕ) : ℝ :=
  pXY x y / pY y

/-- The textbook series formula for `E[g(X) | Y = y]`. -/
def thm_13_13_conditionalExpectationFormula
    (g : ℕ → ℝ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ) (y : ℕ) : ℝ :=
  ∑' x : ℕ, g x * thm_13_13_conditionalPMF pXY pY x y

/-- The particular series formula for `E[X | Y = y]`. -/
def thm_13_13_identityConditionalExpectationFormula
    (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ) (y : ℕ) : ℝ :=
  thm_13_13_conditionalExpectationFormula (fun x : ℕ => (x : ℝ)) pXY pY y

/-- `E[g(X)|Y=y]`, represented by Definition 13.1 as conditioning on the atom
`A_y`.  Theorem 13.12 justifies this atomwise reading when the conditioning
sigma-field is generated by `Y`. -/
def thm_13_13_conditionalExpectationGivenValue {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsFiniteMeasure P] (X Y : Ω → ℕ) (g : ℕ → ℝ) (y : ℕ)
    (hY : Measurable Y) (hAtom0 : P (thm_13_13_atom Y y) ≠ 0) : ℝ :=
  def_13_1 P (thm_13_13_atom Y y)
    (hY (measurableSet_singleton y)) hAtom0
    (measure_ne_top P (thm_13_13_atom Y y)) (fun ω => g (X ω))

/-- The countable-partition conditional-expectation formula from
Theorem 13.12, specialized to the atoms of `Y`. -/
def thm_13_13_partitionConditionalExpectation {Ω : Type*}
    [MeasurableSpace Ω] (P : Measure Ω) [IsFiniteMeasure P] (X Y : Ω → ℕ)
    (g : ℕ → ℝ) : Ω → ℝ :=
  thm_13_12_countablePartitionConditionalExpectation P
    (thm_13_13_atom Y) (fun ω => g (X ω))

/-- On the atom `A_y`, the Theorem 13.12 partition formula has the value
`E[g(X)|A_y]`. -/
theorem thm_13_13_partitionConditionalExpectation_apply {Ω : Type*}
    [MeasurableSpace Ω] (P : Measure Ω) [IsFiniteMeasure P] (X Y : Ω → ℕ)
    (g : ℕ → ℝ) (hY : Measurable Y) {y : ℕ} {ω : Ω}
    (hAtom0 : P (thm_13_13_atom Y y) ≠ 0)
    (hω : ω ∈ thm_13_13_atom Y y) :
    thm_13_13_partitionConditionalExpectation P X Y g ω =
      thm_13_13_conditionalExpectationGivenValue P X Y g y hY hAtom0 := by
  rw [thm_13_13_partitionConditionalExpectation]
  exact thm_13_12_countablePartitionConditionalExpectation_of_mem_wellDefined
    P (fun ω => g (X ω)) (thm_13_13_atoms_countablePartition Y) hω
    (hY (measurableSet_singleton y)) hAtom0

/-- Support for the source step
`∫_{A_y} g(X) dP = ∑_x g(x) p_{XY}(x,y)`.  This is the standard discrete
change from integration over the atom `Y=y` to summation over the sub-atoms
`{X=x,Y=y}`. -/
def thm_13_13_atomIntegralSupport {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X Y : Ω → ℕ) (g : ℕ → ℝ)
    (pXY : ℕ → ℕ → ℝ) : Prop :=
  ∀ y : ℕ,
    (∫ ω in thm_13_13_atom Y y, g (X ω) ∂P) =
      ∑' x : ℕ, g x * pXY x y

/-- The atom-integral step from the source proof, proved by pushing the
restricted measure on `A_y` forward along the discrete random variable `X` and
then using the countable-space integral formula. -/
theorem thm_13_13_atomIntegral_from_jointLaw {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X Y : Ω → ℕ) (g : ℕ → ℝ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ)
    (hX : Measurable X)
    (hInt : Integrable (fun ω => g (X ω)) P)
    (hLaw : thm_13_13_discreteJointLaw P X Y pXY pY) :
    thm_13_13_atomIntegralSupport P X Y g pXY := by
  intro y
  let μy : Measure ℕ := Measure.map X (P.restrict (thm_13_13_atom Y y))
  have hg_sm : AEStronglyMeasurable g μy := by
    exact (measurable_of_countable g).aestronglyMeasurable
  have hX_ae : AEMeasurable X (P.restrict (thm_13_13_atom Y y)) :=
    hX.aemeasurable
  have hg_int_map : Integrable g μy := by
    exact (integrable_map_measure hg_sm hX_ae).2 hInt.integrableOn
  calc
    (∫ ω in thm_13_13_atom Y y, g (X ω) ∂P)
        = ∫ x, g x ∂μy := by
          symm
          exact integral_map hX_ae hg_sm
    _ = ∑' x : ℕ, μy.real {x} • g x := by
          exact integral_countable hg_int_map
    _ = ∑' x : ℕ, g x * pXY x y := by
          apply tsum_congr
          intro x
          have hμ : μy.real {x} = pXY x y := by
            calc
              μy.real {x}
                  = ((P.restrict (thm_13_13_atom Y y)) (X ⁻¹' {x})).toReal := by
                      simp [μy, measureReal_def,
                        Measure.map_apply hX (measurableSet_singleton x)]
              _ = (P ((X ⁻¹' {x}) ∩ thm_13_13_atom Y y)).toReal := by
                      rw [Measure.restrict_apply (hX (measurableSet_singleton x))]
              _ = (P {ω : Ω | X ω = x ∧ Y ω = y}).toReal := by
                      congr 1
              _ = pXY x y := (hLaw.2.1 x y).symm
          rw [hμ]
          simp [mul_comm]

/-- The algebraic passage from
`(∑_x g(x)p_{XY}(x,y))/p_Y(y)` to `∑_x g(x)p_{X|Y}(x|y)`. -/
theorem thm_13_13_conditionalPMFSeries
    (g : ℕ → ℝ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ) (y : ℕ) :
    (∑' x : ℕ, g x * thm_13_13_conditionalPMF pXY pY x y) =
      (∑' x : ℕ, g x * pXY x y) / pY y := by
  rw [div_eq_mul_inv, ← tsum_mul_right]
  congr with x
  simp [thm_13_13_conditionalPMF, div_eq_mul_inv]
  ring

/-- Theorem 13.13: the conditional expectation at the value `Y=y` is the
conditional-pmf weighted sum. -/
theorem thm_13_13 {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X Y : Ω → ℕ) (g : ℕ → ℝ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ)
    (hX : Measurable X) (hY : Measurable Y)
    (hInt : Integrable (fun ω => g (X ω)) P)
    (hLaw : thm_13_13_discreteJointLaw P X Y pXY pY)
    (y : ℕ) (hAtom0 : P (thm_13_13_atom Y y) ≠ 0) :
    thm_13_13_conditionalExpectationGivenValue P X Y g y hY hAtom0 =
      thm_13_13_conditionalExpectationFormula g pXY pY y := by
  let hIntegral := thm_13_13_atomIntegral_from_jointLaw P X Y g pXY pY hX hInt hLaw
  calc
    thm_13_13_conditionalExpectationGivenValue P X Y g y hY hAtom0
        = (∫ ω in thm_13_13_atom Y y, g (X ω) ∂P) /
            (P (thm_13_13_atom Y y)).toReal := by
          exact thm_13_12_def_13_1_simple_formula P (thm_13_13_atom Y y)
            (hY (measurableSet_singleton y)) hAtom0
            (measure_ne_top P (thm_13_13_atom Y y)) (fun ω => g (X ω))
    _ = (∑' x : ℕ, g x * pXY x y) / pY y := by
          rw [hIntegral y, ← hLaw.2.2 y]
    _ = thm_13_13_conditionalExpectationFormula g pXY pY y := by
          rw [thm_13_13_conditionalExpectationFormula,
            thm_13_13_conditionalPMFSeries]

/-- The Theorem 13.12 partition version, evaluated on `A_y`, gives the
conditional-pmf series. -/
theorem thm_13_13_partitionFormula_on_atom {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X Y : Ω → ℕ) (g : ℕ → ℝ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ)
    (hX : Measurable X) (hY : Measurable Y)
    (hInt : Integrable (fun ω => g (X ω)) P)
    (hLaw : thm_13_13_discreteJointLaw P X Y pXY pY)
    {y : ℕ} {ω : Ω} (hAtom0 : P (thm_13_13_atom Y y) ≠ 0)
    (hω : ω ∈ thm_13_13_atom Y y) :
    thm_13_13_partitionConditionalExpectation P X Y g ω =
      thm_13_13_conditionalExpectationFormula g pXY pY y := by
  rw [thm_13_13_partitionConditionalExpectation_apply P X Y g hY hAtom0 hω]
  exact thm_13_13 P X Y g pXY pY hX hY hInt hLaw y hAtom0

/-- The version-on-an-atom reading used in the proof: if a version of
`E[g(X)|Y]` is known to take the atomwise value on `A_y`, then it agrees there
with the conditional-pmf series. -/
theorem thm_13_13_version_on_atom {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X Y : Ω → ℕ) (g : ℕ → ℝ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ)
    (CE : Ω → ℝ) (hX : Measurable X) (hY : Measurable Y)
    (hInt : Integrable (fun ω => g (X ω)) P)
    (hLaw : thm_13_13_discreteJointLaw P X Y pXY pY)
    {y : ℕ} (hAtom0 : P (thm_13_13_atom Y y) ≠ 0)
    (hAtomValue :
      ∀ ω ∈ thm_13_13_atom Y y,
        CE ω = thm_13_13_conditionalExpectationGivenValue P X Y g y hY hAtom0)
    {ω : Ω} (hω : ω ∈ thm_13_13_atom Y y) :
    CE ω = thm_13_13_conditionalExpectationFormula g pXY pY y := by
  rw [hAtomValue ω hω]
  exact thm_13_13 P X Y g pXY pY hX hY hInt hLaw y hAtom0

/-- The particular case `g(x)=x`, giving the displayed formula for
`E[X|Y=y]`. -/
theorem thm_13_13_identity {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P]
    (X Y : Ω → ℕ) (pXY : ℕ → ℕ → ℝ) (pY : ℕ → ℝ)
    (hX : Measurable X) (hY : Measurable Y)
    (hInt : Integrable (fun ω => (X ω : ℝ)) P)
    (hLaw : thm_13_13_discreteJointLaw P X Y pXY pY)
    (y : ℕ) (hAtom0 : P (thm_13_13_atom Y y) ≠ 0) :
    thm_13_13_conditionalExpectationGivenValue P X Y
        (fun x : ℕ => (x : ℝ)) y hY hAtom0 =
      thm_13_13_identityConditionalExpectationFormula pXY pY y := by
  exact thm_13_13 P X Y (fun x : ℕ => (x : ℝ)) pXY pY hX hY
    hInt hLaw y hAtom0
