import Mathlib
import ToyApollo.Output.def_13_3
import ToyApollo.Output.def_13_4
import ToyApollo.Output.thm_13_4
import ToyApollo.Output.thm_13_6
import ToyApollo.Output.thm_13_7

/-
TASK ID: thm_13_9
TYPE: Theorem_with_Proof
SOURCE PLAN: chapter13-properties
TASK CONTENT:
\begin{thmbox}{13.9}
\end{thmbox}

Suppose XY are in L1(P,\mathcal{F}), where X is a \mathcal{G}-measurable function and Y is

\mathcal{F}-measurable and integrable, then

E[XY\vert\mathcal{G}]= XE[Y\vert\mathcal{G}]as.

In particular , when X is a function of Z , we have E[XY\vertZ]= XE[Y\vertZ] as.

\textit{Proof} We first show that, for any \mathcal{G}-measurable set A ,

\int

B

E[1AY\vert\mathcal{G}]dP =

\int

B

1AE[Y\vert\mathcal{G}]dP B\in \mathcal{G}. (13.10)

For eachB\in \mathcal{G}, the right-hand side of (13.10) equals

\int

1B\capAE[Y\vert\mathcal{G}]dP =

\int

B\capA

E[Y\vert\mathcal{G}]dP =

\int

B\capA

Yd P . ( B \cap A \in\mathcal{G}).

Meanwhile, the left-hand side of (13.10) is equal to

\int

B

1AYd P =

\int

1B\capAYd P =

\int

B\capA

Yd P . ( B \cap A \in\mathcal{G}).

This proves that (13.10) holds for allB\in \mathcal{G}, and hence for all \mathcal{G}-measurable simple

functions. Extend (13.10) to nonnegative functions and real-valued functions. \hfill $\square$
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory
open ProbabilityTheory

noncomputable section

/-- The indicator-set step in the proof of Theorem 13.9. Conditioning an
indicator-restricted variable over a `G`-measurable set pulls the indicator
outside. -/
theorem thm_13_9_indicator {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓖 : SigmaField Ω} (_h𝓖 : IsSubSigmaField 𝓖 𝓕)
    [SigmaFinite (P.trim _h𝓖)] {A : Set Ω} {Y : Ω → ℝ}
    (hY : Integrable Y P) (hA : IsMeasurableIn 𝓖 A) :
    P[A.indicator Y | 𝓖] =ᵐ[P] A.indicator (P[Y | 𝓖]) :=
  condExp_indicator (μ := P) (m := 𝓖) (s := A) hY hA

/-- Pull-out property for a multiplier already measurable with respect to the
conditioning sigma-field. -/
theorem thm_13_9_pullout {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓖 : SigmaField Ω} (h𝓖 : IsSubSigmaField 𝓖 𝓕)
    [SigmaFinite (P.trim h𝓖)] {X Y : Ω → ℝ}
    (hX : GMeasurable 𝓖 X) (hXY : Integrable (X * Y) P)
    (hY : Integrable Y P) :
    P[X * Y | 𝓖] =ᵐ[P] X * P[Y | 𝓖] := by
  have hXsm : StronglyMeasurable[𝓖] X :=
    (show Measurable[𝓖] X from hX).stronglyMeasurable
  exact condExp_mul_of_stronglyMeasurable_left
    (μ := P) (m := 𝓖) (f := X) (g := Y) hXsm hXY hY

/-- Theorem 13.9: if `X` is `G`-measurable, then it can be pulled outside
conditional expectation. -/
theorem thm_13_9 {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} {𝓖 : SigmaField Ω} (h𝓖 : IsSubSigmaField 𝓖 𝓕)
    [SigmaFinite (P.trim h𝓖)] {X Y : Ω → ℝ}
    (hX : GMeasurable 𝓖 X) (hXY : Integrable (X * Y) P)
    (hY : Integrable Y P) :
    P[X * Y | 𝓖] =ᵐ[P] X * P[Y | 𝓖] :=
  @thm_13_9_pullout Ω 𝓕 P 𝓖 h𝓖 _ X Y hX hXY hY

/-- The "in particular" form: a measurable function of an observed random
variable is measurable with respect to the sigma-field generated by that
observation, so the same pull-out property holds when conditioning on `Z`. -/
theorem thm_13_9_function_of_observation {Ω S : Type*}
    [𝓕 : MeasurableSpace Ω] [MeasurableSpace S]
    {P : Measure Ω} {Z : Ω → S} {g : S → ℝ} {Y : Ω → ℝ}
    (hZ : Measurable Z) (hg : Measurable g)
    [SigmaFinite (P.trim (def_13_4_sigma_subSigma_of_measurable hZ))]
    (hXY : Integrable ((g ∘ Z) * Y) P) (hY : Integrable Y P) :
    P[(g ∘ Z) * Y | def_13_4_sigma Z] =ᵐ[P]
      (g ∘ Z) * P[Y | def_13_4_sigma Z] := by
  have hX : GMeasurable (def_13_4_sigma Z) (g ∘ Z) :=
    (show Measurable[def_13_4_sigma Z] (g ∘ Z) from
      hg.comp (comap_measurable Z))
  exact thm_13_9 (def_13_4_sigma_subSigma_of_measurable hZ) hX hXY hY
