import ToyApollo.Output.thm_13_12_support


/-
TASK ID: thm_13_12
TYPE: Theorem_with_Proof
SOURCE PLAN: chapter13-discrete-random-variable
TASK CONTENT:
\begin{thmbox}{13.12}
\end{thmbox}

Suppose that X is an integrable random variable defined on a probability

space.(\Omega,\mathcal{F},P) , andAi \in\mathcal{F},f o ri= 1 ,2,3,... , form a countable partition

of \Omega Let \mathcal{G}be the \sigma-algebra generated by .(Ai)\infty

i=1. Then, the conditional

expectationE[X\vert\mathcal{G}] is almost surely equal to .

\sum\infty

i=1 E[X\vertAi]1Ai .

\textit{Proof} Since the events Ai 's are mutually disjoint and their union is \Omega ,t h e

conditional expectation E[X\vert\mathcal{G}] is a function that is constant in each Ai Suppose

E[X\vert\mathcal{G}]()= c i for \in A i We can determine the value of ci from the defining

property of conditional expectation

ciP(Ai)=

\int

Ai

E[X\vert\mathcal{G}]dP =

\int

Ai

XdP.

Therefore,ci = 1

P(Ai)

\int

Ai XdP = E [X\vertAi]We define a \mathcal{G}-measurable random

variable

X()\coloneqq

\infty\sum

i=1

E[X\vertAi]1Ai ().

By linearity of expectation, for any finite union B= A i1 \cupAi2 \cup\cdot\cdot\cdot\cup Aim , where

i1,i2,...,i m are m distinct indices, we have

\int

B

XdP =

m\sum

k=1

\int

Aik

XdP =

m\sum

k=1

\int

Aik

XdP =

\int

B

XdP. (13.12)

For countably many indices, we can obtain the same equality by Theorem 13.11.

This completes the proof that X is a version of E[X\vert\mathcal{G}]\hfill $\square$

When the countable partition is induced by a discrete random variable, Theo-

rem 13.12 can be rephrased as follows.
-/

-- WRITE FINAL LEAN CODE BELOW

open MeasureTheory Filter
open scoped ENNReal

noncomputable section

/-- Theorem 13.12: for a countable partition, the abstract conditional
expectation is almost surely equal to the countable atomwise formula. -/
theorem thm_13_12 {Ω : Type*} [𝓕 : MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {𝓖 : SigmaField Ω}
    (h𝓖 : IsSubSigmaField 𝓖 𝓕) (X Y : Ω → ℝ) (A : ℕ → Set Ω)
    (hY : @def_13_3 Ω 𝓕 P 𝓖 h𝓖 X Y)
    (hPartition : thm_13_12_countablePartition A)
    (hGenerated : thm_13_12_generatedByPartition 𝓖 A) :
    Y =ᵐ[P] @thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X := by
  have hVersion :
      @def_13_3 Ω 𝓕 P 𝓖 h𝓖 X
        (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X) :=
    @thm_13_12_countablePartitionVersionSupport Ω 𝓕 P _ 𝓖 h𝓖 A X
      hPartition hGenerated
      (@def_13_3_integrable_original Ω 𝓕 P 𝓖 h𝓖 X Y hY)
  exact @thm_13_4 Ω 𝓕 P _ 𝓖 h𝓖 X Y
    (@thm_13_12_countablePartitionConditionalExpectation Ω 𝓕 P _ A X)
    hY hVersion
