import ToyApollo.Output.def_3_10
import Mathlib.MeasureTheory.PiSystem

/-!
# Theorem 3.7 (π-λ Theorem)

The textbook π-system and λ-system interfaces are bridged to Mathlib's
generated Dynkin-system theorem.  The existing root theorem is retained with
its exact Mathlib-facing signature for downstream compatibility.
-/

open MeasurableSpace

/-- A textbook `PiSystem` is, in particular, Mathlib's weaker
nonempty-intersection `IsPiSystem`. -/
theorem PiSystem.toIsPiSystem {Ω : Type*} {P : Set (Set Ω)}
    (hP : PiSystem P) : IsPiSystem P := by
  intro A hA B hB _h_nonempty
  exact hP hA hB

/-- A textbook `LambdaSystem` as a Mathlib Dynkin system with the same
underlying carrier. -/
def LambdaSystem.toDynkinSystem {Ω : Type*} {L : Set (Set Ω)}
    (hL : LambdaSystem L) : MeasurableSpace.DynkinSystem Ω where
  Has := fun s => s ∈ L
  has_empty := by
    have hcompl : (Set.univ : Set Ω)ᶜ ∈ L := hL.compl_mem hL.univ_mem
    simpa using hcompl
  has_compl := by
    intro s hs
    exact hL.compl_mem hs
  has_iUnion_nat := by
    intro f hdis hmem
    exact hL.iUnion_mem hdis hmem

/-- Membership in the converted Dynkin system is definitionally membership in
the original textbook lambda system. -/
@[simp] theorem LambdaSystem.toDynkinSystem_has
    {Ω : Type*} {L : Set (Set Ω)} (hL : LambdaSystem L) (s : Set Ω) :
    (hL.toDynkinSystem).Has s ↔ s ∈ L :=
  Iff.rfl

/-- Mathlib-facing compatibility helper used by the current downstream
theorems. -/
theorem thm_3_7 {α : Type*} {P : Set (Set α)} {L : DynkinSystem α}
    (hP : IsPiSystem P) (hPL : ∀ s ∈ P, L.Has s) :
    ∀ s, @MeasurableSet α (generateFrom P) s → L.Has s := by
  intro s hs
  have h := DynkinSystem.generateFrom_eq hP
  rw [h] at hs
  change (DynkinSystem.generate P).Has s at hs
  have key : DynkinSystem.generate P ≤ L := DynkinSystem.generate_le L hPL
  exact (DynkinSystem.le_def.mp key) s hs

/-- The textbook π-λ theorem: a lambda system containing a pi-system contains
the sigma-algebra generated by that pi-system. -/
theorem thm_3_7_textbook {Ω : Type*} {P L : Set (Set Ω)}
    (hP : PiSystem P) (hL : LambdaSystem L) (hPL : P ⊆ L) :
    ∀ s, @MeasurableSet Ω (MeasurableSpace.generateFrom P) s → s ∈ L := by
  have hP_mathlib : IsPiSystem P := PiSystem.toIsPiSystem hP
  have hPL_dynkin : ∀ s ∈ P, (hL.toDynkinSystem).Has s := by
    intro s hs
    exact (LambdaSystem.toDynkinSystem_has hL s).2 (hPL hs)
  intro s hs
  have hs_dynkin : (hL.toDynkinSystem).Has s :=
    thm_3_7 (P := P) (L := hL.toDynkinSystem)
      hP_mathlib hPL_dynkin s hs
  exact (LambdaSystem.toDynkinSystem_has hL s).1 hs_dynkin
