/-
TASK ID: ex_4_2_lebesgue_borel
SOURCE MATERIAL: omitted from the public source snapshot; see docs/repository_scope.md.
-/

import Mathlib
import ProbabilityTheory.chapter_04.thm_4_3

open MeasureTheory Set Cardinal




 



lemma image_div3_eq_preimage_mul3 (S : Set ℝ) :
    (· / 3) '' S = (· * 3) ⁻¹' S := by
      grind



lemma image_add2_div3_eq_preimage (S : Set ℝ) :
    (fun x => (2 + x) / 3) '' S = (fun y => y * 3 - 2) ⁻¹' S := by
      grind



lemma volume_image_div3 (S : Set ℝ) :
    volume ((· / 3) '' S) = ENNReal.ofReal (1/3) * volume S := by
  rw [image_div3_eq_preimage_mul3]
  have hmul : (fun x : ℝ => x * 3) = fun x : ℝ => 3 * x := by
    funext x
    ring
  rw [hmul, Real.volume_preimage_mul_left (show (3 : ℝ) ≠ 0 by norm_num)]
  norm_num



lemma volume_image_add2_div3 (S : Set ℝ) :
    volume ((fun x => (2 + x) / 3) '' S) = ENNReal.ofReal (1/3) * volume S := by
  have himage :
      (fun x : ℝ => (2 + x) / 3) '' S =
        (· / 3) '' ((fun y : ℝ => y + 2) '' S) := by
    ext z
    constructor
    · rintro ⟨x, hx, rfl⟩
      refine ⟨x + 2, ⟨x, hx, rfl⟩, ?_⟩
      ring
    · rintro ⟨y, ⟨x, hx, rfl⟩, rfl⟩
      exact ⟨x, hx, by ring⟩
  rw [himage, volume_image_div3]
  norm_num [Set.image_add_right]



lemma volume_preCantorSet_le (n : ℕ) :
    volume (preCantorSet n) ≤ ENNReal.ofReal ((2/3 : ℝ) ^ n) := by
  induction n with
  | zero =>
      erw [Real.volume_Icc]
      norm_num
  | succ n ih =>
      refine le_trans (MeasureTheory.measure_union_le _ _) ?_
      rw [volume_image_div3, volume_image_add2_div3]
      calc
        ENNReal.ofReal (1 / 3) * volume (preCantorSet n) +
            ENNReal.ofReal (1 / 3) * volume (preCantorSet n) =
            (ENNReal.ofReal (1 / 3) + ENNReal.ofReal (1 / 3)) *
              volume (preCantorSet n) := by ring
        _ ≤ (ENNReal.ofReal (1 / 3) + ENNReal.ofReal (1 / 3)) *
            ENNReal.ofReal ((2 / 3 : ℝ) ^ n) :=
          mul_le_mul_right ih _
        _ = ENNReal.ofReal ((2 / 3 : ℝ) ^ (n + 1)) := by
          rw [← ENNReal.ofReal_add] <;> norm_num
          rw [pow_succ]
          ring



lemma volume_cantorSet_eq_zero : volume cantorSet = 0 := by
  have h_cantor_subset : ∀ n, volume (preCantorSet n) ≤ ENNReal.ofReal ((2/3 : ℝ) ^ n) :=
    fun n => volume_preCantorSet_le n
  -- Since the Cantor set is the intersection of the preCantorSet n, its volume is less than or equal to the volume of any preCantorSet n.
  have h_cantor_le : ∀ n, volume cantorSet ≤ ENNReal.ofReal ((2/3 : ℝ) ^ n) := by
    exact fun n => le_trans ( MeasureTheory.measure_mono <| Set.iInter_subset _ _ ) ( h_cantor_subset n );
  -- Since $(2/3)^n \to 0$ as $n \to \infty$, the volume of the Cantor set must also be zero.
  have h_cantor_zero : Filter.Tendsto (fun n => ENNReal.ofReal ((2/3 : ℝ) ^ n)) Filter.atTop (nhds 0) := by
    simpa using ENNReal.tendsto_ofReal ( tendsto_pow_atTop_nhds_zero_of_lt_one ( by norm_num ) ( by norm_num : ( 2 : ℝ ) / 3 < 1 ) );
  exact le_antisymm ( le_of_tendsto_of_tendsto' tendsto_const_nhds h_cantor_zero h_cantor_le ) bot_le

 



lemma cardinal_borel_le_continuum :
    Cardinal.mk {t : Set ℝ | MeasurableSet t} ≤ Cardinal.continuum := by
      -- The Borel σ-algebra is generated by the countable basis of open sets in ℝ.
      have h_borel : (borel ℝ) = MeasurableSpace.generateFrom (TopologicalSpace.countableBasis ℝ) := by
        -- Apply the fact that the Borel σ-algebra is generated by the countable basis.
        apply TopologicalSpace.IsTopologicalBasis.borel_eq_generateFrom; exact TopologicalSpace.isBasis_countableBasis ℝ;
      have h_card : Cardinal.mk { t : Set ℝ | @MeasurableSet ℝ ( MeasurableSpace.generateFrom ( TopologicalSpace.countableBasis ℝ ) ) t } ≤ Cardinal.continuum := by
        apply_rules [ MeasurableSpace.cardinal_generateMeasurable_le_continuum ];
        exact le_trans ( Cardinal.mk_le_aleph0_iff.mpr <| by exact Encodable.countable ) ( Cardinal.aleph0_le_continuum );
      convert h_card using 1;
      congr!



lemma cardinal_powerset_cantorSet_gt_continuum :
    Cardinal.continuum < Cardinal.mk (Set cantorSet) := by
      -- The set of all functions from ℕ to Bool has cardinality 2^ℵ₀.
      have h_card_cantor : Cardinal.mk (cantorSet) = Cardinal.continuum := by
        refine' le_antisymm _ _;
        · exact le_trans ( Cardinal.mk_subtype_le _ ) ( by simp +decide [ Cardinal.mk_real ] );
        · refine' le_trans _ ( Cardinal.mk_le_of_injective _ );
          rotate_left;
          exact ( ℕ → Bool );
          exact fun f => ⟨ _, cantorSetEquivNatToBool.symm f |>.2 ⟩;
          · intro f g h; aesop;
          · simp +decide [ Cardinal.mk_real ];
      simp +decide [ h_card_cantor, Cardinal.cantor ]



lemma exists_non_borel_subset_cantorSet :
    ∃ N : Set ℝ, N ⊆ cantorSet ∧ ¬ MeasurableSet N := by
      -- By contradiction, assume every subset of cantorSet is measurable.
      by_contra h_contra
      have : Cardinal.mk (Set cantorSet) ≤ Cardinal.mk {t : Set ℝ | MeasurableSet t} := by
        refine' ⟨ fun N => ⟨ N.image Subtype.val, _ ⟩, _ ⟩;
        all_goals norm_num [ Function.Injective ];
        grind +revert;
      grind +suggestions

 



def LebesgueBorelMeasurable (f : ℝ → ℝ) : Prop :=
  ∀ ⦃B : Set ℝ⦄, MeasurableSet B → NullMeasurableSet (f ⁻¹' B) volume

 
def BorelBorelMeasurable (f : ℝ → ℝ) : Prop :=
  Measurable f



def theorem43MiddleSigmaFieldMismatch (f g : ℝ → ℝ) : Prop :=
  LebesgueBorelMeasurable f ∧ LebesgueBorelMeasurable g ∧ ¬ BorelBorelMeasurable g

 
lemma LebesgueBorelMeasurable.of_borel {f : ℝ → ℝ} (hf : Measurable f) :
    LebesgueBorelMeasurable f := by
  intro B hB
  exact (hf hB).nullMeasurableSet

 
lemma lebesgueBorelMeasurable_sq :
    LebesgueBorelMeasurable (fun x : ℝ => x ^ 2) :=
  LebesgueBorelMeasurable.of_borel (measurable_id.pow_const 2)

 
lemma indicator_one_preimage (N B : Set ℝ) :
    (Set.indicator N (fun _ => (1 : ℝ))) ⁻¹' B =
      {x : ℝ | x ∈ N ∧ (1 : ℝ) ∈ B} ∪ {x : ℝ | x ∉ N ∧ (0 : ℝ) ∈ B} := by
  ext x
  by_cases hx : x ∈ N <;> simp [Set.indicator, hx]



lemma LebesgueBorelMeasurable.indicator_one {N : Set ℝ}
    (hN : NullMeasurableSet N volume) :
    LebesgueBorelMeasurable (Set.indicator N (fun _ => (1 : ℝ))) := by
  intro B _hB
  rw [indicator_one_preimage]
  exact (hN.inter (NullMeasurableSet.const ((1 : ℝ) ∈ B))).union
    (hN.compl.inter (NullMeasurableSet.const ((0 : ℝ) ∈ B)))



lemma not_borelBorelMeasurable_indicator_one {N : Set ℝ} (hN : ¬ MeasurableSet N) :
    ¬ BorelBorelMeasurable (Set.indicator N (fun _ => (1 : ℝ))) := by
  intro hg
  exact hN ((measurable_indicator_const_iff (α := ℝ) (β := ℝ) (s := N) (1 : ℝ)).1 hg)



lemma measurableSet_of_sq_preimage {N : Set ℝ}
    (hN : N ⊆ Set.Ici 0)
    (h : MeasurableSet ((fun x : ℝ => x ^ 2) ⁻¹' N)) :
    MeasurableSet N := by
      convert h.preimage ( show Measurable Real.sqrt from ?_ ) |> MeasurableSet.inter <| show MeasurableSet ( Set.Ici 0 ) from measurableSet_Ici;
      · grind;
      · exact Real.continuous_sqrt.measurable



lemma not_measurable_indicator_comp_sq {N : Set ℝ}
    (hN : N ⊆ Set.Icc 0 1) (hNm : ¬ MeasurableSet N) :
    ¬ Measurable (Set.indicator N (fun _ => (1 : ℝ)) ∘ (fun x : ℝ => x ^ 2)) := by
      -- Suppose for contradiction that the composition is measurable.
      by_contra h_contra

      -- Then the preimage of {1} under the composition is measurable.
      have h_preimage : MeasurableSet ((fun x : ℝ => x ^ 2) ⁻¹' N) := by
        convert h_contra ( MeasurableSingletonClass.measurableSet_singleton 1 ) using 1 ; aesop;
      grind +suggestions

 



theorem ex_4_2_lebesgue_borel : ∃ (N : Set ℝ), N ⊆ cantorSet ∧
    NullMeasurableSet N volume ∧
    volume N = 0 ∧
    ¬ MeasurableSet N ∧
    let f : ℝ → ℝ := fun x => x ^ 2
    let g : ℝ → ℝ := Set.indicator N (fun _ => (1 : ℝ))
    LebesgueBorelMeasurable f ∧
      LebesgueBorelMeasurable g ∧
      ¬ BorelBorelMeasurable g ∧
      theorem43MiddleSigmaFieldMismatch f g := by
      obtain ⟨ N, hN₁, hN₂ ⟩ := exists_non_borel_subset_cantorSet
      have hNnullMeasure : volume N = 0 :=
        MeasureTheory.measure_mono_null hN₁ volume_cantorSet_eq_zero
      have hNnull : NullMeasurableSet N volume :=
        MeasureTheory.NullMeasurableSet.of_null hNnullMeasure
      refine' ⟨ N, hN₁, hNnull, hNnullMeasure, hN₂, _ ⟩
      dsimp
      have hf : LebesgueBorelMeasurable (fun x : ℝ => x ^ 2) := lebesgueBorelMeasurable_sq
      have hg : LebesgueBorelMeasurable (Set.indicator N (fun _ => (1 : ℝ))) :=
        LebesgueBorelMeasurable.indicator_one hNnull
      have hng : ¬ BorelBorelMeasurable (Set.indicator N (fun _ => (1 : ℝ))) :=
        not_borelBorelMeasurable_indicator_one hN₂
      exact ⟨hf, hg, hng, hf, hg, hng⟩
