/-
TASK ID: thm_4_4
SOURCE MATERIAL: omitted from the public source snapshot; see docs/repository_scope.md.
-/

import Mathlib.MeasureTheory.MeasurableSpace.Basic




section Theorem_4_4

open MeasureTheory Set

universe u v

variable {Ω : Type u} {Ω' : Type v}



theorem measurable_iff_preimage_generating_set
    [mF : MeasurableSpace Ω]
    {C : Set (Set Ω')}
    (f : Ω → Ω') :
    @Measurable Ω Ω' mF (MeasurableSpace.generateFrom C) f ↔
    ∀ A ∈ C, MeasurableSet (f ⁻¹' A) := by
  constructor
  · -- Forward direction: If f is measurable, then f⁻¹(A) is measurable for A ∈ C.
    intro hf A hA
    -- Since f is measurable, the preimage of any set measurable in σ(C) is measurable in ℱ.
    -- We apply the definition of measurability to A.
    apply hf
    -- In the σ-algebra generated by C, every element of C is measurable.
    exact MeasurableSpace.measurableSet_generateFrom hA

  · -- Backward direction: If preimages of generators are measurable, f is measurable.
    intro hA
    -- Mathlib's `measurable_generateFrom` is specifically designed for this.
    -- It states that if preimages of a generating set are measurable, the function is measurable.
    apply measurable_generateFrom
    exact hA



example
    [mF : MeasurableSpace Ω]
    [mG : MeasurableSpace Ω']
    {C : Set (Set Ω')}
    (hG : mG = MeasurableSpace.generateFrom C)
    (f : Ω → Ω') :
    Measurable f ↔ ∀ A ∈ C, MeasurableSet (f ⁻¹' A) := by
  -- Use the equality to substitute the generated σ-algebra for mG.
  rw [hG]
  exact measurable_iff_preimage_generating_set f

end Theorem_4_4
