/-
TASK ID: intro_13_1
TYPE: Remark
SOURCE PLAN: chapter13-finite-partition

This parent-facing file is a non-proof textual carrier for source narrative.
It preserves the remark text for Phase 2 status accounting and exports no
mathematical dependency.
-/

/-- Textual carrier for `Expectation Conditioned on a Finite Partition`. -/
def intro_13_1 : String :=
  "\\subsection*{13.1 Expectation Conditioned on a Finite Partition}\n\nAs a " ++
  "motivating example, suppose we want to obtain the average height of people" ++
  "\n\nin a country by taking uniform samples from the population. We define " ++
  "the set of\n\npeople in this country as \\Omega , and the uniform " ++
  "distribution on \\Omega as P We denote the\n\nheight of a person chosen from " ++
  "the population by X()The expectation E[X]\n\nrepresents the average height " ++
  "of the population. However, we can also compute\n\nthe average height in the" ++
  " country by first determining the average height in each\n\nprovince. Let " ++
  "E[X\\vertprovince A ] denote the average height in a given province A .\n\n" ++
  "The national average height can then be computed as a weighted average of " ++
  "the\n\nprovincial averages, with the weighting factors proportional to the " ++
  "population in the\n\nprovinces.\n\nWe can also partition the people in this " ++
  "country by the cities they live in. The\n\naverage height in a city is the " ++
  "conditional expectation E[X\\vertcity ]The partition of\n\nthe country into " ++
  "cities is a more refined partition compared to the partition into\n\n" ++
  "provinces. This example illustrates that the conditional expectation is " ++
  "closely related\n\nto how we partition the sample space.\n\nIn this chapter, " ++
  "we first review the conditional expectation of a random variable\n\ngiven an" ++
  " event. Then we define the conditional expectation conditioned on a\n\n" ++
  "\\sigma-algebra generated by a finite number of events. In the abstract " ++
  "definition of\n\nconditional expectation, we will condition on a general " ++
  "\\sigma-algebra. Finally, we will\n\ndiscuss filtrations and martingales as " ++
  "applications of conditional expectation.\n\nThroughout this chapter, we will" ++
  " work with a fixed probability space .(\\Omega,\\mathcal{F},P) .\n\nIn " ++
  "probability theory, we define the conditional probability of an event E " ++
  "given\n\nanother event A by P(A \\cap E)/P(A) , provided that P(A) > 0 This " ++
  "quantity\n\nrepresents the likelihood of the event E given that we already " ++
  "know that the event\n\nA has occurred.\n\nIf the event A is fixed and the " ++
  "event E varies, we obtain a measure function whose\n\nvalue is conditional " ++
  "probability."
